### ISSUE TITLE
Helper DLL Issue with 32bit JRE 

### ISSUE THREAD

**Issue by amitkumars1985** [TurboVNC/turbovnc#103]
VNC  : TurboVNC 2.1  x86
Server OS : RHEL 6.7
Client OS : Windows 10 
Java Version : JRE version: Java(TM) SE Runtime Environment (8.0_91-b14) (build 1.8.0_91-b14)
                      Java VM: Java HotSpot(TM) Client VM (25.91-b14 mixed mode windows-x86 )

While using JRE 32bit to connect to VNC client, GrabKey option is giving below exception : 

Aug 24, 2017 5:19:17 PM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyE:@...) returned error code 5.
CConn: connected to host Server1 port 5905
CConnection: Server supports RFB protocol version 3.8
CConnection: Using RFB protocol version 3.8
CConn: Using pixel format depth 24 (32bpp) little-endian rgb888
CConn: Requesting Tight encoding
CConn: Enabling GII
CConn: Enabling continuous updates
Viewport: WARNING: Could not invoke grabKeyboard() from TurboVNC Helper:
Viewport:   java.lang.Exception: The specified procedure could not be found.

Attached is the custom client which we are using to connect to VNC. 

[TurboVNC_2_1_WindowsJavaClient_x86.zip](https://github.com/TurboVNC/turbovnc/files/1249246/TurboVNC_2_1_WindowsJavaClient_x86.zip)

**Comment by dcommander** [comment]
Please try the latest 2.1.x pre-release build (https://turbovnc.org/DeveloperInfo/PreReleases).  I believe this has been fixed already, but the fix is post-2.1.1, so it is currently only available in the pre-release.  It will be in the upcoming 2.1.2 release.

**Comment by dcommander** [comment]
Also, please upgrade to 2.1.1.  2.1 is no longer the latest stable release, so it may contain bugs that have already been fixed.

**Comment by dcommander** [comment]
Closing as fixed.  Add a comment if you are still able to reproduce the issue with the latest pre-release build.
