### ISSUE TITLE
TurboVNC + Nvidia Driver. Black screen

### ISSUE THREAD

**Issue by deejayfrankcesco** [TurboVNC/turbovnc#115]
I lost two days to find a good way to manage my computer via VNC and I think that TurboVNC is a good solution but I didn't figured out this problem. 
I'm using a new installation of openSUSE Leap 42.3 (with GNOME).

I installed the official NVIDIA/CUDA drivers and all works like a charm.
Then I installed TurboVNC (and VirtualGL too). I configured the password and launched the /opt/TurboVNC/bin/vncserver (with -3dwm). It creates the server on display :2.

The problem is that when I try to connect from the client, the connection is opened correctly but the screen is always black. No mouse pointer, nothing.

Could be this related to the fact that actually Nvidia driver acts on main display and not in :2 ? 

I hope in your help, many thanks in advice.

The log from TurboVNC is attached.

_File: /home/deejayfrankcesco/.vnc/telescope:2.log                                 

09/01/2018 01:29:38 Framebuffer: BGRX 8/8/8/8
09/01/2018 01:29:38 Maximum clipboard transfer size: 1048576 bytes
09/01/2018 01:29:38 VNC extension running!
/bin/bash: error while loading shared libraries: libturbojpeg.so.0: cannot open shared object file: No such file or dir$

09/01/2018 01:39:01 Got connection from client 192.168.192.198
09/01/2018 01:39:01 Using protocol version 3.8
09/01/2018 01:39:01 Enabling TightVNC protocol extensions
09/01/2018 01:39:01 Advertising Tight auth cap 'VENCRYPT'
09/01/2018 01:39:01 Advertising Tight auth cap 'VNCAUTH_'
09/01/2018 01:39:01 Advertising Tight auth cap 'ULGNAUTH'
09/01/2018 01:39:02 Client requested VeNCrypt sub-type 258
09/01/2018 01:39:02 Successfully loaded symbols from libssl.so.1.0.0
09/01/2018 01:39:02 Successfully loaded symbols from libcrypto.so.1.0.0
09/01/2018 01:39:02 Deferring TLS handshake
09/01/2018 01:39:04 Full-control authentication enabled for 192.168.192.198
09/01/2018 01:39:04 Pixel format for client 192.168.192.198:
09/01/2018 01:39:04   32 bpp, depth 24, little endian
09/01/2018 01:39:04   true colour: max r 255 g 255 b 255, shift r 16 g 8 b 0
09/01/2018 01:39:04   no translation needed
09/01/2018 01:39:04 Enabling full-color cursor updates for client 192.168.192.198
09/01/2018 01:39:04 Enabling Desktop Size protocol extension for client 192.168.192.198
09/01/2018 01:39:04 Enabling Extended Desktop Size protocol extension for client 192.168.192.198
09/01/2018 01:39:04 rfbProcessClientNormalMessage: ignoring unknown encoding -307 (fffffecd)
09/01/2018 01:39:04 Enabling LastRect protocol extension for client 192.168.192.198
09/01/2018 01:39:04 Enabling Continuous Updates protocol extension for client 192.168.192.198
09/01/2018 01:39:04 Enabling Fence protocol extension for client 192.168.192.198
09/01/2018 01:39:04 Enabling GII extension for client 192.168.192.198
09/01/2018 01:39:04 Using tight encoding for client 192.168.192.198
09/01/2018 01:39:04 Using JPEG subsampling 0, Q100 for client 192.168.192.198
09/01/2018 01:39:04 Using JPEG quality 95 for client 192.168.192.198
09/01/2018 01:39:04 Using JPEG subsampling 0 for client 192.168.192.198
09/01/2018 01:39:04 Using Tight compression level 1 for client 192.168.192.198
09/01/2018 01:39:04 Using 1 thread for Tight encoding
09/01/2018 01:39:04 Client supports GII version 1
09/01/2018 01:39:04 New desktop size: 1240 x 824
09/01/2018 01:39:04 Continuous updates enabled
09/01/2018 01:39:04 Continuous updates enabled_

**Comment by dcommander** [comment]
VirtualGL takes care of redirecting the OpenGL commands to the main display, reading back the rendered 3D pixels, and drawing them to the TurboVNC display using only X11 drawing commands.  Starting the TurboVNC Server with `-3dwm` runs the window manager using VirtualGL.  But the fact that you're getting a black screen means that some part of that isn't working.  The first thing I'd do is try to run something simple using VirtualGL on the TurboVNC display.  Example:

```
DISPLAY=:2 vglrun /opt/VirtualGL/bin/glxspheres64
```

If that doesn't work, then you'll need to get it working using the instructions in the VirtualGL User's Guide before you can expect `/opt/TurboVNC/bin/vncserver -3dwm` to work properly.

**Comment by dcommander** [comment]
Also, this line concerns me:

```
/bin/bash: error while loading shared libraries: libturbojpeg.so.0: cannot open shared object file: No such file or dir$
```

Are you using our official VirtualGL and TurboVNC packages?  If so, then I'm not sure what is referring to libturbojpeg.so.0, since our official packages are statically linked with the TurboJPEG API library.

**Comment by deejayfrankcesco** [comment]
So, since probably I installed libjpegturbo from another repo, I cleaned the installation and I did it again. Now TurboVNC, VirtualGL and TurboJPEG are installed from official rpms. Doing the same test the new log is that showed in bottom. 
I would underline that without -3dwm the behaviour is the same. All black screen. But probably this is dued to the fact that gnome session require openGL (?)



LOG
-----


TurboVNC Server (Xvnc) 64-bit v2.1.2 (build 20170925)
Copyright (C) 1999-2017 The VirtualGL Project and many others (see README.txt)
Visit http://www.TurboVNC.org for more information on TurboVNC

09/01/2018 15:38:10 Using auth configuration file /etc/turbovncserver-security.conf
09/01/2018 15:38:10 Enabled authentication method 'tlsvnc'
09/01/2018 15:38:10 Enabled authentication method 'tlsotp'
09/01/2018 15:38:10 Enabled authentication method 'tlsplain'
09/01/2018 15:38:10 Enabled authentication method 'x509vnc'
09/01/2018 15:38:10 Enabled authentication method 'x509otp'
09/01/2018 15:38:10 Enabled authentication method 'x509plain'
09/01/2018 15:38:10 Enabled authentication method 'vnc'
09/01/2018 15:38:10 Enabled authentication method 'otp'
09/01/2018 15:38:10 Enabled authentication method 'unixlogin'
09/01/2018 15:38:10 Enabled authentication method 'plain'
09/01/2018 15:38:10 Desktop name 'TurboVNC: telescope:2 (deejayfrankcesco)' (telescope:2)
09/01/2018 15:38:10 Protocol versions supported: 3.3, 3.7, 3.8, 3.7t, 3.8t
09/01/2018 15:38:10 Listening for VNC connections on TCP port 5902
09/01/2018 15:38:10   Interface 0.0.0.0
09/01/2018 15:38:10 Listening for HTTP connections on TCP port 5802
09/01/2018 15:38:10   URL http://telescope:5802
09/01/2018 15:38:10   Interface 0.0.0.0
09/01/2018 15:38:10 Framebuffer: BGRX 8/8/8/8
09/01/2018 15:38:10 Maximum clipboard transfer size: 1048576 bytes
09/01/2018 15:38:10 VNC extension running!
/etc/X11/xim: Checking whether an input method should be started.
/etc/X11/xim: Checking whether an input method is specified in /home/deejayfrankcesco/.i18n.
/etc/X11/xim: line 74: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8)
sourcing /etc/sysconfig/language to get the value of INPUT_METHOD
INPUT_METHOD is not set or empty (no user selected input method).
Trying to start a default input method for the locale UTF-8 ...
There is no default input method for the current locale.
Dummy input method "none" (do not use any fancy input method by default)

(process:12532): Gtk-WARNING **: Locale not supported by C library.
        Using the fallback 'C' locale.
No protocol specified
[VGL] ERROR: Could not open display :0.

(process:12533): Gtk-WARNING **: Locale not supported by C library.
        Using the fallback 'C' locale.
No protocol specified
[VGL] ERROR: Could not open display :0.
gnome-session-binary[12484]: WARNING: software acceleration check failed: Child process exited with code 1
Unable to init server: Could not connect: Connection refused

** (gnome-session-failed:12534): WARNING **: Cannot open display:

09/01/2018 15:38:15 Got connection from client 192.168.192.198
09/01/2018 15:38:15 Using protocol version 3.8
09/01/2018 15:38:15 Enabling TightVNC protocol extensions
09/01/2018 15:38:15 Advertising Tight auth cap 'VENCRYPT'
09/01/2018 15:38:15 Advertising Tight auth cap 'VNCAUTH_'
09/01/2018 15:38:15 Advertising Tight auth cap 'ULGNAUTH'
09/01/2018 15:38:15 Client requested VeNCrypt sub-type 258
09/01/2018 15:38:15 Successfully loaded symbols from libssl.so.1.0.0
09/01/2018 15:38:15 Successfully loaded symbols from libcrypto.so.1.0.0
09/01/2018 15:38:15 Deferring TLS handshake
09/01/2018 15:38:17 Full-control authentication enabled for 192.168.192.198
09/01/2018 15:38:17 Pixel format for client 192.168.192.198:
09/01/2018 15:38:17   32 bpp, depth 24, little endian
09/01/2018 15:38:17   true colour: max r 255 g 255 b 255, shift r 16 g 8 b 0
09/01/2018 15:38:17   no translation needed
09/01/2018 15:38:17 Enabling full-color cursor updates for client 192.168.192.198
09/01/2018 15:38:17 Enabling Desktop Size protocol extension for client 192.168.192.198
09/01/2018 15:38:17 Enabling Extended Desktop Size protocol extension for client 192.168.192.198
09/01/2018 15:38:17 rfbProcessClientNormalMessage: ignoring unknown encoding -307 (fffffecd)
09/01/2018 15:38:17 Enabling LastRect protocol extension for client 192.168.192.198
09/01/2018 15:38:17 Enabling Continuous Updates protocol extension for client 192.168.192.198
09/01/2018 15:38:17 Enabling Fence protocol extension for client 192.168.192.198
09/01/2018 15:38:17 Enabling GII extension for client 192.168.192.198
09/01/2018 15:38:17 Using tight encoding for client 192.168.192.198
09/01/2018 15:38:17 Using JPEG subsampling 0, Q100 for client 192.168.192.198
09/01/2018 15:38:17 Using JPEG quality 95 for client 192.168.192.198
09/01/2018 15:38:17 Using JPEG subsampling 0 for client 192.168.192.198
09/01/2018 15:38:17 Using Tight compression level 1 for client 192.168.192.198
09/01/2018 15:38:17 Using 1 thread for Tight encoding
09/01/2018 15:38:17 Client supports GII version 1
09/01/2018 15:38:17 New desktop size: 1240 x 824
09/01/2018 15:38:17 Continuous updates enabled
09/01/2018 15:38:17 Continuous updates enabled

**Comment by deejayfrankcesco** [comment]
if I try to launch vglrun as @dcommander suggested on display 2, It returns:

Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
No protocol specified
[VGL] ERROR: Could not open display :0.

**Comment by dcommander** [comment]
That means VirtualGL is not configured properly.  As I said, you need to get VirtualGL working properly before `-3dwm` will work.  All `-3dwm` does is execute the window manager startup script using vglrun.

**Comment by deejayfrankcesco** [comment]
Thank you very much @dcommander . What do you said is true. I did an incorrect VirtualGL. Now all works!

**Comment by DevMohamedMI** [comment]
If $DISPLAY=:1 vglrun /opt/VirtualGL/bin/glxspheres64 works for someone but they can't get something like $/opt/TurboVNC/bin/vncserver -3dwm -geometry 2560x1600 to not show a black screen, try running $sudo chown -R <insert your username> ~ it worked for me

**Comment by mpdmanash** [comment]
For me `DISPLAY=:1 vglrun /opt/VirtualGL/bin/glxspheres64` was running well. Still `/opt/TurboVNC/bin/vncserver -3dwm -geometry 2560x1600` showed a black screen. Turns out, vncserver was not able to start the **xfce4** desktop environment. So in a separate ssh shell I ran `vglrun startxfce4` and TurboVNC showed the desktop environment.

**Comment by dcommander** [comment]
Why would you run Xfce 4 using VirtualGL?  Xfce is not a compositing window manager.  Anyhow, you would need to specify `-wm startxfce4` on the TurboVNC command line (or set `$wm = startxfce4` in **/etc/turbovncserver.conf** or **~/.vnc/turbovncserver.conf**) if you expect the TurboVNC Server to use that window manager.  TurboVNC will default to using GNOME otherwise.
