### ISSUE TITLE
Hotkey to change zoom level

### ISSUE THREAD

**Issue by ThomasKjoernes** [TurboVNC/turbovnc#117]
This would be very nice. Such as jusing ctrl+shift+ plus/minus/0 (reset)

**Comment by dcommander** [comment]
Please try the 2.2 evolving pre-release build.  It has this feature.  Let me know if the behavior needs any tweaking.

**Comment by ThomasKjoernes** [comment]
Oh, thanks, I will try it 😊

Thomas

Fra: DRC
Sendt: søndag 14. januar 2018 kl. 19:21
Til: TurboVNC/turbovnc
Kopi: ThomasKjoernes; Author
Emne: Re: [TurboVNC/turbovnc] Hotkey to change zoom level (#117)

Please try the 2.2 evolving pre-release build. It has this feature. Let me know if the behavior needs any tweaking.

**Comment by dcommander** [comment]
@ThomasKjoernes did you try it?

**Comment by dcommander** [comment]
Closing due to lack of user response.  Assumed working in 2.2 build.
