### ISSUE TITLE
Handle "@" in usernames for SSH tunnels

### ISSUE THREAD

**Issue by dario-pilori** [TurboVNC/turbovnc#120]
TurboVNC does not properly handle the username for SSH tunnels if it contains the "@" character.

Steps to reproduce the problem:
1. Write **name.surname@domain.com** as SSH user and **host.com** as host for SSH tunnel in the TurboVNC Viewer Options
2. Save this setting as Default
3. Close TurboVNC Viewer and open it again 
4. Now, in the SSH tunnel options it is written **name.surname** as SSH user and **domain.com@host.com** as host.
Similar issue occurs when using the **Via** option as command line.

Possible fix: use the last "@" character to distinguish user and host instead of the first "@".

Using TurboVNC Viewer v2.1.2 on Linux.

**Comment by dcommander** [comment]
Fixed in master/2.1.x stable.  (Pre-release build available.)
