### ISSUE TITLE
Using the clipboard to copy & paste Chinese has garbled between Windows and Ubuntu

### ISSUE THREAD

**Issue by fcying** [TurboVNC/turbovnc#122]
copy from windows chrome
![1](https://user-images.githubusercontent.com/106934/37240036-1c5f00a0-2480-11e8-8604-5350b9d5f46c.jpg)

paste to ubuntu file manager
![3](https://user-images.githubusercontent.com/106934/37240038-1fe00d50-2480-11e8-9f18-7a37a4911194.jpg)

Copy & paste English can be displayed normally

Is there any settting that can be fix it?

**Comment by dcommander** [comment]
Most likely related to the fact that RFB clipboard transfers are limited to ISO-8859-1.  This is a limitation in the protocol that will have to be worked around by implementing #113.

**Comment by fcying** [comment]
OK, I understand. I am looking forward to the update
