### ISSUE TITLE
Can TurboVNC manage a timeout for a vnc session?

### ISSUE THREAD

**Issue by al3x609** [TurboVNC/turbovnc#131]
I need to create  a time limit by session and then automatic kill those.

**Comment by dcommander** [comment]
Yes, pass `-idletimeout {t}` to vncserver when starting the session, where `{t}` is the maximum idle time for the session in seconds.  Also see the `max-idle-timeout` value in the TurboVNC Server security configuration file.  Refer to /opt/TurboVNC/man/Xvnc.man.

**Comment by al3x609** [comment]
maybe I did not explain myself well, I need to disconnect a VNC client after a certain assigned time, not only when there are no clients connected.

something that automatically disconnects the client and removes the open unix socket, after a limited time

**Comment by dcommander** [comment]
Why do you need this?

**Comment by dcommander** [comment]
The feature does not exist, which is why I'm asking about a use case.  I have to have that information before I can justify a business decision to add the feature.

**Comment by al3x609** [comment]
I work in a remote viewing project, where the client requests a remote desktop for a certain time, then it must release the resources also automatically, this involves removing the open sockets.

and I thought turbovnc had an option for this case.
