### ISSUE TITLE
TurboVNC on Ubuntu 18.04 not showing anything

### ISSUE THREAD

**Issue by jfha73** [TurboVNC/turbovnc#133]
Hello,

I installed TurboVNC 2.1.2 on my Ubuntu 18.04 box, I'm connecting to it using RealVNC Viewer from a Mac, but when I'm logged in to my Ubuntu, all I see is a Black Screen, I can see a pointer for the mouse and I can move it around, but nothing else is shown, what do I have to do so it works for me?

Thanks.

**Comment by dcommander** [comment]
TurboVNC 2.1.x doesn't work out of the box with 3D window managers.  Your options are:
* Install MATE.  TurboVNC 2.1.x will automatically use this on Ubuntu systems if it is installed.  MATE is a fork of GNOME 2 and thus doesn't require OpenGL.
* Install the GNOME Flashback window manager.  TurboVNC 2.1.x will automatically use this on Ubuntu systems if it is installed.
* If you have a GPU, you can install and configure VirtualGL, then start the TurboVNC Server with `-3dwm` to run Unity 3D using VirtualGL.
* Use TurboVNC 2.2 beta, which now has built-in support for 3D window managers (but bear in mind that its built-in OpenGL support is unaccelerated.  You have to use VirtualGL to get accelerated OpenGL.)

In general, MATE and GNOME Flashback are the cleanest solutions.  There are [known problems](https://github.com/TurboVNC/turbovnc/issues?utf8=%E2%9C%93&q=label%3A%22Unity%207.4%22) with using Unity 3D in any VNC environment.

**Comment by dcommander** [comment]
Leaving this open to remind me to test Ubuntu 18.04 and update the window manager reports:
https://turbovnc.org/Documentation/Compatibility
https://turbovnc.org/Documentation/Compatibility22

**Comment by dcommander** [comment]
NOTE: Apparently Ubuntu 18.04 uses GNOME 3 rather than Unity.  Ugh.  TurboVNC's default xstartup.turbovnc file doesn't currently handle this properly.  Making the following modification temporarily works around the issue:

```
--- xstartup.turbovnc.old	2018-08-09 23:16:47.099489082 -0500
+++ xstartup.turbovnc	2018-08-09 23:13:26.227681380 -0500
@@ -41,7 +41,7 @@
       # again.
       if [ -f /usr/share/gnome-session/sessions/ubuntu.session ]; then
         DESKTOP_SESSION=ubuntu;  export DESKTOP_SESSION
-        XDG_CURRENT_DESKTOP=Unity;  export XDG_CURRENT_DESKTOP
+        XDG_CURRENT_DESKTOP=ubuntu:GNOME;  export XDG_CURRENT_DESKTOP
       fi
       ;;
   esac
```

I'm investigating how to fix it permanently.  Also, issue #47 exists with GNOME 3/Ubuntu 18.04.
