### ISSUE TITLE
Java Viewer: Per-host options + the ability to save connection info files

### ISSUE THREAD

**Issue by dcommander** [TurboVNC/turbovnc#135]
Since the Windows TurboVNC Viewer will be retired in the next major release, this is a catch-all issue for any GUI features from the Windows TurboVNC Viewer that still need to be ported into the Java TurboVNC Viewer, including:

1. The ability to save connection profiles
2. Saving and managing settings per-connection instead of globally
3. The view-only, zoom, and clipboard transfer hotkeys from #45

**Comment by dcommander** [comment]
The view-only and zoom hotkeys have been implemented in the latest 3.0 evolving build. The clipboard transfer hotkey isn’t a good fit for the Java viewer, since it has independent settings for disabling inbound and outbound clipboard transfer. (The clipboard transfer hotkey was implemented primarily as an easy workaround for the flaky daemon-based clipboard transfer mechanism that has long since been replaced.)

**Comment by relcodedev** [comment]
Is there a possibility of providing the UI selection to options file mapping.  
I am trying to figure out the change to "Lossless Tight + Zlib (WAN)" translates to in the options file.  It is not obvious from docs.

**Comment by dcommander** [comment]
@relcodedev Yeah, it's a bit nonintuitive, because the format of .vnc connection info files comes from TightVNC 1.3.x, and I had to map TurboVNC features onto that format.  I'm about to replace all of that mess with a new .turbovnc connection info file format that just uses the TurboVNC Viewer command-line parameters.

In the meantime, you can achieve what you want with
```
quality=-1
compresslevel=6
```
For other mappings, refer to: https://github.com/TurboVNC/turbovnc/blob/d5e760cefe78794ec402de1e58102d370facf914/java/com/turbovnc/rfb/Params.java#L146-L305

**Comment by dcommander** [comment]
Per-host options were implemented in the TurboVNC 3.1 evolving code base back in August.  Later today, I plan to push a commit that implements a new .turbovnc connection info file format that accepts the same parameters and values that the TurboVNC Viewer accepts.  However, upon further reflection, the ability to save connection info files doesn't make a lot of sense with the TurboVNC Session Manager and the advanced authentication features that the TurboVNC Viewer supports.  If a TurboVNC session was started using the session manager, then (unless `SessMgrAuto` is explicitly disabled) the TurboVNC Viewer will only be able to connect to the session using SSH and will only be able to authenticate with the session using a one-time password.  There is no way to enable OTP authentication using a connection info file, and since SSH tunneling uses an ephemeral client-side port, creating a connection info file that properly emulated an SSH-tunneled connection would be tricky at best.  These days, connection info files are primarily meant to be generated on the fly by TurboVNC web portals and downloaded to the client via a web browser.  Once the viewer has connected to the TurboVNC session, the initial parameter state will have usually changed, so saving the parameters to a connection info file wouldn't usually allow the connection to be reproduced.  The only case in which that would work is the case in which the viewer was used only to connect to a static TurboVNC session using a static VNC password, and that is a "supported but de-emphasized" use case in TurboVNC these days.  Other use cases might be supportable with some difficulty, but it would require maintaining a separate copy of the parameters prior to the connection and synchronizing that copy whenever the primary parameters change (such as when using the Options dialog.)  A big reason why TightVNC needed a "save connection info file" feature was the fact that its connection info file format was somewhat inscrutable, but the new .turbovnc connection info file format addresses that concern.
