### ISSUE TITLE
Running under Java 10 causes jawt.dll to be not found

### ISSUE THREAD

**Issue by mslinn** [TurboVNC/turbovnc#137]
When running `vncviewer-javaw.bat`, the error for Java 10 is:
```
WARNING: Could not find jawt.dll.  Some features may not work properly.
```
JRE 10 provides the file in the `bin/` directory. JDK 10 does not provide it.

**Comment by dcommander** [comment]
Ugh.  OK, I'll look into it.  Java is in such a state of flux this year that it's hard to keep up.

**Comment by mslinn** [comment]
Oh, joy, 6 month rolling releases of Java henceforth.

**Comment by dcommander** [comment]
Turns out this was a legitimate bug in vncviewer-javaw.bat, and it affected Java 8 as well.

**Comment by mslinn** [comment]
When might a released version have this fix?

**Comment by dcommander** [comment]
Within the next few days.  I'm doing some final testing with Java 11 beta.
