### ISSUE TITLE
Can we run TurboVNC without showing the desktop?

### ISSUE THREAD

**Issue by liuty10** [TurboVNC/turbovnc#139]
I only need a terminal to start games. I do not need the desktop. Is it possible to run remote games without the virtual desktop?

**Comment by al3x609** [comment]
read this from official webpage [Application Isolation](https://turbovnc.org/Documentation/ApplicationIsolation)

**Comment by dcommander** [comment]
You don't even necessarily need that procedure if you're running a game.  As long as the game has a full-screen mode, then you can simply create a script to run the game in VirtualGL:

```
#!/bin/bash
vglrun {VirtualGL_options} {my_lovely_game} {fullscreen_argument}
```
and pass that script to the TurboVNC Server using the `-xstartup` argument.  That avoids the unnecessary overhead of a window manager.  You only need a window manager if the application you're running creates multiple windows.

**Comment by liuty10** [comment]
@dcommander 
I am still not clear. 
The document said TurboVNC with VirtualGL has higher performance. I want this.

When I only use virtualGL, 
at client side: vglconnect user@IP. After that, I get a terminal, and I can start the game by: vglrun ./my_game

When I want higher performance, I use TurboVNC and VirtualGL.
At server side: vncserver -3dwm
at client side:   ./vncviewer IP:5901

You said, 
#!/bin/bash
vglrun {VirtualGL_options} {my_lovely_game} {fullscreen_argument}

@dcommander When I pass that script to the TurboVNC Server using the -xstartup argument. 
Do you mean that I should start TurboVNC and my game at the same time by using ssh from client?

**Comment by dcommander** [comment]
I meant exactly what I said.  Pass `-xstartup {script}` to vncserver, where `{script}` is the script used to start your game with VirtualGL (example given above.)  Do not use `-3dwm` in that case, since (a) `-3dwm` has no effect unless you are using the default xstartup.turbovnc script, and (b) you are already invoking vglrun in the custom xstartup script.

**Comment by liuty10** [comment]
I encounter the following error again:


lty@ubuntu:~/Downloads/my-game$ vncserver -xstartup run_game.sh 
Couldn't start Xtightvnc; trying default font path.
Please set correct fontPath in the vncserver script.
Couldn't start Xtightvnc process.

Unrecognized option: -xstartup
use: X [:<display>] [option]
-a #                   mouse acceleration (pixels)
-ac                    disable access control restrictions
-audit int             set audit trail level
-auth file             select authorization file
bc                     enable bug compatibility
-bs                    disable any backing store support
.............

**Comment by dcommander** [comment]
When I say vncserver, I mean /opt/TurboVNC/bin/vncserver.  /usr/bin/vncserver is not TurboVNC.

**Comment by liuty10** [comment]
Got it. 
/opt/TurboVNC/bin/vncserver -xstartup run_game

I can start the vncserver now, but the vncviewer is black screen again.

**Comment by liuty10** [comment]
Great! The run_game.sh was not found just now.
There is no window manager at client side now. Only the game window. That's good.

I have another question:
If the server side has no lightdm or other manager, can we run game remotely using TurboVNC?

**Comment by liuty10** [comment]
Another Question:
If I start the vncserver this way, how can I support multiple game player?

**Comment by dcommander** [comment]
TurboVNC doesn't require a display manager (LightDM, etc.), but VirtualGL does.  Supporting multiple game players is just a matter of having each player start their own TurboVNC Server session using the same script.  TurboVNC creates independent virtual X servers that are per-user, so everything displayed to a particular TurboVNC session is confined to that session.  There is no limit on the number of TurboVNC sessions, other than CPU and memory resources.  VirtualGL virtualizes the hardware-accelerated OpenGL in such a way that multiple users can share the same GPU.  Similarly, there is no limit on VirtualGL sessions other than GPU and GPU memory resources.

**Comment by liuty10** [comment]
Thank you very much!

But,
1. why VirtualGL need display manager? I am interested in the exact dependencies.

2. What other components required by VirtualGL/TurboVNC?

**Comment by dcommander** [comment]
Refer to the VirtualGL User's Guide.  It needs the display manager because that is the most secure way to provide shared access to the 3D X server, which is needed in order to access the GPU.  Other components required?

```
ldd /opt/TurboVNC/bin/Xvnc
ldd /usr/lib[64]/libvglfaker.so
```

will give you a general idea.  Mostly just X11 and OpenGL libraries, but TurboVNC also needs the OpenSSL libraries if you want to use the built-in encryption feature.  It also goes without saying that you need an SSH server in order to start TurboVNC sessions.
