### ISSUE TITLE
[question] How to send vncpasswd  view-only with the -f option?

### ISSUE THREAD

**Issue by al3x609** [TurboVNC/turbovnc#140]
I try
`echo "testpass" | /opt/TurboVNC/bin/vncpasswd  -f > ~/.secret/passvnc`

but the only - view pass... How to send it ?

**Comment by dcommander** [comment]
I don’t fully understand what you are asking, but have you tried passing `-v` to vncpasswd?

**Comment by al3x609** [comment]
I'm sorry it was a mistake of my interpretation. I had not tried the -v option. Thank you.

In addition to this, could you give me an opinion about the best possible configuration of virtualgl / turbovnc to provide a remote viewing service with novnc?

what happens is that I'm running a blender benchmark, remotely but the results are giving me more than 5 times slower than other tests on the internet with the same hardware.

for now I do not use any configuration to run turbovnc or virtualgl, only the default options.

**Comment by dcommander** [comment]
> In addition to this, could you give me an opinion about the best possible configuration of virtualgl / turbovnc to provide a remote viewing service with novnc?
> 
> what happens is that I'm running a blender benchmark, remotely but the results are giving me more than 5 times slower than other tests on the internet with the same hardware.

What do you mean by "other tests"?

> for now I do not use any configuration to run turbovnc or virtualgl, only the default options.

noVNC unfortunately doesn't provide a way to configure the compression level and quality without modifying this portion of the noVNC source code:

https://github.com/novnc/noVNC/blob/master/core/rfb.js#L1242-L1243

As you can see, the default in noVNC is Compression Level 2 and Quality Level 6.  If connecting to the TurboVNC Server over a low-bandwidth network, better options would be Compression Level 7 (which is the same as Compression Level 2, except that it also enables interframe comparison to prevent duplicate framebuffer updates) and either Quality Level 4 without automatic lossless refresh or Quality Level 2 with automatic lossless refresh (`man -M /opt/TurboVNC/man Xvnc` for information on the ALR feature and how to enable it.)

> and I work with binaries not from source code.
> Is it necessary to install turbo-jpeg separately?

Not if you are using our official binaries.  They link statically with TurboJPEG.
