### ISSUE TITLE
Mac: JRELoadError with JDK 11

### ISSUE THREAD

**Issue by dcommander** [TurboVNC/turbovnc#143]
JDK 11 no longer installs a separate JRE, so the launcher embedded in **TurboVNC Viewer.app** doesn't know where to find the JVM, resulting in a "JRELoadError" dialog.

To work around this problem temporarily, run the following command in a Terminal window:

```
sudo ln -fs /Library/Java/JavaVirtualMachines/jdk-11.jdk /Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin
```

A more robust fix is forthcoming.

**Comment by dcommander** [comment]
https://github.com/TurboVNC/turbovnc/commit/de71c0dbbe43828112d029e8c02c95d9cefb2655 makes the Mac TurboVNC Viewer app launcher honor `JAVA_HOME`, as the Java TurboVNC Viewer launch scripts on other platforms do.  That means you should be able to add the following to **~/.bash_profile** in order to make the Mac TurboVNC Viewer app use JDK 11:

```
export JAVA_HOME=`/usr/libexec/java_home -v 11`
launchctl setenv JAVA_HOME $JAVA_HOME
```

**Comment by thesamesam** [comment]
I'm currently running into this issue on Catalina (10.15.2).

This is in `.zshrc`:
```
# https://github.com/TurboVNC/turbovnc/issues/143
export JAVA_HOME=`/usr/libexec/java_home -v 13`
launchctl setenv JAVA_HOME $JAVA_HOME
```

With:
```
$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/adoptopenjdk-13.0.2.jdk/Contents/Home
```

I installed OpenJDK via `brew cask install adoptopenjdk` which installed OpenJDK 13. I can open up TurboVNC if I open the .app and run the .jar manually, but this means the native parts won't run (I think?)

**Comment by dcommander** [comment]
Does it work with the latest pre-release build?
https://turbovnc.org/DeveloperInfo/PreReleases

**Comment by thesamesam** [comment]
Sorry for omitting TurboVNC version from initial comment, it's 2.2.3.
I've just tried with the pre-release (Jan 16th) and it opens correctly, thank you.
