### ISSUE TITLE
Java Web Start -- FEEDBACK REQUESTED FROM COMMUNITY

### ISSUE THREAD

**Issue by dcommander** [TurboVNC/turbovnc#147]
As most of you know, TurboVNC (since v1.2) has embraced Java Web Start as a way of deploying the (Java/Mac/Un*x) TurboVNC Viewer in a zero-install capacity, and I know that some organizations use this method of deployment with their own internal TurboVNC web portals.  Although there is [some scuttlebutt](https://lists.openstreetmap.org/pipermail/josm-dev/2018-April/008023.html) regarding the open source community picking up support of JWS through the [IceaTea-Web](https://icedtea.classpath.org/wiki/IcedTea-Web) project, Oracle has dropped JWS from Java 11.  Thus, when public updates for Java SE 8 stop ([January, 2019 for commercial users and December, 2020 for personal users](https://www.oracle.com/technetwork/java/javase/eol-135779.html)), the only enterprise-friendly way of using Java Web Start will be through an Oracle support contract.

If your organization is currently using the TurboVNC Viewer with Java Web Start, I would like to hear from you regarding your plans.

## Food for thought

TurboVNC 3.0, which is currently being developed in the "dev" branch of our GitHub repository, includes the following new features that will ease the transition away from Java Web Start, for those desiring to make that transition:

- The "TurboVNC Session Manager", which uses the Java TurboVNC Viewer's embedded SSH client to start, kill, and manage multiple TurboVNC sessions running under a particular user account on a remote TurboVNC host.  By default, the TurboVNC Session Manager automatically enables SSH tunneling and OTP authentication, for a completely seamless and secure user experience.  Once the user authenticates with the SSH server, everything else "just works."  ssh-agent and Pageant support, for automatic SSH authentication using a key chain, are also possible but would require some additional development (preferably funded development.)
- The Java TurboVNC Viewer is now deployed with a custom JRE on Mac and Windows, which eliminates the need to install a standalone JRE.  This custom JRE, which is built using jlink, includes only the components necessary to run the TurboVNC Viewer, so it requires only about 50 MB of disk space.

## Ideas for a next-gen zero-install TurboVNC viewer

1. Deprecation

    Basically this would involve jettisoning the built-in HTTP server in the TurboVNC Server and supporting JWS deployments only from dedicated web servers and only as a legacy feature for Oracle Java 8 or IceaTea-Web users.  Originally the concept of an embedded HTTP server in every VNC session was predicated on the ubiquity of Java in web browsers, but these days, not only isn't Java ubiquitous in web browsers, but it isn't available at all.  My instincts say that the built-in HTTP server doesn't make much sense until/unless we develop some other type of browser-based VNC viewer that doesn't require Java.

2. Hide and watch

    Do nothing, wait and see whether IceaTea-Web becomes enough of a thing that it makes sense to support it along with the existing TurboVNC Viewer zero-install deployment strategy (including the built-in HTTP server.)  If OpenJDK+ITW binaries become available for Linux, Windows, and Mac, then it might become possible to support the existing zero-install deployment strategy, but still, it seems like:

    - The only advantage of this would be the ability to push out new TurboVNC Viewer JARs to a large organization.
    - Most large organizations that would need to do that are going to use a dedicated web server to do so, not the TurboVNC Server's built-in HTTP server.

    In general, since desktop JREs are becoming less of a thing, the price for JWS deployment is installing more software on the client (i.e. a 200 MB JRE instead of the 50 MB TurboVNC Viewer w/ embedded JRE) and performing more steps in order to connect to a TurboVNC session.  The TurboVNC Session Manager, IMHO, is a much more straightforward workflow unless organizations already have a JRE deployed on all of their client machines.

2. Keep the HTTP server but serve up a different viewer with it

    We are looking at the possibility of a WebAssembly (WASM) TurboVNC Viewer in the long term, but WASM [doesn't yet support SIMD instructions](https://github.com/libjpeg-turbo/libjpeg-turbo/issues/250), which are necessary for developing a TurboVNC viewer.  Another possibility is serving up a customized version of noVNC using our built-in HTTP server, although this would require a lot of work (and funding), and the resulting viewer would lack the features and performance of the standalone viewer.  The main advantage of using a viewer like noVNC would be support for mobile devices.

3. Support [Webswing](https://webswing.org/)

    Although I was able to get the TurboVNC Viewer to work with Webswing, with some modifications, in general the technology seems promising but not fully baked yet.  I ran into some deep issues, such as resolving some of the com.turbovnc.rfb classes, that shouldn't have happened.  The interface also doesn't work particularly well for mobile devices.  It would probably be necessary to implement a new "Webswing" mode, similar to the old applet mode, whereby the viewer behaves differently if it detects that it's running in a browser.

    Also, given that Webswing works sort of like a VNC viewer, converting thick client apps into thin client, it seems like duplication of effort to run a VNC viewer inside of it.

4. Support [Getdown](https://github.com/threerings/getdown)

    This would restore the ability to deploy new TurboVNC Viewer JARs to a large organization, but it would take a lot of effort to integrate it into TurboVNC in a seamless manner.

5. Some other idea I haven't thought of

**Comment by dcommander** [comment]
A variant of #3 (which I'll call #3a) seems to be:

- Include instructions on how to integrate the TurboVNC Server with a stock version of noVNC.  That would probably be the most meaningful thing to do for 3.0, since noVNC is undergoing rapid development and may or may not be the preferred solution in the long term.  Conceivably, the vncserver script could simply call the noVNC launcher with the appropriate parameters, so that connecting to http://my_host:580n would automatically launch noVNC pre-configured to connect to the TurboVNC session (bonus points if I can figure out how to pass a one-time password to it.)

There are some limitations with noVNC, such as the inability to adjust the compression level and quality on the fly, etc., but the Java viewer used to be much more limited than the native viewer as well.

**Comment by al3x609** [comment]
> 3a has been implemented in [6f4767e](https://github.com/TurboVNC/turbovnc/commit/6f4767ecf709310970f87744240b9e91cbdd4e33). That commit introduces two new options to vncserver that allow it to configure the noVNC WebSockets proxy as a substitute for the TurboVNC Server's built-in HTTP server. Conceptually this solution works the same as the existing "zero-install"/built-in HTTP server solution-- listening on Port 580x for HTTP/HTTPS connections from a browser and interfacing with RFB Port 590x on the back end. The major functional limitations are: (a) much lower performance than the TurboVNC Viewer, (b) no way to configure the encoding settings, and (c) only supporting VNC Password authentication. [38eb634](https://github.com/TurboVNC/turbovnc/commit/38eb634162834b9b4e8d195cdd711eddd9a49fd3) extends the TurboVNC Session Manager so that it can easily be used to generate new OTPs for a session and copy them to the clipboard, so this facilitates sharing a session using noVNC (or any other viewer that lacks the Tight and VeNCrypt security extensions) and logging into it using an OTP. Although that workflow doesn't make much sense if you already have the TurboVNC Viewer installed, it could be used to share the session with a colleague or to temporarily join the session from a mobile device or a different computer on the same network.
> 
> Given this solution, I have retired the JWS documentation to the Java viewer README file, thus de-emphasizing that mode of operation but leaving it documented and supported as an "advanced topic" for the time being. It may make sense to eliminate the built-in HTTP server as well, but for the moment, I'm OK with merely deprecating it in 3.0 as long as it doesn't interfere with any new features.
> 
> Bonus points will be investigating whether the TurboVNC Server can support WebSockets without a proxy.

If you put OTP over noVNC,  
you lose a feature that makes vnc notorious, persistent sessions; This is because the use of a web session is not only the opportunity of zero installation.
In this way, the user wants to start a vnc web session in X moment, disconnect and then reopen the same session in another place and / or device. With OTP, it requires again to launch the VNC server, which is not viable from the point of view of the end user in a remote service.

**Comment by dcommander** [comment]
Incorrect.  New OTPs can be generated for a session without restarting the server.

**Comment by al3x609** [comment]
I use novnc / websockify - virtualgl / turbovnc to provide a remote VNC service.

I believe that turbovnc 3.0 should support.

-websocktes,
- mini web server.
In other words, integrate the functionality of Websockify.

**Comment by al3x609** [comment]
I found this  too : [web workers](https://github.com/novnc/noVNC/issues/114)

**Comment by dcommander** [comment]
WebSockets support in the TurboVNC Server is mostly done, and I am in the process of testing it before pushing the feature.  After that, I will determine the best course of action for the HTTP server.  If we can get away with not supporting HTTPS (presumably we can, since the only thing being transferred over the HTTP connection will be the noVNC files), then it may be possible to re-purpose the existing HTTP server.

Regarding OTPs, the new TurboVNC Session Manager feature in TurboVNC 3.0 also allows new OTPs for a TurboVNC session to be generated remotely, from the client machine.  That streamlines the process of generating an OTP for the purposes of collaborating with a colleague or logging in to an existing session with your phone.

**Comment by dcommander** [comment]
I ran into problems with the built-in WebSockets proxy (refer to #127), so for the moment, I'm sticking with the approach of using websockify and letting vncserver manage that process along with the Xvnc process.  As such, there isn't a need to re-purpose the built-in HTTP server yet, and thus there isn't a need to jettison the built-in Java Web Start deployment feature yet.  I expect that, eventually, integrating the built-in WebSockets proxy (which is currently relegated to an experimental branch) will necessitate re-purposing the HTTP server so that it can serve up noVNC (and hopefully support HTTPS as well), but unless something changes prior to 3.0 beta, my current plan of action is to deprecate Java Web Start in 3.0 but not remove it.

**Comment by dcommander** [comment]
At the moment, it appears that the built-in WebSockets proxy feature will slip past 3.0.  Since ITW does provide binaries for Windows, I've decided to keep the zero-install JWS feature for now, until there is a good reason to jettison it.  However, note that I don't personally plan to test that feature, so if it breaks in 3.0, someone will have to let me know during the beta-test phase.

**Comment by dcommander** [comment]
Given the security problems inherent in the built-in HTTP server, I've opened up a new issue (#187) for overhauling that feature.  That would involve moving the HTTP server into a separate executable, which would use libmicrohttpd or some other OSS HTTP framework.  I've decided that, unless I can get funding for that feature, the HTTP server will be removed in TurboVNC 3.0. An embedded web server will likely still be needed in order to serve up noVNC, once #127 is completed, but the existing HTTP server code would not be suitable for that task.  It doesn't make sense to keep it if its only purpose is to support Java Web Start.  If the TurboVNC community wants to continue using the embedded HTTP server + JWS feature, then they need to pony up funding for that feature to be implemented in a more secure way.

**Comment by dcommander** [comment]
Java Web Start support, JAR signing support, and the embedded web server have been completely removed in 3.0, in favor of tighter integration with noVNC.  The TurboVNC Server now ships with a simple Python-based web server that responds to the `-x509key` and `-x509cert` arguments, and since the new built-in WebSocket proxy also responds to those arguments, starting an encrypted noVNC session is now as easy as putting your cert and key file under **~/.vnc/x509_cert.pem** and **~/.vnc/x509_private.pem** (refer to https://gist.github.com/dcommander/fc608434735026dd8215 for an example of how to generate these with a self-signed certificate authority) and passing `-novnc {novnc-directory}` to **vncserver**.  The **vncserver** script automatically starts an instance of the simple web server on the VNC HTTP port (5800 + display number), tracks/kills that process along with the Xvnc process, and prints a complete noVNC URL with the `host`, `port`, and `encrypt` parameters set appropriately.  I intend to also modify the Session Manager so that it can obtain complete one-click noVNC URLs for a particular session, with the OTP added via the `password` URL parameter.

In general, I think that this is more in keeping with the original intent of the VNC embedded web server.  It was meant as a zero-install, browser-based, limited-feature, and limited-performance deployment alternative for the VNC viewer, back in the days when the Java plugin was ubiquitous in browsers.  Moving the web server into a separate process improves the security of the solution in two ways:
1. The attack surface of Xvnc is reduced, and
2. All of the security-critical code in the web server is now external (the Python BaseHTTPServer class.)

Organizations that still have Java 8 deployments and commercial licenses for same can still deploy the TurboVNC 3.0 viewer with Java Web Start, but the TurboVNC distribution will no longer provide signed JARs or a JNLP template to facilitate that.  Java Web Start, JAR signing, and the embedded web server will continue to be supported in the 2.2.x branch.  However, once 3.0 is released, that branch will cease receiving much attention unless an organization pays for long-term support on it (https://turbovnc.org/About/ProfessionalServices).  There probably will be a 2.2.5 bug-fix release prior to that time.
