### ISSUE TITLE
Java TurboVNC Viewer looses some key release events

### ISSUE THREAD

**Issue by i-perminov** [TurboVNC/turbovnc#149]
Hi,

If both left and right modifier keys of the same type are pressed and then released, VNC viewer does not pass the second release event to the server. For example, sequence "press left Alt, press right Alt, release right Alt, release left Alt" results in 3 events instead of 4:
KeyPress event, serial 34, synthetic NO, window 0xe00001,
    root 0x2bf, subw 0x0, time 1367970929, (-306,879), root:(495,900),
    state 0x0, keycode 64 (keysym 0xffe9, Alt_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 34, synthetic NO, window 0xe00001,
    root 0x2bf, subw 0x0, time 1367971857, (-306,879), root:(495,900),
    state 0x8, keycode 113 (keysym 0xffea, Alt_R), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 34, synthetic NO, window 0xe00001,
    root 0x2bf, subw 0x0, time 1367972897, (-306,879), root:(495,900),
    state 0x8, keycode 113 (keysym 0xffea, Alt_R), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

I tried different TurboVNC/vnc4 server/viewer combinations and the problem seems to be with TurboVNC viewer.
Environment: TurboVNC 2.2, Ubuntu 18.04, OpenJDK Runtime Environment (IcedTea 2.6.14) (7u181-2.6.14-0ubuntu0.1)

Thanks,
Ilya

**Comment by dcommander** [comment]
I'll look into it.  I thought all of those issues were fixed in 2.2.

**Comment by dcommander** [comment]
Blerg.  Apparently the pressedKeys HashMap needs to be updated to compare the key location as well as the keycode, because under Java, the keycode is the same for LAlt and RAlt (but the location is different.)  So the viewer is mistaking the RAlt release for a LAlt release, and since it thinks LAlt has already been released, it ignores the key event.  I'll hack something up for it tomorrow.

**Comment by dcommander** [comment]
Fix pushed to master, and a pre-release build with the fix ([2.2.x stable](https://turbovnc.org/DeveloperInfo/PreReleases)) will be available shortly.  Please test.

**Comment by i-perminov** [comment]
I can't reproduce the bug using the new vncviewer version.  I'll do more "real life" testing, but the bug seems to be fixed. Thank a lot for fixing it!

**Comment by dcommander** [comment]
Cool.  Let me know if you encounter any other problems.  TurboVNC 2.2.1 is scheduled to be released in December.
