### ISSUE TITLE
Missing call to DamageDrawInternal(pScreen, FALSE) in rfbSpriteRestoreCursor()

### ISSUE THREAD

**Issue by almightykiwi** [TurboVNC/turbovnc#153]
Some sections of code in [unix/Xvnc/programs/Xserver/hw/vnc/sprite.c](https://github.com/TurboVNC/turbovnc/blob/5ad43211cc1671c966ae3a0049586dd825e97a3f/unix/Xvnc/programs/Xserver/hw/vnc/sprite.c) are surrounded by calls to the `DamageDrawInternal` function:

```
DamageDrawInternal(pScreen, TRUE);
// code here
DamageDrawInternal(pScreen, FALSE);
```

Based on all the occurrences of this pattern, and on the implementation of this function, it seems
necessary that both calls are made for the code to be correct, yet there is a code path in the function `rfbSpriteRestoreCursor` where it returns early, *between* those two calls:

https://github.com/TurboVNC/turbovnc/blob/5ad43211cc1671c966ae3a0049586dd825e97a3f/unix/Xvnc/programs/Xserver/hw/vnc/sprite.c#L964-L965

This corrupts the internal state of the "damage" code, and will prevent the proper rendering of windows for applications that rely on it. (In which case, the output of Xvnc will be full of messages like `non internal damage, skipping at 17` if `DAMAGE_DEBUG_ENABLE` is enabled in damage.c).

The following patch fixes this issue, although maybe not in the most elegant way.
```diff
--- i/unix/Xvnc/programs/Xserver/hw/vnc/sprite.c
+++ w/unix/Xvnc/programs/Xserver/hw/vnc/sprite.c
@@ -961,8 +961,10 @@ rfbSpriteRestoreCursor(DeviceIntPtr pDev, ScreenPtr pScreen)
     rfbSpriteComputeSaved(pDev, pScreen);
     pCursor = pCursorInfo->pCursor;
 
-    if (rfbFB.cursorIsDrawn || !pCursor)
+    if (rfbFB.cursorIsDrawn || !pCursor) {
+        DamageDrawInternal(pScreen, FALSE);
         return;
+    }
 
     rfbFB.dontSendFramebufferUpdate = TRUE;
 ```
--

For context, we ran into this issue with an application based on the Qt Quick framework, with a transparent window plus some custom OpenGL rendering. If a VNC client connects while the application is running (without a window manager, I might add), the situation described above happens, and the window's content stops being refreshed. (And any similar application run afterwards will display a black window.) So, quite a corner case, I would say :-)

**Comment by dcommander** [comment]
Fixed in master.  Thanks!
