### ISSUE TITLE
Upgrade Linux TurboVNC Helper to use X Input v2

### ISSUE THREAD

**Issue by dcommander** [TurboVNC/turbovnc#156]
This will hopefully resolve issues with Qt5 applications (refer to #154) when using the default ("hot plug") mode of TurboVNC's Extended Input Device (EID) feature.  Qt5 unfortunately seems to hard-code the drawing tablet valuator names, so it expects pressure to come from a valuator called "Abs Pressure", etc.  (This is, IMHO, a bad design decision on Qt's part, since those valuator names are an implementation detail of the driver, not a defined standard.)  The TurboVNC Helper for Linux currently only supports X Input v1, so it can't read the valuator names from the tablet driver on the client machine.  It thus assigns generic names ("Valuator 0", "Valuator 1", etc.) to the valuators, and this confuses Qt5 on the server end.  Supporting X Input v1 was necessary at the time the EID feature was implemented, because we still had to support RHEL 5, but since RHEL 5 is now EOL, it should be safe to upgrade to X Input v2.  That will allow us to send the actual valuator names from client to server, which will improve the compatibility of the EID feature in general.

**Comment by jave** [comment]
When you get around to this feature, it would be nice if it could be tested with Gimp, Krita, and Inkscape.

**Comment by dcommander** [comment]
@jave The feature is in the 3.0 beta1 release, so please test it.
