### ISSUE TITLE
[error start app with virtualGL/turbovnc] manual start.

### ISSUE THREAD

**Issue by al3x609** [TurboVNC/turbovnc#160]
HI, 
```

DISPLAY=:1 vglrun  +v -d localhost:0.0 paraview
[VGL] Shared memory segment ID for vglconfig: 1441792
[VGL] VirtualGL v2.6.1 64-bit (Build 20190101)
[VGL] Opening connection to 3D X server localhost:0.0
*** stack smashing detected ***: /opt/ParaView/lib/paraview terminated
Segmentation fault (core dumped)
```
sometimes it works fine, but other times it generates this error

**Comment by dcommander** [comment]
I strongly suspect that this is related to VirtualGL and not specific to TurboVNC, but I have no idea what could be causing it. I’m going to need details about your application server— O/S, GPU, driver version, Paraview version, VirtualGL and TurboVNC version, and anything else that may be relevant to help me reproduce the problem.

**Comment by al3x609** [comment]
Im sorry for that , it was my fail, It was an error with ldconfig and libGL.so* thanks
