### ISSUE TITLE
UltraVNC Viewer flickers with TurboVNC 2.2.1 Server

### ISSUE THREAD

**Issue by kisol-pw** [TurboVNC/turbovnc#165]
Hi, 
when I updated from TurboVNC 2.2 to 2.2.1, I got rapid flickering in UltraVNC viewers, other viewers were fine though.
Diff led me to rfbserver.c and the pendingDesktopSize field seemed suspicous.

The change was introduced in 5cb50b8f8732d0d79689e207fd67bc9692c38e69 and enables pendingDesktopSize in rfbFramebufferUpdateRequest (which I guess was intended as a first-time-only action?) and sends the desktop size in rfbSendFramebufferUpdate.

It seems the uvnc viewer doesn't notice that the desktop size hasn't changed and requests a refresh triggering an endless loop, as reverting the commit fixed it.

**Comment by dcommander** [comment]
I'll check it out.

**Comment by dcommander** [comment]
Fixed in master (2.2.2 pre-release.)  I also fixed a crash in the UltraVNC Viewer that occurred when resizing the TurboVNC Server desktop to a smaller size with interframe comparison turned on.
