### ISSUE TITLE
Release of binaries for 2.2.2

### ISSUE THREAD

**Issue by bhaprayan** [TurboVNC/turbovnc#170]
I'm having issues running TurboVNC 2.2.1 (specifically running into):
`javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)`
I noticed in the changelog that this bug has been fixed in 2.2.2. When would the latest binaries be released on SourceForge (latest release is 2.2.1)? I would've built the latest version of TurboVNC  myself, but I'm having issues during compilation with the libjpeg-turbo library.
Thanks!

**Comment by dcommander** [comment]
That's why we provide pre-release binaries, which are automatically built every time I push a commit: https://turbovnc.org/DeveloperInfo/PreReleases

**Comment by dcommander** [comment]
2.2.2 is due in April.

**Comment by bhaprayan** [comment]
Alright, great! Thanks :+1:
