### ISSUE TITLE
Continuous resize events triggered

### ISSUE THREAD

**Issue by felix-wolfheimer** [TurboVNC/turbovnc#174]
I'm using TurboVNC together with apache guacamole which uses libvncclient to connect to TurboVNC's Xvnc (I use vncconnect to establish a reverse connection to be precise). It seems that version 2.2.1 introduced a problem related to resizing events. In my configuration TurboVNC 2.2.1 triggers about 10 (false) resizing events per second in libvncclient which leads to a significant slowdown of the VNC session. This effect was not present in version 2.2.0 with an otherwise identical configuration. In the release notes of 2.2.1 there is a statement related to a change in the handling of display resizing. Maybe this introduced this problem.

**Comment by dcommander** [comment]
Try the 2.2.x pre-release: https://turbovnc.org/DeveloperInfo/PreReleases

**Comment by felix-wolfheimer** [comment]
I tested turbovnc-2.2.2-20190329.x86_64 and it fixes the issue. Thanks a lot for the quick response and the help!
