### ISSUE TITLE
Wacom - Linux-to-linux - Clicks sticking 

### ISSUE THREAD

**Issue by sipickles** [TurboVNC/turbovnc#176]
Hi,

We've been hearing reports from our users of trouble using their Wacom tablets for extended periods of time.

Although wacom functionality works initially, after a period of time a button (eg pen tip or pen lower side) becomes locked in the 'down' position and no amount of clicking releases it. As a result the pen continues to draw/zoom even though the button has been released.

We've been working to provide exact repro steps but it seems rather unpredictable.

We are able to reproduce it on two CentOS 7 machines using TurboVNC 2.2.1 across a LAN. The server is run with the -virtualtablet flag.

Our best repro steps are:
- Initiate session to remote machine
- Run gimp on remote machine (although we can trigger the bug in any app so far tested)
- Ensure Input parameters are set up for the tablet, and that pressure sensitivity is working
- Use airbrush or brush to paint OR use lower side button to drag
- Repeat paint/drag repeatedly
- Eventually the button becomes stuck in the down position as described above, despite being released.

The only way to unlock the button is to:
- restart the vnc session OR
- click the same button on the mouse

I can provide a video of the problem if required.

Many thanks

**Comment by dcommander** [comment]
I'm happy to look into this if your company can pay for my labor.  You are the primary consumers of this feature at the moment, and I'm not in a good position to eat any cost on it.

Is the issue reproducible across all client platforms, or just one specific client platform?

**Comment by dcommander** [comment]
I believe that the latest 2.2.x pre-release build (https://turbovnc.org/DeveloperInfo/PreReleases) should fix this.  Please install it on the client and verify that it fixes the issue on your end.
