### ISSUE TITLE
can't open Xvnc

### ISSUE THREAD

**Issue by ZXZ521** [TurboVNC/turbovnc#181]
the compiled is good on the centos7，but I can't open the Xvnc.

WARNING: The first attempt to start Xvnc failed, possibly because the vncserver
script was not able to figure out an appropriate X11 font path for this system
or because the font path you specified with the -fp argument was not valid.
Attempting to restart Xvnc using the X Font Server (xfs) ...
Could not start Xvnc.

I try to update the pixman,pixman-devel and libXfont，but which can't solve the problem.

seek help.

**Comment by dcommander** [comment]
Check the Xvnc log (which is under **~/.vnc**).  That might reveal why Xvnc is failing to start.  Also, please post the full console output from the `vncserver` script.  You might be leaving out something that you don't think is important but which actually is.

**Comment by ZXZ521** [comment]
Thanks.

**Comment by dcommander** [comment]
Are you still having problems?

**Comment by dcommander** [comment]
Closing due to lack of response from the submitter.
