### ISSUE TITLE
Ubuntu-18.04 RDP (from windows 10) is not working.

### ISSUE THREAD

**Issue by shahin231** [TurboVNC/turbovnc#188]
Hi Team,

I have done the below configuration and tried to connect it from Remote Desktop Connection, but its not connecting.

sudo apt-get update
sudo apt install xrdp
sudo apt install xser ver-xorg-core
sudo apt install xorg xrdp
sudo apt install xorg
sudo nano /etc/polkit-1/localauthority.conf.d/02-allow-colord.conf

polkit.addRule(function(action, subject) {
if ((action.id == “org.freedesktop.color-manager.create-device” ||
action.id == “org.freedesktop.color-manager.create-profile” ||
action.id == “org.freedesktop.color-manager.delete-device” ||
action.id == “org.freedesktop.color-manager.delete-profile” ||
action.id == “org.freedesktop.color-manager.modify-device” ||
action.id == “org.freedesktop.color-manager.modify-profile”) &&
subject.isInGroup(“{group}”)) {
return polkit.Result.YES;
}
});

sudo nano /etc/polkit-1/localauthority/50-local.d/45-allow-colord.pkla

[Allow colord for all users]
Identity=unix-user:*
Action=org.freedesktop.color-manager.create-device;org.freedesktop.color-manager.create-profile;org.freedesktop.color-manager.delete-device;org.freedesktop.color-manager.delete-profile;org.freedesktop.color-manager.modify-device;org.freedesktop.color-manager.modify-profile
ResultAny=no
ResultInactive=no 
ResultActive=yes

sudo ufw allow 3389/tcp
sudo /etc/init.d/xrdp restart
sudo systemctl status xrdp
sudo systemctl enable xrdp
ifconfig	(Get IP address)

Remote desktop client (Windows 10)-> Entered IP -> Connect
Its not connecting at all.

Could you please suggest me if any configuration I missed.

Thanks in Advance

Thanks & Regards
Shahin
Phone No+91 8240790602

**Comment by dcommander** [comment]
xrdp is a completely different open source project.  I only support TurboVNC.

**Comment by dcommander** [comment]
You should also never include personal information, such as phone numbers, in a GitHub post.  These are publicly visible.  I would strongly suggest editing your post to remove that information, then deleting the revision containing that information.
