### ISSUE TITLE
clipboard problem on the remote end

### ISSUE THREAD

**Issue by jave** [TurboVNC/turbovnc#192]
I am having trouble copying text on the remote server.

I tried copying betweenseveral different applications.

- Fedora 30 on both server and client
- current official turbovnc rpm:s
- Gnome window manager
- if I do F8/Clipboard, I can see the string I'm copying, but I cant do anything with it
-  Copy does work from remote to client, but not from client to remote.

I notice there are several similar issues in the bugtracker, but they seemed not relevant for this. I apologize if I missunderstood.

**Comment by jave** [comment]
I tried switching the server WM to xfce4 on a whim, and that didnt help

**Comment by dcommander** [comment]
I can't reproduce the issue.  Any chance that you are using a Wayland session and this goes away when you switch to an Xorg session (on the client side)?

**Comment by dcommander** [comment]
And just to clarify, how are you trying to copy the text from client to server?

**Comment by jave** [comment]
- I am running X11 on the client side

- to reproduce, open for instance gedit on the server inside turbovnc. Select text with the mouse, ctrl-c, and try to paste with ctrl-v. Nothing happens in the gedit window. 

However:
- f8/clipboard shows the copied string
- switch to a window on the client machine, ctrl-v  pastes the string.

**Comment by jave** [comment]
on another whim, I tried jre-12 on the client side for the turbovnc client, but it made no difference.

Also I tried poking around with xsel, but didnt figure anything out.

**Comment by jave** [comment]
another data point:

When I select something in any application on the remote, the selection goes away after a short while. This doesnt happen on the client machine.

Attempt att clarification:

- open gedit on the remote, type some text
- select all,ctrl-a
- the selected text is now highlighted with a blue background
- after about one second, the text is deselected, the blue background goes away

**Comment by jave** [comment]
2.2.3 didnt help

**Comment by jave** [comment]
tried 2.2.80, that didnt help either. On the server side.

**Comment by jave** [comment]
Client log(nothing relevan AFAICS)

/opt/TurboVNC/bin/vncviewer -ExtSSH=1 -Tunnel=1 tanaka:1
libjawt.so path: /usr/lib/jvm/jre-12/lib
CConn: connected to host localhost port 39091
CConnection: Server supports RFB protocol version 3.8
CConnection: Using RFB protocol version 3.8
CConn: Using pixel format depth 24 (32bpp) little-endian rgb888
CConn: Requesting Tight encoding
TurboVNC Helper: Enabling X11 full-screen mode for window 0x04000039
TurboVNC Helper: Grabbed keyboard & pointer for window 0x04000039
CConn: Enabling GII
TurboVNC Helper: Listening for XInput events on :0 (window 0x04000039)
Viewport: Successfully created device 1 (Wacom HID 481C Pen stylus)
Viewport: Successfully created device 2 (Wacom HID 481C Finger touch)
Viewport: Successfully created device 3 (Wacom HID 481C Pen eraser)
CConn: Enabling continuous updates
TurboVNC Helper: Ungrabbed keyboard & pointer
TurboVNC Helper: Shutting down XInput listener on display :0
TurboVNC Helper: Disabling X11 full-screen mode for window 0x0400010a
TurboVNC Helper: Listening for XInput events on :0 (window 0x0400010a)
Viewport: Successfully created device 1 (Wacom HID 481C Pen stylus)
Viewport: Successfully created device 2 (Wacom HID 481C Finger touch)
Viewport: Successfully created device 3 (Wacom HID 481C Pen eraser)

**Comment by jave** [comment]
- I tried with 2.2.3, same thing
- I tried setenforce 0 for a bit, no change
- It happens with any text, plain ascii no funky chars
- I cant see anything in particular in the server log
- I cant really try withouth the tunnel, at least not as I can figure out atm

**Comment by jave** [comment]
Ok, I tried running vncviewer inside a x2go session, which in that case doesnt use ssh at all.
Same thing.

Then I tried copy/paste inside the x2go remote session, and, its the same issue. 

I find this completely weird. 

x2go has its own X stack just as turbovnc.

Do you have a pointer to a document that describes how the different clipboard parts are supposed to work together? Because at this point I'm kind of baffled.

**Comment by jave** [comment]
For some reason something called "clipit" was installed on the server, either by default or as a dependency.

Anyway, I removed this thing, and now I can copy paste!
