### ISSUE TITLE
Get VNC client and server FPS

### ISSUE THREAD

**Issue by liuty10** [TurboVNC/turbovnc#195]
Hi,
When we use VGL Transport, we can get the server FPS and client FPS if VGL_PROFILE is set to be 1.  
If we use X11 transport, is it possible that client FPS is higher than server FPS? I have added some code to calculate the server and client FPS, but I am not sure whether they are correct or not.

For VNC server FPS: frame number increases by one when XShmPutImage is called each time. When frame_num is 60, FPS = 60/totla_time.
For client FPS: when nUpdateRectsLeft decrease from non-zero value to zero, frame number increase by 1. When frame number is 60, client FPS = 60/Total_time.

For the server FPS, the value I get is similar to the value that games display. But for clientFPS, it is strange, because it is higher than the serverFPS. Is there something wrong with my calculation? Is it possible that client FPS is higher than Server FPS in TurboVNC?

**Comment by dcommander** [comment]
The TurboVNC Viewer and Server will print profiling information to the console when `TVNC_PROFILE` is set to `1` in the environment.  The Java/Mac/Un*x TurboVNC Viewer additionally has a profiling dialog that can be activated with Ctrl-Alt-Shift-P (or F8, then P.)

RFB has no concept of "frames."  It only has a concept of "framebuffer updates", which can encompass anything from 1 pixel to the entire screen.  When using VirtualGL, each frame that the X11 Transport draws will usually be transmitted as a single framebuffer update, but that isn't guaranteed.  So it is entirely possible that the number of framebuffer updates/second in TurboVNC exceeds the number of frames/second in VirtualGL.

If you want to measure an accurate frame rate from the client while using TurboVNC, you have to use TCBench (https://cdn.rawgit.com/VirtualGL/virtualgl/2.6.2/doc/index.html#hd0017), which has limitations (practically speaking, it only works with GLXspheres and other applications that continuously update a particular region of the screen.)  You can accurately measure megapixels/second using the built-in TurboVNC profiler, but that value may or may not directly correlate to the number of frames/second that VirtualGL is drawing.

**Comment by liuty10** [comment]
Got it. Thank you very much.
