### ISSUE TITLE
listening to global interface

### ISSUE THREAD

**Issue by maulvi** [TurboVNC/turbovnc#197]
Is there any parameter equivalent to (tigervnc) `-localhost no` in turbovnc for listening to global interface

**Comment by dcommander** [comment]
Yes.  `-localhost` works with TurboVNC as well, but the syntax is different.  In TigerVNC, `-localhost` is a boolean option that defaults to off.  In TurboVNC, `-localhost` has no arguments.  It defaults to off, and passing `-localhost` turns it on (i.e. forces the VNC server to listen only on the local interface.)  In TurboVNC, you can also set the `no-remote-connections` directive in the TurboVNC Security Configuration file (**/etc/turbovncserver-security.conf**) to achieve the same thing on a system-wide basis.
