### ISSUE TITLE
Mac: JRELoadError with Java 13

### ISSUE THREAD

**Issue by scottcamacmartin** [TurboVNC/turbovnc#199]
Installed TurboVNC Viewer from TurboVNC-2.2.3.dmg on a Macbook running OS 10.15

When attempting to start the application, a message pops up saying: JRELoadError.  Tried to troubleshoot by following the advice given in a similar error using Java 11.

  $ which java
  /usr/bin/java
  
  $ java --version
  java 13.0.1 2019-10-15
  Java(TM) SE Runtime Environment (build 13.0.1+9)
  Java HotSpot(TM) 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)
  
  $ /usr/libexec/java_home -v 13
  /Library/Java/JavaVirtualMachines/jdk-13.0.1.jdk/Contents/Home
  
  $ cat .bash_profile
  export JAVA_HOME=`/usr/libexec/java_home -v 13`
  launchctl setenv JAVA_HOME $JAVA_HOME
  
  $ echo $JAVA_HOME
  /Library/Java/JavaVirtualMachines/jdk-13.0.1.jdk/Contents/Home

**Comment by dcommander** [comment]
Fix pushed.  It is still necessary to set `JAVA_HOME`, as with Java 11, but I'm looking into a fix for that as well.

**Comment by nalt** [comment]
Thanks. Could you create a release, such that Homebrew (https://github.com/Homebrew/homebrew-cask/blob/master/Casks/turbovnc-viewer.rb) can install a working version?

**Comment by dcommander** [comment]
There aren't enough fixes in master yet to justify a release.  You can use the pre-release code in the meantime: https://s3.amazonaws.com/turbovnc-pr/master/osx/index.html

**Comment by dcommander** [comment]
I just tried the Homebrew cask, and all you need to do to make it work is follow their recommendation of installing Java 8:

```
brew cask install homebrew/cask-versions/adoptopenjdk8
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
launchctl setenv JAVA_HOME $JAVA_HOME
```
Then the TurboVNC Viewer will use that version of Java, regardless of whether it is launched from the command line or the app.
