### ISSUE TITLE
VNC remote access vulnerabilities

### ISSUE THREAD

**Issue by Neustradamus** [TurboVNC/turbovnc#202]
There are VNC remote access vulnerabilities: https://www.kaspersky.com/blog/vnc-vulnerabilities/31462/

**Comment by dcommander** [comment]
The one vulnerability they found in TurboVNC was fixed in 2.2.3. I have already announced this on Facebook and LinkedIn.

https://www.facebook.com/133376330013118/posts/3106053266078728
