### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [TurboVNC/turbovnc#204]
[Extra null pointer checks are not needed in functions](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") like the following.
- [FileTransferItemInfo::Free](https://github.com/TurboVNC/turbovnc/blob/1fdf1bdbdab5acd24f846425b82a7c1d2ed7e54e/win/vncviewer/FileTransferItemInfo.cpp#L78 "FileTransferItemInfo::Free function")
- [FreeConnInfo](https://github.com/TurboVNC/turbovnc/blob/c08b1aaf680a27e5fa6840dba36994867ac0b66e/unix/Xvnc/lib/xtrans/Xtrans.c#L131 "FreeConnInfo function")
- [XauReadAuth](https://github.com/TurboVNC/turbovnc/blob/c08b1aaf680a27e5fa6840dba36994867ac0b66e/unix/Xvnc/lib/libXau/AuRead.c#L69 "XauReadAuth function")

**Comment by dcommander** [comment]
The first instance you list above is in the deprecated Windows TurboVNC Viewer, which is going away in the next major release.  No point in fixing that.  The other two instances are in the Xorg code, which is included verbatim and is out of my control.  I did fix unnecessary NULL pointer checks before invocations of `free()` in the TurboVNC Server code, which is under my control.  Refer to recent commits.

**Comment by dcommander** [comment]
Again, I would very much appreciate exact instructions regarding how to automatically detect this (and other code style issues you care about), rather than wasting my time by forcing me to field such issues individually.  Unless there is an automatic way to detect such issues, then there is no guarantee that they won't re-emerge.

**Comment by elfring** [comment]
Thanks for [your source code improvement](https://github.com/TurboVNC/turbovnc/commit/a850e0b721ce27ce1ff9acef229ff14d447c96cf "Eliminate unnecessary NULL checks before free()").

-----

>… instructions regarding how to automatically detect this …

Such information is provided by corresponding software documentation of available development tools, isn't it?
