### ISSUE TITLE
Windows Viewer: Stuck Windows Key after Locking Screen

### ISSUE THREAD

**Issue by omad** [TurboVNC/turbovnc#206]
I use the Windows TurboVNC viewer running in full screen mode. When walking away from my keyboard, I use `WinKey + L` to lock the screen. When I return, TurboVNC has the `Windows Key` left in a _Stuck On_ state, which makes most keys and mouse actions not work as expected.

Once I figured out what was happening, it's easy to press and release the `Windows Key` to _unstick_ it. But it's still annoying.

No idea whether this is something that can be intercepted and fixed, or if Windows steals control too quickly when locking the screen.

**Comment by dcommander** [comment]
It should be possible to intercept Win+L in the low-level hook, but first, I need to reproduce the issue, which unfortunately I haven't been able to do yet.  Are you using the native or Java viewer?  Do you have keyboard grabbing enabled in full-screen mode?

**Comment by dcommander** [comment]
Also, is this on Windows 10?

**Comment by omad** [comment]
- I have keyboard grabbing enabled in full screen mode.
- On Windows 10.
- Native viewer.

**Comment by dcommander** [comment]
The issue has been reproduced, and I verified it by running the following program in the TurboVNC session:
```
#include <X11/Xlib.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <X11/extensions/XTest.h>

int main(int argc, char *argv[])
{
  Display *d;
  int i, j;
  int bit_no = 0;
  unsigned char kr;
  KeySym keysym;
  char keys_return[32];
  short fix=0;

  if (argc>1 && strcmp(argv[1],"-fix")==0)
      fix=1;

  // Needed to avoid picking up the <return> key on launch
  sleep(1);

  d = XOpenDisplay(NULL);
  if (d == NULL) {
    fprintf(stderr, "Cannot open display\n");
    exit(1);
  }

  XQueryKeymap(d, keys_return);

  for (i=0; i<32; i++) {
    kr = (unsigned char)keys_return[i];
    if (kr == 0) { bit_no+=8; continue; }
    for (j=0; j<8; j++) {
      if (kr & (1<<j)) {
          keysym = XKeycodeToKeysym(d, bit_no, 0);
          printf("Key stuck: '%s'\n", XKeysymToString(keysym));
          if (fix) {
              printf("Unsticking key...\n");
              XTestFakeKeyEvent(d, bit_no, 0, 0);
          }
      }
      bit_no++;
    }
  }

  XCloseDisplay(d);

  return 0;
}
```
Investigating.

**Comment by dcommander** [comment]
Note that the issue occurs solely in the Windows TurboVNC Viewer when keyboard grabbing is enabled.  Full-screen mode is not necessary to reproduce it.

**Comment by dcommander** [comment]
Fixed and pushed
