### ISSUE TITLE
Keyboard Events has no response without desktop

### ISSUE THREAD

**Issue by liuty10** [TurboVNC/turbovnc#208]
I have tried to start two games (0ad and dota2) using TurboVNC and VirtualGL without desktop. Keyboard events has no response and I suspect that keyboard has no focus.
I start the game using command below:
$ /opt/TurboVNC/bin/vncserver -xstartup {scripts for games}

setups:
OS: Ubuntu 16.04
how to install 0ad version 0.0.20: 
        $sudo apt install 0ad
For dota2, I downloaded from stream.

Do you think this is a bug of games or a bug of TurboVNC? I have tried to solve the problem for 2 days, but I still do not have any idea.

**Comment by dcommander** [comment]
I can’t fix a problem unless I can reproduce it, and you have not provided enough information for me to do that.

**Comment by dcommander** [comment]
Ignore previous comment. I didn’t notice that you mentioned a specific application that was causing the problem. I’ll try to reproduce it.

**Comment by liuty10** [comment]
Thank you very much. 
I use Nvidia 1080Ti. 
For the game 0ad, I always get a black screen if version 0.0.23 or 0.0.24 is used on ubuntu 16.04. So, I am not sure whether it is a bug of games or VNC.

For your reference: https://play0ad.com/download/linux/

**Comment by dcommander** [comment]
Confirmed that 0ad 0.0.23b on Fedora 31 displays a black screen (I tried various SDL environment variable settings-- no effect) and that 0ad 0.0.20 on Ubuntu 16.04 doesn't respond to keyboard input.  0.0.20 works OK with a window manager, however, so I doubt that this is a TurboVNC bug.  If you can diagnose the issue and narrow it down to a particular feature (or missing feature) in TurboVNC, then I can look into it further, but I don't have time to perform that diagnosis myself.

**Comment by liuty10** [comment]
No problem. I will let you know if I narrow down the issue. Thanks!
