### ISSUE TITLE
Disabeling ToolBar does not work when java vncviewer is started in listen mode

### ISSUE THREAD

**Issue by naatje80** [TurboVNC/turbovnc#209]
We are currently unable to disable the toolbar in the java vncviewer when the client is started in listen mode. 
When we directly start the client with: vncviewer -ToolBar=0 server:displaynumber it works perfectly.
However, if we start the client with: vncviewer -ToolBar=0 -listen, reverse connect the server to the client using vncconfig, it still shows the ToolBar. This only seems to be the case for the java client, it works perfectly with the "normal" windows vnc client.

**Comment by dcommander** [comment]
I reproduce the problem, and oddly, it seems to only occur on Windows.  Investigating.

**Comment by naatje80** [comment]
That is indeed strange, because I dit not mention I'm encountering the issue on Linux (Centos 7). I was assuming it was an OS independent issue, so I did not test it (jet) on Windows.

**Comment by dcommander** [comment]
Never mind about the O/S.  It was occurring on my Windows machine only because that machine had stored TurboVNC Viewer defaults.  Stand by.

**Comment by dcommander** [comment]
Should be fixed in master/2.2.x stable pre-release build

**Comment by naatje80** [comment]
The issue is indeed fixed. Thank you once again for your quick support!
