### ISSUE TITLE
Jpeg Image Quality reset during reverse connection

### ISSUE THREAD

**Issue by naatje80** [TurboVNC/turbovnc#214]
For slow connections we start the TurboVNC viewer in listen mode with the following additional options:
`turbovnc2p2p4viewer.exe -singlebuffer -samp 2X -compresslevel 6 -quality 80 -grabkeyboard always -notoolbar -listen `
All options seems to be taken into account. We noticed that the quality option is also used if we check the "Default settings" of the listening turbovnc viewer process. But we noticed the quality is always reset to 95% when we reverse connect the session from the server to the viewer. All other settings don't seem to be affected.

**Comment by dcommander** [comment]
Reproduced and investigating

**Comment by dcommander** [comment]
Fixed and pushed.  The fix is now available in the 2.2.x stable pre-release build (https://turbovnc.org/DeveloperInfo/PreReleases).

**Comment by naatje80** [comment]
The issue is indeed resolved. Thank you again for your quick response and solution.
