### ISSUE TITLE
No window opening after successfull connection established

### ISSUE THREAD

**Issue by GabrielParisLion** [TurboVNC/turbovnc#228]
Hi,
I'm trying to use TurboVNC with a Windows client and a CentOS Linux 7 server following [https://cdn.rawgit.com/TurboVNC/turbovnc/2.2.5/doc/index.html#hd001](url)
I use the SSH with tunnel connexion, which works, but when I launch vncviewer the connection is "Established" but no window appears.
I've tried to launch vncviewer as admin and disabled antivirus just in case.

The commands I use at the client side are :
`ssh -L 1047:127.0.0.1:5901 myname@myhost.mylab.my `
`cvncviewer 127.0.0.1:1047`

Thanks for your help,
Gabriel

**Comment by dcommander** [comment]
Things to try:

1. Instead of establishing the SSH tunnel manually, try instead to use the built-in `-tunnel` parameter, i.e.:

    ```
    cvncviewer -tunnel myname@myhost.mylab.my:1
    ```
    (Note that this requires the SSH implementation from either Cygwin or MSYS2.)

2. Try connecting without SSH, i.e.
    ```
    cvncviewer myname@myhost.mylab.my:1
    ```

3. Make sure that a TurboVNC session is actually running on the host and listening on Display :1.

**Comment by GabrielParisLion** [comment]
Hello, 

Thank you very much for your answer, I'll try to make the first solution work. 

I cannot access the server host without SSH because it is on my laboratory network. The turboVNC server is up and running on display 1, I made sure of that. 

Best regards, 
Gabriel 

De: "DRC" <notifications@github.com> 
À: "TurboVNC/turbovnc" <turbovnc@noreply.github.com> 
Cc: "GabrielParisLion" <clement.brunet@insa-rouen.fr>, "Author" <author@noreply.github.com> 
Envoyé: Mercredi 15 Juillet 2020 01:39:40 
Objet: Re: [TurboVNC/turbovnc] No window opening after successfull connection established (#228) 





Things to try: 

    1. 

Instead of establishing the SSH tunnel manually, try instead to use the built-in -tunnel parameter, i.e.: 
cvncviewer -tunnel myname@myhost.mylab.my:1 


(Note that this requires the SSH implementation from either Cygwin or MSYS2.) 
    2. 

Try connecting without SSH, i.e. 
cvncviewer myname@myhost.mylab.my:1 

    3. 

Make sure that a TurboVNC session is actually running on the host and listening on Display :1.

**Comment by dcommander** [comment]
Any luck?

**Comment by GabrielParisLion** [comment]
Not at all. Tried both but no results. I'm gonna go for a Virtual Machine on Linux, apparently it is easier. Thanks for the support though ! 


De: "DRC" <notifications@github.com> 
À: "TurboVNC/turbovnc" <turbovnc@noreply.github.com> 
Cc: "GabrielParisLion" <clement.brunet@insa-rouen.fr>, "Author" <author@noreply.github.com> 
Envoyé: Mercredi 22 Juillet 2020 17:33:52 
Objet: Re: [TurboVNC/turbovnc] No window opening after successfull connection established (#228) 





Any luck?

**Comment by dcommander** [comment]
You could also try our Java viewer, which has a built-in SSH client, in case your SSH client is the issue.

**Comment by dcommander** [comment]
The only other thing I'd suggest is to look at the server log and make sure you're actually getting a successful connection to the TurboVNC Server.  Perhaps the SSH tunnel is succeeding but the connection to the server is not for some reason.
