### ISSUE TITLE
[Question] TurboVNC client lossless refresh flashes before going back to default quality

### ISSUE THREAD

**Issue by Ellynas** [TurboVNC/turbovnc#229]
Hello, I'm having some trouble with a feature of TurboVnc, maybe you could help me ?

The company I work with uses docker containers with TurboVNC server and virtualGL to stream its applications. 
The clients connect to them using noVNC in a browser.

I was trying to enable Automatic Lossless Refresh, but couldn't make it work at all. I then switched to turboVNC **client** (ubuntu) on my machine to see if it was some kind incompatibility with noVNC, but couldn't make it work either. 

The curious part is that even a manual lossless refresh (either with the button, F8 menu or `Ctrl-Alt-Shif-L` shortcut) behaves strangely : I get the lossless update, but it stays on screen for less than a fraction of a second before returning to the default quality. 

Any idea on what might cause this ? I must admit that I'm fairly new to those technologies and I would greatly appreciate a nudge in the right direction.

**Comment by Ellynas** [comment]
I found a clue, and possibly the root of my problem : our server constantly sends frame updates for some reason. I'll have to dig in deep to figure out _why_, but after that I have hope that I will be able to enable ALR.

**Comment by dcommander** [comment]
That was my suspicion.  Have you tried enabling interframe comparison?  You can do that by passing `-interframe` to `/opt/TurboVNC/bin/vncserver` or specifying `$serverArgs = "-interframe";` in either **~/.vnc/turbovncserver.conf** (per-user) or **/etc/turbovncserver.conf** (system-wide) or simply enabling interframe comparison in the TurboVNC Viewer.  Interframe comparison won't prevent the server from generating redundant updates, but it will at least prevent those redundant updates from being encoded and sent to connected viewers.  If you are seeing redundant updates only with a specific OpenGL application, then it may be that the OpenGL application is rendering to the front buffer and the `VGL_GLFLUSHTRIGGER` setting needs to be tweaked to eliminate redundant frame triggers.

**Comment by Ellynas** [comment]
Following your advice, I've enabled interframe comparison and it did help in some way : when I make a manual lossless refresh now, it stays visible except for some rectangles of the screen which immediately go back to the default lossy quality. (tested with TurboVNC client). In Chrome using noVNC I could confirm that the server still sends me frame updates for those rectangles, which are usually located around specific parts our applications (the main 3D model for example) 

I feel that most if not all our applications (they're built around the same core) will still send those redundant updates even with interframe enabled. I will now create an internal issue for our applicative team to take over, quoting your answer.

Feel free to close this issue as I don't think this has much more to do with TurboVNC.

Thank you for your help and quick answer, and thank you for providing this tool.

**Comment by dcommander** [comment]
OK, please let me know if further investigations reveal this to be an issue with TurboVNC, but I have not seen such problems with other applications.

```
vglrun /opt/VirtualGL/bin/glxspheres64 -i
```
is a quick & dirty test to verify whether ALR is working properly.  If that works properly, then the issue is not with TurboVNC.

**Comment by Ellynas** [comment]
For anyone that want to test `vglrun /opt/VirtualGL/bin/glxspheres64 -i` and get `ERROR in line 614: Could not open display`, the steps are : 

``` bash
/opt/TurboVNC/bin/vncserver -alr 2.0 :1
export DISPLAY=:1
vglrun /opt/VirtualGL/bin/glxspheres64 -i
```
Hope it helps.

**Comment by dcommander** [comment]
That is standard behavior for all X servers.  `DISPLAY` is only set automatically if you launch a program using the window manager running on the X server.  Otherwise, if you want to run a program outside of the X server and have it talk to the X server, you have to set `DISPLAY` manually.  Best practices are to set `DISPLAY` on a command-by-command basis, e.g.:

```
DISPLAY=:1 vglrun /opt/VirtualGL/bin/glxspheres64 -i
```
since it's possible to have multiple X proxy instances running under the same user account.  Also, best practices are to not pass a display number to `/opt/TurboVNC/bin/vncserver`.  Let TurboVNC choose a display number for you.  Otherwise, if :1 is already occupied, the TurboVNC Server would fail to start.
