### ISSUE TITLE
RHel7 is s performance is lower than RHel6

### ISSUE THREAD

**Issue by wang332127858** [TurboVNC/turbovnc#230]
vnc version：turbovnc-2.2.5
desktop OS：Linux root 2.6.32-431.el6.x86_64，Linux root 3.10.0-1062.12.1.el7.x86_64
desktop display:xfce4 or gnome

More detailed steps
1.Connect to the rhel6 server desktop using the Viewer
2.You can run a glxgears on terminal or nothing to do
3.Check the traffic of Viewer in Explorer（task manageer）
4.Connect to the rhel7 and Repeat the above steps
5.Compare the traffic of two Viewer,RHel7 is significantly higher than RHel6，I suspect that the picture captured by RHel7 is bigger

**Comment by dcommander** [comment]
Are you serious?  I said *in the future*, file issues such as these under this bug tracker.  I did not say *re-post your existing issue*.  I already provided you with a workaround.  Please test it.
