### ISSUE TITLE
Cannot connect to vncserver

### ISSUE THREAD

**Issue by duanwujie** [TurboVNC/turbovnc#235]
Remote server run with 

`/opt/TurboVNC/bin/vncserver -geometry 3840x2160`

Now in the client connect with 

`/opt/TurboVNC/bin/vncviewer 172.30.24.123:1 -DesktopSize=Server`

Result:

Could not connect: connection refused

**Comment by dcommander** [comment]
Does the host machine have a firewall?  If so, then you need to open TCP port 5901 in the firewall or use SSH (add `-tunnel -securitytypes VNC,Plain,UnixLogin` to the vncviewer command line to tunnel the VNC connection through SSH.)

**Comment by duanwujie** [comment]
Thank you I will try it.


发自我的iPhone

**Comment by duanwujie** [comment]
Thank you, it's okay now. Our machine has 2 GPUs, Intel and AMD Firepro S7150. By default, intel is used. How to specify amd in vncserver?

**Comment by dcommander** [comment]
TurboVNC doesn't directly use the GPU.  It relies on VirtualGL to do that.  Generally, when there are multiple GPUs in the same system, the easiest way to use them with VirtualGL is to configure the X server such that each GPU occupies a separate screen.  Then you could set `VGL_DISPLAY=:0.n`, where `n` is the screen of the GPU you wish to use.
