### ISSUE TITLE
JRE Load Error

### ISSUE THREAD

**Issue by stsve** [TurboVNC/turbovnc#241]
Hello,

Just downloaded v2.2.5 for macOS and the app will not open
Error message: JRELoadError

I am running on a macOS Catalina 10.15.3

Should I try older versions?

**Comment by dcommander** [comment]
Which version of Java?

**Comment by stsve** [comment]
In deed... Java was the issue. 
My bad just updated and everything works fine. 

Sorry about that!

**Comment by dcommander** [comment]
Which version was causing the problem? I thought our viewer handled all of the current releases.

**Comment by stsve** [comment]
I made a mistake... I forgot I had temporarily uninstalled Java I realized it when I decided to upgrade my Java. Everything works fine I even tried later versions and they were also working. Sorry for the false alarm.
