### ISSUE TITLE
TurboVNC Viewer (Listen Mode).app needs to be updated message on macOS.

### ISSUE THREAD

**Issue by pkania** [TurboVNC/turbovnc#242]
TurboVNC version 2.2.5 (20200507)
macOS version 10.15.7

Some, but not all developers on these versions are seeing this message which says "The developer of this app needs to update it to work with this version of macOS. ..."

**Comment by pkania** [comment]
Uninstall and re-install did not fix the problem.

$ codesign -vv /Applications/TurboVNC/*.app
/Applications/TurboVNC/TurboVNC Viewer (Listen Mode).app: valid on disk
/Applications/TurboVNC/TurboVNC Viewer (Listen Mode).app: satisfies its Designated Requirement
/Applications/TurboVNC/TurboVNC Viewer.app: valid on disk
/Applications/TurboVNC/TurboVNC Viewer.app: satisfies its Designated Requirement
/Applications/TurboVNC/Uninstall TurboVNC.app: valid on disk
/Applications/TurboVNC/Uninstall TurboVNC.app: satisfies its Designated Requirement

**Comment by pkania** [comment]
We were able to start it from command line `open -a /Applications/TurboVNC/TurboVNC\ Viewer.app` on the problem machine.

**Comment by dcommander** [comment]
Already fixed in 882bc05afc439649677c88e9368bca08bfb6aa15.  The 2.2.x stable pre-release build contains the fix: https://turbovnc.org/DeveloperInfo/PreReleases
