### ISSUE TITLE
How can you perform a factory reset? 

### ISSUE THREAD

**Issue by emangini-onshape** [TurboVNC/turbovnc#244]
I'm running TurboVNC 2.2.5 on OS X. 

I'm trying to reset the application to factory defaults, but despite wiping my machine of all files and links to turbovnc, when I reinstall, it remembers the previous application state. 

Please advise.

**Comment by dcommander** [comment]
You mean the options?  Open the TurboVNC Viewer Options dialog, then click the "Global" tab, then click "Clear the list of saved connections", then click "Cancel" (don't click "OK") to exit the dialog, then exit and restart the TurboVNC Viewer.  And yes, I realize this is non-intuitive.  It will be addressed in the next major release.

**Comment by emangini-onshape** [comment]
I do mean the options. However, this isn’t what I’m asking.

I’ve entirely removed the application and re-installed it,but it recalls previous state. Where is this information being persisted?

**Comment by dcommander** [comment]
You didn't actually ask anything in the original post.  You stated:

"I'm trying to reset the application to factory defaults, but despite wiping my machine of all files and links to turbovnc, when I reinstall, it remembers the previous application state. Please advise."

So I advised.  But to answer the question you are now asking, the preferences are stored with other Java application preferences, which on macOS are in **~/Library/Preferences/com.apple.java.util.prefs.plist**.  Look for a key called "TurboVNC".  The procedure I described above simply clears out that key.
