### ISSUE TITLE
Could not create4 SSH tunnel: invalid privatekey: <chars>

### ISSUE THREAD

**Issue by emangini-onshape** [TurboVNC/turbovnc#245]
I'm trying to use TurboVNC (2.2.5) w/ SSH on OS X Catalina 10.15.7
The only deviation from the default settings is that we are enabling "Use VNC server as a gateway" in the Security settings.

We have nodes in AWS that we need to be able to VNC into from our developer laptops. 

SSH works fine on its own. I'm able to connect, copy via scp etc. 
The keys are created with this command -> ssh-keygen -t rsa -b 2048 -m PEM -C.
(I've also tried 4096 as a size)
I've confirmed that the private key contains 
-----BEGIN RSA PRIVATE KEY-----

They key has been added to the ssh-agent. 

When I click 'connect', I immediately get the error message above. 

It doesn't matter what I put in the VNC server: in the 'New TurboVNC Connection' dialog, because it's never attempting to make a connection. I never see failures on the remote side of the connection, and I can actually disable my network and still see the same behavior (or just put a bogus string in the VNC Server: field)

It clearly doesn't like my key (all keys need love), but it's in the same format w/ the same size as other working systems, so I'm at a bit of a loss. 

Assistance would be greatly appreciated.

**Comment by dcommander** [comment]
Attempting to reproduce.  Stand by.

**Comment by dcommander** [comment]
Is there anything in **~/.ssh/config**?

**Comment by emangini-onshape** [comment]
Host bf_ed
   HostName  <ip address>
   User builder
   IdentityFile ~/.ssh/buildkey

**Comment by dcommander** [comment]
Is the config entry with **~/.ssh/buildkey** supposed to be the entry for the AWS host?  If so, are you using the config hostname 'bf_ed' when attempting to connect to the host with the TurboVNC Viewer?

**Comment by emangini-onshape** [comment]
Yes, but the ip address is the HostName. The “Host” is just the alias.

So when I ssh@bf_ed, I get to the host fine. Like I mentioned, it works outside of turbovnc perfectly.

**Comment by emangini-onshape** [comment]
Also,
I don’t think I’m getting that far to be honest.

No matter what I put in the VNC Server: dialog.. It fails to read my key. I ran tcpdump, and it’s not even trying to connect.

From: "Mangini, Ed" <emangini@ptc.com>
Date: Thursday, October 22, 2020 at 2:07 PM
To: TurboVNC/turbovnc <reply@reply.github.com>, TurboVNC/turbovnc <turbovnc@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: Re: [TurboVNC/turbovnc] Could not create4 SSH tunnel: invalid privatekey: <chars> (#245)

Yes, but the ip address is the HostName. The “Host” is just the alias.

So when I ssh@bf_ed, I get to the host fine. Like I mentioned, it works outside of turbovnc perfectly.

**Comment by emangini-onshape** [comment]
Bingo

There is a separate id_rsa file, which is probably part of the issue. That id_rsa file is using the newer openssh format (not PEM). However, that’s for a different purpose and it needs to remain with the newer openssh format. It won’t support PEM.

I’m able to connect if I specify the correct file via the cli, however Phil assures me he is doing the same thing as I am and he doesn’t have to do this via the CLI.

Despite being able to connect, there’s no video.

**Comment by dcommander** [comment]
It shouldn't be necessary to use the command line. But again, it is necessary to enter **bf_ed** as the hostname in the TurboVNC Viewer, or else it won't use the private key specified in the OpenSSH config file's "IdentityFile" field.

As far as the blank screen, that's odd.  Double check that **/etc/turbovncserver.conf** contains 
```
$wm = "mate-session";
```
It should, according to the instructions I sent Phil.

**Comment by dcommander** [comment]
Also, I will modify the viewer so that the error message from an invalid private key shows which key it's trying to read.

**Comment by emangini-onshape** [comment]
So that’s the weird part.

I’m using bf_ed:1 in the viewer, but I still get the invalid key.
Via CLI – no problem, but I get the black screen.

Is there a way to provide the “via” parameter on the CLI? I think that’s why I’m getting the black screen. I need to be able to provide it as a gateway.

**Comment by dcommander** [comment]
If you're getting a TurboVNC Viewer window with blank contents, then that means that the SSH and RFB connections were successful, so anything related to a gateway isn't the problem.  But perhaps that's not what you meant by "no video."

The `-via` option shouldn't be needed with AWS.  That would only be needed if the TurboVNC Server is behind an SSH gateway and is running on a different machine than the SSH gateway machine.  Otherwise, `-tunnel`/ "Use VNC server as gateway" is what you need.

**Comment by emangini-onshape** [comment]
That’s a good idea.

lsof shows me that you’re hitting id_rsa regardless of what key I specify in .ssh/config. I confirmed it.

I moved my existing id_rsa to another name and moved the non rsa to id_rsa and it works in the viewer as well as the CLI.

However, I have a black screen in either case.

builder@ip-10-86-13-73:~$ grep mate .vnc/turbovncserver.conf
##                  "mate-session" or "2d")
$wm = "mate-session"
builder@ip-10-86-13-73:~$

**Comment by emangini-onshape** [comment]
Roger that

It looks like the UI is using id_rsa no matter what is placed in the “server” field. I had a newer id_rsa (using OPENSSH format) for a red hat service I have that “really really needs it to be named id_rsa. I can move it for now.

I’m bouncing the Vnc server to see if that’s what is causing the black screen. It’s just black. Trying CTRL-ALT-DEL and the other buttons have no effect. I would expect to see some visual “effect” by selecting a refresh.

**Comment by dcommander** [comment]
> That’s a good idea. lsof shows me that you’re hitting id_rsa regardless of what key I specify in .ssh/config. I confirmed it. I moved my existing id_rsa to another name and moved the non rsa to id_rsa and it works in the viewer as well as the CLI.

I think I see the issue.  Stand by.

> However, I have a black screen in either case. builder@ip-10-86-13-73:~$ grep mate .vnc/turbovncserver.conf ## "mate-session" or "2d") $wm = "mate-session"

Oops.  There should be a semicolon after that line, and I think I may have given instructions to Phil that didn't include said semicolon.

**Comment by emangini-onshape** [comment]
Rock on!

It actually works after I bounced the server, so I think we’re in good shape. Now if we can just make secure connections to AWS  viable for RT synchronous traffic.
😊

**Comment by dcommander** [comment]
The latest 2.2.x pre-release build should have a fix for this issue by the time you read this.
https://turbovnc.org/DeveloperInfo/PreReleases
It was a legitimate bug in the TurboVNC Viewer whereby **~/.ssh/id_dsa** and **~/.ssh/id_rsa** were allowed to take precedence even if `IdentityFile` was specified in the OpenSSH config file.  That has been fixed, and the viewer also now specified which private key file it was trying to use if an "invalid privatekey" error occurs.
