### ISSUE TITLE
`const char *` type mismatches on FreeBSD

### ISSUE THREAD

**Issue by Parakleta** [TurboVNC/turbovnc#250]
There are a couple of type mismatches on arguments and returns between the installed header files and the stubs provided for libraries within TurboVNC, specifically `BufFileWrite`, `NameForAtom`, and `FontEncDirectory`.  These cause the build to fail.

I just manually changed your files to match the system ones, but I'm not sure if there is a better way, or something you can do upstream so it doesn't need to be patched for FreeBSD.

Thanks.

**Comment by Parakleta** [comment]
I just stumbled across the `-DTVNC_SYSTEMX11=1` option which has resolved this for me.  I see now that if I knew better how to use CMAKE this solution would have been obvious as it is documented there.

**Comment by dcommander** [comment]
It's

**Comment by dcommander** [comment]
It's still a bug, though, because the code should build without `TVNC_SYSTEMX11`.  Which compiler and flags did you use when the error occurred?

**Comment by Parakleta** [comment]
Everything is the default settings except that I disable the viewer build (I only want the server) and provide the link arguments to turbojpeg.  I believe the compiler will be a recent version of clang.

The issue is that the system headers for X11 are picked up ahead of yours and it’s trying to compile your X11 source against the system X11 headers, and they’re different versions and some of the function signatures are different.

I can try and get more information tomorrow if you need it.

**Comment by dcommander** [comment]
Any information is appreciated. I am using Clang, but my build doesn’t pick up the system X11 headers if `TVNC_SYSTEMX11=0`.

**Comment by dcommander** [comment]
I still can't reproduce.  I am using `/usr/bin/clang`, which is Clang v8.0.1, and doing:
```
cd turbovnc
mkdir freebsd12
cd freebsd12
CC=clang CFLAGS='-Wall -Werror' cmake -DTVNC_BUILDJAVA=0 -DTVNC_BUILDNATIVE=0 ..
make
```

**Comment by Parakleta** [comment]
I suspect it might be the fact that I am using the system install of libjpeg-turbo.  This adds `TJPEG_INCLUDE_DIR:PATH=/usr/local/include` to the CMakeCache.txt file.  I also have the following variables pointing to `/usr/local/include` if any of those are relevant:

```sh
Fontconfig_INCLUDE_DIR:PATH=/usr/local/include
ICONV_INCLUDE_DIR:PATH=/usr/local/include
TJPEG_INCLUDE_DIR:PATH=/usr/local/include
X11_ICE_INCLUDE_PATH:PATH=/usr/local/include
X11_SM_INCLUDE_PATH:PATH=/usr/local/include
X11_X11_INCLUDE_PATH:PATH=/usr/local/include
X11_X11_xcb_INCLUDE_PATH:PATH=/usr/local/include
X11_XRes_INCLUDE_PATH:PATH=/usr/local/include
X11_XShm_INCLUDE_PATH:PATH=/usr/local/include
X11_XSync_INCLUDE_PATH:PATH=/usr/local/include
X11_Xaccessrules_INCLUDE_PATH:PATH=/usr/local/include
X11_Xaccessstr_INCLUDE_PATH:PATH=/usr/local/include
X11_Xau_INCLUDE_PATH:PATH=/usr/local/include
X11_Xcomposite_INCLUDE_PATH:PATH=/usr/local/include
X11_Xcursor_INCLUDE_PATH:PATH=/usr/local/include
X11_Xdamage_INCLUDE_PATH:PATH=/usr/local/include
X11_Xdmcp_INCLUDE_PATH:PATH=/usr/local/include
X11_Xext_INCLUDE_PATH:PATH=/usr/local/include
X11_Xfixes_INCLUDE_PATH:PATH=/usr/local/include
X11_Xft_INCLUDE_PATH:PATH=/usr/local/include
X11_Xi_INCLUDE_PATH:PATH=/usr/local/include
X11_Xinerama_INCLUDE_PATH:PATH=/usr/local/include
X11_Xkb_INCLUDE_PATH:PATH=/usr/local/include
X11_Xkblib_INCLUDE_PATH:PATH=/usr/local/include
X11_Xlib_INCLUDE_PATH:PATH=/usr/local/include
X11_Xmu_INCLUDE_PATH:PATH=/usr/local/include
X11_Xpm_INCLUDE_PATH:PATH=/usr/local/include
X11_Xrandr_INCLUDE_PATH:PATH=/usr/local/include
X11_Xrender_INCLUDE_PATH:PATH=/usr/local/include
X11_Xshape_INCLUDE_PATH:PATH=/usr/local/include
X11_Xss_INCLUDE_PATH:PATH=/usr/local/include
X11_Xt_INCLUDE_PATH:PATH=/usr/local/include
X11_Xtst_INCLUDE_PATH:PATH=/usr/local/include
X11_Xutil_INCLUDE_PATH:PATH=/usr/local/include
X11_Xv_INCLUDE_PATH:PATH=/usr/local/include
X11_Xxf86vm_INCLUDE_PATH:PATH=/usr/local/include
X11_dpms_INCLUDE_PATH:PATH=/usr/local/include
X11_xcb_INCLUDE_PATH:PATH=/usr/local/include
X11_xcb_icccm_INCLUDE_PATH:PATH=/usr/local/include
X11_xkbcommon_INCLUDE_PATH:PATH=/usr/local/include
X11_xkbcommon_X11_INCLUDE_PATH:PATH=/usr/local/include
X11_xkbfile_INCLUDE_PATH:PATH=/usr/local/include
FIND_PACKAGE_MESSAGE_DETAILS_X11:INTERNAL=[/usr/local/include][/usr/local/lib/libX11.so][c ][v()]
```

**Comment by Parakleta** [comment]
Sorry, this most recent build is against the dev version, in case these don't match up.  The problem is the same in both cases, but I wanted to experiment with the session management stuff.

**Comment by Parakleta** [comment]
Hi, I'm not in a position to play with this until early November but I'll check it out then.  The only note I have that clearly differs from what you have there is that I had to set `-DTJPEG_LIBRARY="-L/usr/local/lib -lturbojpeg"`, I'm not sure if the extra still matters.

**Comment by dcommander** [comment]
There may be something about my environment that eliminates the need to specify `-L/usr/local/lib`. Mainly I need someone to evaluate `TVNC_STATIC_XORG_PATHS` and the associated `XKB_*` and `XORG_*` variables.
