### ISSUE TITLE
Support sending Alt-Tab and other system keys when not full-screen

### ISSUE THREAD

**Issue by hackonteur** [TurboVNC/turbovnc#26]

**Comment by dcommander** [comment]
It already does.  The default is to grab the keyboard (thus enabling Alt-Tab and other system key combinations to be sent to the server) only in full-screen mode, but you can change it by passing `/grabkeyboard always` or `/grabkeyboard manual` to the Windows viewer (or `grabkeyboard=always` or `grabkeyboard=manual` to the Java viewer), or you can manually toggle grabbing at any time by pressing Ctrl-Alt-Shift-G.

**Comment by dcommander** [comment]
In the Windows native viewer, you can also toggle grabbing in the system menu (the menu that appears when you click on the upper left of the window), and in the Java viewer, you can also toggle grabbing in the F8 menu.

**Comment by dcommander** [comment]
I should note that keyboard grabbing in the Java viewer on Windows is a TurboVNC 2.1 feature, so if you're using that viewer, you'll have to use the pre-release build.  However, grabbing has been in the Windows native viewer and the Linux viewer since TurboVNC 2.0.

**Comment by hackonteur** [comment]
Then maybe this should be a documentation bug?
I don't see any reference to this in the documentation that came with 2.0.1.

I do know some people that will be very happy about this.

**Comment by dcommander** [comment]
The User's Guide is more of a general guide for using the software.  To get documentation on all of the available options, you have to pass `-?` to the viewer.  However, I do think that the grab option needs to be added to the GUI so that it is more easily discoverable.

**Comment by dcommander** [comment]
9d6a396b5ba8f2f3e8e2bf13eecbb47fea8ffbcf (master-- 2.1 evolving) and d18877705b3cdb7d57fb9817f12aa77ca76b596e (2.0.x) add the grab options to the GUI.  This will be in the upcoming 2.1 beta and 2.0.2 releases.
