### ISSUE TITLE
Misleading config example for securityTypes

### ISSUE THREAD

**Issue by paulmelis** [TurboVNC/turbovnc#262]
The basic setting for `$securityTypes` in `turbovncserver.conf` shows a list of types separated by ", ", i.e. including spaces. 

https://github.com/TurboVNC/turbovnc/blob/3b02943d2ef956887a018bb3f8b3a1986aaac74e/unix/turbovncserver.conf.in#L45-L53

However, uncommenting the line and editing it to e.g. remove a type will not work as spaces are not accepted in that line, as `vncserver` passes it directly (including spaces) to `Xvnc`. Which then fails to start, e.g.

```
melis@juggle 09:40:~/software/turbovnc-2.2.5/bin$ grep securityTypes ../etc/turbovncserver.conf
##  $securityTypes -- comma-separated list of security types to enable
# $securityTypes = "TLSVnc, TLSOtp, TLSPlain, X509Vnc, X509Otp, X509Plain, VNC, OTP, UnixLogin, Plain";
$securityTypes = "TLSPlain, UnixLogin";


melis@juggle 09:39:~/software/turbovnc-2.2.5/bin$ ./vncserver  

WARNING: The first attempt to start Xvnc failed, possibly because the vncserver
script was not able to figure out an appropriate X11 font path for this system
or because the font path you specified with the -fp argument was not valid.
Attempting to restart Xvnc using the X Font Server (xfs) ...
Could not start Xvnc.

Unrecognized option: UnixLogin
use: X [:<display>] [option]
-a #                   default pointer acceleration (factor)
-ac                    disable access control restrictions
-audit int             set audit trail level
-auth file             select authorization file
```

The description of `$securityTypes` at the top of `turbovncserver.conf` does mention that it should contain a `comma-separated list of security types`, but it would be good to fix the example line and/or add a clear message with it that spaces should not be used in the value.

**Comment by dcommander** [comment]
vncserver should now accept spaces in `$securityTypes`.
