### ISSUE TITLE
Uninstall does not work on macOS 11.1

### ISSUE THREAD

**Issue by r10r** [TurboVNC/turbovnc#266]
I tried to uninstall TurboVNC but it does not work. The uninstall symbol is greyed out.

```
Rubens-MBP:doc ruben$ open /Applications/TurboVNC/Uninstall\ TurboVNC.app/
The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10386 "(null)" UserInfo={_LSLine=3665, _LSFunction=_LSOpenStuffCallLocal}
```
<img width="372" alt="Screenshot 2021-02-02 at 10 12 28" src="https://user-images.githubusercontent.com/309304/106577867-2bf8c200-653f-11eb-8d73-fc36aa40cf33.png">

<img width="572" alt="Screenshot 2021-02-02 at 10 09 25" src="https://user-images.githubusercontent.com/309304/106577700-f8b63300-653e-11eb-8bce-de5a0b25e385.png">

**Comment by dcommander** [comment]
Try the latest 2.2.x stable pre-release build.  882bc05afc439649677c88e9368bca08bfb6aa15
 should have already fixed this, but it hasn't been released yet (I'm hoping to release 2.6.6 this week.)

**Comment by dcommander** [comment]
Closing as presumed fixed.  Let me know ASAP if the pre-release build does not work.

**Comment by r10r** [comment]
Thanks for your fast response. Where do I find the `*.dmg` for the `latest 2.2.x stable pre-release` ?

**Comment by dcommander** [comment]
https://turbovnc.org/DeveloperInfo/PreReleases

**Comment by r10r** [comment]
This Pre-release works fine on macOS (upgraded to 11.2 since issue was reported). Thanks!

```
TurboVNC-2.2.6.dmg | 4125442 | Jan 27 | 652ac7aa4b9eed8a0cb5113afda9b044
```
