### ISSUE TITLE
support: Optimal display settings for text output on high resolution (4k) display

### ISSUE THREAD

**Issue by r10r** [TurboVNC/turbovnc#267]
Hi,

i've a 4k monitor attached to my macbook. 
Using TurboVNC I noticed that the terminal output is a (tiny) bit blurry and not as sharp as with another VNC viewer  (RealVNC Viewer 6.21.118 x64).  I did not change the default display settings. 
Yes I'm spoiled with sharp graphics and just curious if there are any option to make the output sharper?  
(I did set all Encoding options to 'best' but that doesn't change anything here)

<img width="1220" alt="Screenshot 2021-02-04 at 01 35 57" src="https://user-images.githubusercontent.com/309304/106950247-6d02f900-672e-11eb-96f0-abb044429645.png">

Btw. sorry for opening a ticket for that ;)

**Comment by dcommander** [comment]
It's all good.  GitHub issues can be used for general support as well as bug reports.

I'm wondering if this is the same issue described in #254.  From Terminal, can you try setting `JAVA_TOOL_OPTIONS=-Dsun.java2d.uiScale.enabled=false` and then launching the TurboVNC Viewer using `/opt/TurboVNC/bin/vncviewer &`?  (This assumes that you're using Java >= 9.)

**Comment by r10r** [comment]
Thanks for the fast answer and pointing to the java system properties.
I had an old JDK so I installed  [openjdk15](https://jdk.java.net/15/)

Unfortunately 

> try setting `JAVA_TOOL_OPTIONS=-Dsun.java2d.uiScale.enabled=false`

did not help. 

After some googling I spotted a stackoverflow thread [How to fix scaling of a java-based application on a high dpi display in linux?](https://stackoverflow.com/questions/58699877/how-to-fix-scaling-of-a-java-based-application-on-a-high-dpi-display-in-linux) suggesting to set `JAVA_TOOL_OPTIONS=-Dsun.java2d.uiScale=2.0`  which worked fine.


You can now rename TurboVNC to TurboSharpVNC  :D 

![Image 05 02 21 at 00 33](https://user-images.githubusercontent.com/309304/106968784-d04e5480-6749-11eb-9cbc-a6515bfa1d10.jpg)


For anyone doing this on macOS 11.x. The settings can be persisted in `/etc/launchd.conf`

```shell
# Set environment variables here so they are available globally to all apps
# (and Terminal), including those launched via Spotlight.
#
# After editing this file run the following command from the terminal to update
# environment variables globally without needing to reboot.
# NOTE: You will still need to restart the relevant application (including Terminal) to pick up the changes!
# grep -E "^setenv" /etc/launchd.conf | xargs -t -L 1 launchctl
#
# See http://www.digitaledgesw.com/node/31
# and http://stackoverflow.com/questions/135688/setting-environment-variables-in-os-x/
#
# Note that you must hardcode the paths below, don't use environment variables.
# You also need to surround multiple values in quotes.
#
#
# output from `/usr/libexec/java_home`
#setenv JAVA_HOME /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
setenv JAVA_HOME /Library/Java/JavaVirtualMachines/jdk-15.0.2.jdk/Contents/Home
setenv JAVA_TOOL_OPTIONS -Dsun.java2d.uiScale=2.0
```

**Comment by dcommander** [comment]
Awesome.  Thanks for sharing the solution!
