### ISSUE TITLE
Configuration of turbovnc on CentoS 7

### ISSUE THREAD

**Issue by MoiseKans** [TurboVNC/turbovnc#270]
Hello!
With CentOS server based on CentOS 5 & 6, i was using Tigervnc to configure a multiple sessions for a user.  Now I need to upgrade some of these servers to CentOS 7. But with CentOS 7, it is no longer possible tu have multiple session.
I have the following response TigerVnc user discussion.

"The new systemd-based launcher in the latest TigerVNC doesn’t support more than one simultaneous session, even if using a legacy-friendly window manager like MATE or Xfce that would otherwise work fine with multiple sessions. (Even GNOME 3 still works with multiple sessions. It just has some minor issues that have to be worked around.) I’ve been directing people who need multiple sessions to TurboVNC, which continues to support the multi-session vncserver approach (and is fully compatible with TigerVNC’s viewer, if people prefer that to our viewer.) TurboVNC is meant to be more of a cross-distribution solution, so we’ve had to come up with admittedly non-kosher ways of working around systemd limitations. TigerVNC chose instead to embrace those limitations in the name of reducing potential compatibility problems with newer window managers, but of course doing so removed a major piece of functionality that a lot of users relied upon. I would argue that that limitation was unnecessary in some cases. My customers are primarily in high-performance computing and visualization, and in that market space, the users are less likely to embrace new window managers like GNOME 3, but multi-session capabilities are critical."

Now I would like to know the configuration procedure with TurboVnc.
Thanks for the help

**Comment by dcommander** [comment]
No special procedure necessary.  Just install the TurboVNC RPM (refer to the [User's Guide](https://cdn.rawgit.com/TurboVNC/turbovnc/master/doc/index.html) for instructions), then

- `cp /etc/turbovncserver.conf ~/.vnc`
- Edit **~/.vnc/turbovncserver.conf**.
- Uncomment the `$wm` line.
- Change the value in quotes to an appropriate value for the window manager you intend to use (for instance, `gnome-session` or `mate-session` or `startxfce4`.)  Refer to https://turbovnc.org/Documentation/Compatibility22.
- Run `/opt/TurboVNC/bin/vncserver` as many times as you want.  (Each invocation will create a new session on a different X display number.)

Note that there are some [known issues](https://github.com/TurboVNC/turbovnc/issues?q=gnome+3+label%3A%22GNOME+3%22) with using GNOME 3 in VNC.  Most of these are unrelated to the use of multiple sessions (that is, TigerVNC's new systemd-friendly startup mechanism suffers from most of the same issues.)  The most friendly WM to use with TurboVNC is MATE, and https://turbovnc.org/Documentation/Compatibility22 provides instructions for installing it on CentOS 7.

**Comment by dcommander** [comment]
Please let me know if any of the above does not work.

**Comment by MoiseKans** [comment]
Thank you for your prompt response.
I used mate-session for the window manager and it work.

Now, I would like to know if instead of running many times (or each time when we kill all sessions), we can use vnc-ltsp-config to handle this? If yes, there are a special configuration to do?

Many thanks

**Comment by dcommander** [comment]
I don’t understand why you’d want to provide a login screen in a TurboVNC session. Wouldn’t that defeat the purpose of using a solution like TurboVNC that inherently supports multiple sessions under multiple user accounts? If you’re looking for a more user-friendly way to manage multiple sessions, try out the Session Manager in the TurboVNC 3.0 evolving builds.

**Comment by MoiseKans** [comment]
Hello,

Indeed, I may have to explain a little bit more our infra :
-	We use NIS as user authentication
-	We have more than 10 different Linux workstations
-	Each colleague can connect on every workstations
-	We use generic account for some purpose i.e. many users use the same ID and password

What we used to do is :
-	Install tigervnc
-	Install vnc-ltsp
-	As it is described in chapter 5 : https://wiki.centos.org/HowTos/VNC-Server 
This configuration allows us to not launch a priori vncserver for each user and sessions close when you log off.
We do not have to configure user environment or password and so on.
More details about advantages are mentioned in the Chapter 5.

What we understand for tigervncserver is that this feature of simplicity with multi-gui session is no more available but is it not more related to vnc-ltsp ?
Do you thing that we can configure turbovncserver with vnc-ltsp ?
When we try to install vnc-ltsp RPM it indicates a missing dependencies with vnc-server.

We succeeded to user up-to-date tigervncserver with vnc-ltsp but we can not open a second gui session after the first session opened.
But if we launch at the same time 2 gui session, it works, as if some lock filed were created ?

Thanks
