### ISSUE TITLE
Disable webserver

### ISSUE THREAD

**Issue by ich777** [TurboVNC/turbovnc#289]
Is there a way to disable the integrated webserver that runs by default on port 5900?
The command line argument `-nohttpd` doesn't work and also if I set `$enableHTTP = 0;` in `/etc/turbovncserver.conf` this changes nothing.

Am I missing something here? Maybe someone could help me out. :)

I'm running TurboVNC Server v2.2.6 on Debian Buster.

**Comment by dcommander** [comment]
Apparently I’m missing something, because TurboVNC doesn’t have anything that listens on port 5900. TurboVNC sessions listen on ports 5901-5999, and their associated web servers listen on 5801-5899.

**Comment by ich777** [comment]
Sorry mentioned the wrong port...
It is actually 5899

**Comment by dcommander** [comment]
Is a TurboVNC server listening on Display :99? If not, then I still have no explanation. How are you starting the server? Please provide details.

**Comment by ich777** [comment]
@dcommander sorry for the inconvenience and disturbing you, something was wrong with my port mappings inside the container and I think that was causing the issue (actually had a long day yesterday).

Thank you very much for helping me out and sorry for wasting your time... :/
