### ISSUE TITLE
"Attempted to configure an invalid screen layout" and "Rect too big"

### ISSUE THREAD

**Issue by nathanshearer** [TurboVNC/turbovnc#292]
I believe this is an issue with the vncviewer side and not the server side since UltraVNC vncviewer is able to connect successfully, while both TurboVNC and TigerVNC fail with these errors:
- Attempted to configure an invalid screen layout
- Rect too big

VNC Server
- Windows 10 Pro
- UltraVNC 1.3.2 x64

VNC Client
- TurboVNC 2.2.6 vncviewer

https://github.com/TigerVNC/tigervnc/issues/1257

**Comment by nathanshearer** [comment]
Error log from TurboVNC vncviewer:
```
$ vncviewer 
libjawt.so path: /etc/java-config-2/current-system-vm/lib/amd64
CConn: connected to host 192.168.0.110 port 5900
CConnection: Server supports RFB protocol version 3.8
CConnection: Using RFB protocol version 3.8
CConn: Using pixel format depth 24 (32bpp) little-endian rgb888
CConn: Requesting Tight encoding
TurboVNC Helper: Disabling X11 full-screen mode for window 0x07400060
CConn: Enabling GII
No extended input devices.
CMsgHandler: Server sent us an invalid screen layout
CMsgReader: Rect too big: 64x64 at 960,512 exceeds 0x0
Rect too big
```

**Comment by dcommander** [comment]
It appears that UltraVNC unfortunately decided to invent their own server-to-client extended desktop size message:
https://github.com/ultravnc/UltraVNC/blob/main/rfb/rfbproto.h#L1191-L1232
As near as I can determine, this violates the protocol:
https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#extendeddesktopsize-pseudo-encoding

**Comment by Neustradamus** [comment]
@nathanshearer: Have you tested the last UltraVNC?
- https://github.com/ultravnc/UltraVNC/issues/16
