### ISSUE TITLE
Screen auto resizing stopped working.

### ISSUE THREAD

**Issue by vbuterin2** [TurboVNC/turbovnc#295]
After a reboot, my turbovnc server won't update its desktop display size according to my turbovnc client's size. this made me feel so uncomfortable in full screen mode

**Comment by vbuterin2** [comment]
Is there a command to trigger for a auto resizing?

**Comment by dcommander** [comment]
Check the TurboVNC Viewer options and make sure that the Desktop Size setting is "auto".  You might also try disconnecting and reconnecting and, if that doesn't work, restarting the TurboVNC session on the host.

**Comment by dcommander** [comment]
Were you able to resolve the problem?
