### ISSUE TITLE
Multiple users, one vnc session

### ISSUE THREAD

**Issue by hinxx** [TurboVNC/turbovnc#296]
Doc says:
>  TurboVNC provides rudimentary collaboration capabilities. Multiple users can simultaneously view the same TurboVNC session and pass around control of the keyboard and mouse. 

Do I need to configure this on server/client somehow?

**Comment by dcommander** [comment]
No. It is default-enabled. Other sessions that can authenticate successfully can share the session with its creator. You can use Unix ACLs or one-time passwords to temporarily grant permission to other users of the system. Refer to the Xvnc man page.
