### ISSUE TITLE
The remote view is not scaling fully vertically in full screen mode

### ISSUE THREAD

**Issue by slehrs** [TurboVNC/turbovnc#297]
The issue started after Windows 10 update on 7/19/2021

**Comment by dcommander** [comment]
Will investigate.  Is this with the native Windows viewer of the Java viewer?

**Comment by slehrs** [comment]
It’s the native Windows viewer.

**Comment by slehrs** [comment]
Any luck with this issue?

From: Lehrs, Shachar
Sent: Thursday, July 22, 2021 1:21 PM
To: 'TurboVNC/turbovnc' ***@***.***>
Subject: RE: [TurboVNC/turbovnc] The remote view is not scaling fully vertically in full screen mode (#297)

It’s the native Windows viewer.

**Comment by dcommander** [comment]
Since it is a regression caused by Windows and will require upgrading my virtual machine, it may take some time before I can look into it.

**Comment by slehrs** [comment]
Thank you.
I appreciate it.

**Comment by slehrs** [comment]
I ran TurboVNC session with the same geometry as my screen and it works great!
Thank you very much for your help!

**Comment by dcommander** [comment]
Does it also work properly if you run a TurboVNC session with a different geometry but the same aspect ratio as your screen?  If so, then I suspect that this issue was a misunderstanding rather than a bug.

**Comment by slehrs** [comment]
Yes, there’s no bug. I just ran it with a different aspect ratio geometry.
I didn’t check but I assume it should work fine when running with same aspect ratio geometry.
