### ISSUE TITLE
Dead keys don't fully work with the Java viewer under Linux and Java 6

### ISSUE THREAD

**Issue by dcommander** [TurboVNC/turbovnc#30]
Refer to https://github.com/TurboVNC/turbovnc/commit/00c436d65544e1cbc004d4d73b6025c6b5de1719.  More detailed issue description:

Java 6, Windows:
* Press/release of a "modified" dead key (a dead key pressed along with Shift or AltGr to produce a different diacritic) causes Java to generate the key code for the unmodified dead key.  It might be possible to work around this, since the key character associated with the erroneous key code can be traced back to the correct dead key (for instance, when pressing dead tilde, the key character is always "~", even though the key code varies depending on the keyboard layout.)

Java 6 and 8, Windows:
* 2nd and subsequent even-numbered presses/releases of a modified dead key also cause Java to generate the key code for the unmodified dead key, as described above.  No known way to work around this, since the key character produced for these events is always 65535 (thus, there is no way to distinguish whether the event corresponds to a modified or unmodified dead key without knowing the specifics of the keyboard layout.)  This is not a serious issue, since it only prevents one from double-pressing a dead key to produce the corresponding "live" key symbol (but pressing the dead key + space still works.)

Java 6, Mac:
* Unmodified dead keys produce correct behavior, but modified dead keys produce incorrect key codes (and the key codes unfortunately are not distinguishable from key codes for non-dead-key events, nor is the key character helpful in these cases-- it is generally 65535 for the odd-numbered presses/releases and the "live" key symbol for even-numbered presses/releases)

Java 8, Mac:
* Depending on the keyboard layout, some dead keys do not produce KeyPress events (similar issue to Linux-- see below), and the others produce different key codes for the key release and key press events.  The key codes used for the release events are layout-dependent, and there is unfortunately no way of distinguishing those release events from non-dead-key release events.

Java, Linux:
* Does not seem to ever produce KeyPress events for dead keys.  Argh.

**Comment by dcommander** [comment]
Further info:  I thought it might be possible under Linux to work around this by simply sending a press + release event for a dead key to the server whenever a dead key release event is received by the viewer, but no such luck.  The JVM also sends only a release event for the modified (accented) letter.  Double-argh.  Those darn meddling kids...  In order to work around this on Linux, I'd have to maintain a list of pressed keys and automatically send a press event for every unexpected release.

It appears that there is already a bug filed against Java:
https://bugs.openjdk.java.net/browse/JDK-8016255

**Comment by dcommander** [comment]
The dead key issues should be resolved under Java 8 on Windows and OS X.  Linux still suffers from https://bugs.openjdk.java.net/browse/JDK-8016255, which may be possible to work around.  The Java 6 issues won't be fixed, as Java 6 is obsolete.  Leaving this issue unresolved until I can determine whether it makes sense to work around the Linux issues.

**Comment by dcommander** [comment]
It is possible to partially work around the issue in Linux using this patch:

```
diff --git a/java/com/turbovnc/vncviewer/CConn.java b/java/com/turbovnc/vncviewer/CConn.java
index 17d8c45..d5251f3 100644
--- a/java/com/turbovnc/vncviewer/CConn.java
+++ b/java/com/turbovnc/vncviewer/CConn.java
@@ -1718,7 +1718,7 @@ public class CConn extends CConnection implements UserPasswdGetter,
   // EDT
   public void writeKeyEvent(KeyEvent ev) {
     int keysym = -1, keycode, key, location;
-    boolean winAltGr = false;
+    boolean winAltGr = false, fakePress = false;
     String debugStr;
 
     if (shuttingDown || benchmark)
@@ -1751,18 +1751,49 @@ public class CConn extends CConnection implements UserPasswdGetter,
       Integer sym = pressedKeys.get(keycode);
 
       if (sym == null) {
-        // Note that dead keys will raise this sort of error falsely
-        // See https://bugs.openjdk.java.net/browse/JDK-6534883
-        debugStr += " UNEXPECTED/IGNORED";
+        if (VncViewer.isX11()) {
+          // Attempt to work around
+          // https://bugs.openjdk.java.net/browse/JDK-8016255
+          switch (keycode) {
+          case KeyEvent.VK_DEAD_ABOVEDOT:
+          case KeyEvent.VK_DEAD_ABOVERING:
+          case KeyEvent.VK_DEAD_ACUTE:
+          case KeyEvent.VK_DEAD_BREVE:
+          case KeyEvent.VK_DEAD_CARON:
+          case KeyEvent.VK_DEAD_CEDILLA:
+          case KeyEvent.VK_DEAD_CIRCUMFLEX:
+          case KeyEvent.VK_DEAD_DIAERESIS:
+          case KeyEvent.VK_DEAD_DOUBLEACUTE:
+          case KeyEvent.VK_DEAD_GRAVE:
+          case KeyEvent.VK_DEAD_IOTA:
+          case KeyEvent.VK_DEAD_MACRON:
+          case KeyEvent.VK_DEAD_OGONEK:
+          case KeyEvent.VK_DEAD_SEMIVOICED_SOUND:
+          case KeyEvent.VK_DEAD_TILDE:
+          case KeyEvent.VK_DEAD_VOICED_SOUND:
+            fakePress = nextKeyFakePress = true;
+            break;
+          default:
+            fakePress = nextKeyFakePress;
+            nextKeyFakePress = false;
+          }
+        }
+        if (!fakePress) {
+          // Note that dead keys will raise this sort of error falsely
+          // See https://bugs.openjdk.java.net/browse/JDK-6534883
+          debugStr += " UNEXPECTED/IGNORED";
+          vlog.debug(debugStr);
+          return;
+        }
+      }
+
+      if (!fakePress) {
+        writeKeyEvent(sym, false);
+        pressedKeys.remove(keycode);
+        debugStr += String.format(" => 0x%04x", sym);
         vlog.debug(debugStr);
         return;
       }
-
-      writeKeyEvent(sym, false);
-      pressedKeys.remove(keycode);
-      debugStr += String.format(" => 0x%04x", sym);
-      vlog.debug(debugStr);
-      return;
     }
 
     if (!ev.isActionKey()) {
@@ -2066,7 +2097,10 @@ public class CConn extends CConnection implements UserPasswdGetter,
     }
     debugStr += String.format(" => 0x%04x", keysym);
     vlog.debug(debugStr);
-    pressedKeys.put(keycode, keysym);
+    if (fakePress && !down)
+      writeKeyEvent(keysym, true);
+    else
+      pressedKeys.put(keycode, keysym);
     writeKeyEvent(keysym, down);
     if (winAltGr) {
       if (pressedKeys.containsValue(Keysyms.Control_L)) {
@@ -2266,6 +2300,7 @@ public class CConn extends CConnection implements UserPasswdGetter,
   private boolean supportsSyncFence;
 
   private HashMap<Integer, Integer> pressedKeys;
+  boolean nextKeyFakePress;
   Viewport viewport;
   boolean showToolbar;
   boolean keyboardGrabbed;
```

However, this is problematic, because if a dead key requires a Shift or AltGr modifier, then Java will report a different key code for the dead key's release event, depending on whether the dead key or the Shift/AltGr modifier was released first.  The only known way to work around this is to use the pressedKeys hash, and we can't do that without a key press event.  Barring that, the user would have to be extremely careful with Shift/AltGr-modified dead keys to ensure that they release the dead key prior to Shift or AltGr.  That's just too high-maintenance to be usable.  Java needs to do the right thing and fix the underlying issue.

The other problem, at least in my testing, is that Java doesn't always properly handle all of the available dead keys.  Specifically, under GNOME 2 with the U.S. International layout, Shift-AltGr-Slash is reported by Java as a slash, not a dead grave as it should be.  Similarly, Shift-AltGr-Minus is reported by Java as a minus, not a dead below dot.

Closing as SEP but adding a "revisit" tag to check up on the status of https://bugs.openjdk.java.net/browse/JDK-8016255 prior to the next TurboVNC release.

**Comment by dcommander** [comment]
Unfortunately, configuring a compose key on the client would not be a viable workaround, because Swing only fires a release event for `VK_COMPOSE` as well.  Grrr...

**Comment by dcommander** [comment]
Worked around via the implementation of #108, which is now available in the dev/3.1 evolving [pre-release build](https://turbovnc.org/DeveloperInfo/PreReleases).  Please test thoroughly.  (You need to use both the server and viewer from the pre-release build in order to activate the feature.)

**Comment by weipe** [comment]
It would be nice if this could be released as a stable, signed build, so we can get dead keys working on the Windows client. My work machine does not permit me to install dev/3.1 because it is unsigned/unknown publisher, so I can only download the stable  3.0.3 from sourceforge which still has the dead keys issue.

**Comment by dcommander** [comment]
Yes, I know.  I am working toward a 3.1 beta1 release, but there are still some things that need to go into it, and one of those things is a funded development project.  Since funded development is critical to the success of TurboVNC, I sometimes have to plan releases around it, and this is one of those cases.

**Comment by weipe** [comment]
Thanks for the quick answer!
