### ISSUE TITLE
Confirmation for closing viewer

### ISSUE THREAD

**Issue by phraide** [TurboVNC/turbovnc#300]
Is it possible to have a confirmation request when a user presses the disconnect button or closes the java viewer by mistake ?

**Comment by dcommander** [comment]
It's possible, but can you provide more details about the workflow that necessitates the feature?

**Comment by phraide** [comment]
VNC server is spawned by a job scheduler. Client is launched connecting to http port of VNC server serving the jnlp file.

**Comment by dcommander** [comment]
I'll see what I can do.

**Comment by dcommander** [comment]
Implemented.  Please test the feature and make sure I didn't screw something up.

**Comment by dcommander** [comment]
(Note that you will have to enable the feature by setting `ConfirmClose=1` in the parameter list in the .jnlp file that your portal generates.  You might also consider setting `NoNewConn=1` if you aren't doing so already.)
