### ISSUE TITLE
Frame spoiling problem with TurboVNC 

### ISSUE THREAD

**Issue by dimitris64bit** [TurboVNC/turbovnc#301]
Hi all,

I would appreciate any help on the following issue:

I have launched TurboVNC server (2.2.4) on a linux machine.
Then I access the server via TurboVNC viewer (2.2.4) from another linux machine.
Then I run an OpenGL application with VirtualGL v2.6.5 64-bit (Build 20201117):
vglrun +tr +v ./my_app.sh

The problem that I experience, is that after pressing a button (e.g. F1) that changes the OpenGL camera view, 
the key event seems to be processed by Qt, but the view is not updated.

Inside the code, I am calling the processEvents and just after that the flushX, but still the view is not updated.

The +tr log shows that the last calls are XCopyArea (multiple times) and finally the glXSwapBuffers.

Could you please shed some light of what might go wrong?
Is it a TurboVNC bug?
Is it a problem of the VNC buffer technology (copy only areas of massive pixel differences)?

Regards,
d

**Comment by dcommander** [comment]
Of those variables, `VGL_SPOILLAST`, `VGL_SYNC` and `VGL_SPOIL` are the only ones that might have made a difference.  The only other variable that might be relevant is `VGL_GLFLUSHTRIGGER`.
