### ISSUE TITLE
how to exit fullscreen via ctrl+esc esc right-click

### ISSUE THREAD

**Issue by levinit** [TurboVNC/turbovnc#302]
I've been wondering how do it, this is my keystroke flow:

0. enter the full screen
1. (in full screen) press <kbd>ctrl</kbd><kbd>esc</kbd>
2. release all keys
3. press <kbd>esc</kdb>
4. release <kbd>esc</kdb> key
5. mouse right click  (but where is the toolbar icon ???)

but it always does not work, how to exit full screen with these steps? thx.

and , 
any other way to exit fullscreen except <kbd>ctrl</kbd><kbd>alt</kbd><kbd>shift</kbd><kdb>f</kdb>  or enable alternate shortcuts **every** time (connect a new connection )  <kbd>alt</kbd><kbd>enter</kbd>

how about adding a hover button to exit the full screen in a future version?

**Comment by dcommander** [comment]
The Alt-Enter setting should be persistent once you set it in the TurboVNC Viewer Options dialog.  Is it not behaving that way?

I don't understand why you expect Ctrl-Esc-Esc to exit full-screen mode.  Is that a standard thing on Windows or some other operating system?

**Comment by levinit** [comment]
@dcommander thanks for reply, alt+enter works well, when I click fullscreen icon, it will tell that "ctrl-esc esc and right click toolbar icon", but I can not find the toolbar in fullscreen , OS is windows 10. Is this feature available?

**Comment by dcommander** [comment]
It is referring to the Windows taskbar, not the TurboVNC toolbar. The text in that dialog is probably 20 years old and may need to be updated to reflect the behavior of Windows 10.

**Comment by levinit** [comment]
understand now. Tanks

**Comment by dcommander** [comment]
Verified that the dialog correctly says "taskbar", not "toolbar" as was indicated in the post above.  This is a non-issue.
