### ISSUE TITLE
Scroll wheel input inserted at wrong location when scaling factor is >100%

### ISSUE THREAD

**Issue by birkenfeld** [TurboVNC/turbovnc#306]
I am using 150% scaling factor. Normal mouse clicks are processed fine, but scroll wheel input seems to be inserted at a different location from the current mouse cursor position. When I reset scaling to 100%, behavior is fine.

TurboVNC Viewer v2.2.6 (build 20211122) [JVM: amd64]

Let me know if I can anything more to debug this. Thanks!

**Comment by dcommander** [comment]
I will try to reproduce it.

**Comment by birkenfeld** [comment]
Looking at the code now, I see that `CConn::writePointerEvent` [contains code to handle scaling](https://github.com/TurboVNC/turbovnc/blob/main/java/com/turbovnc/vncviewer/CConn.java#L2448) while `CConn::writeWheelEvent` [does not](https://github.com/TurboVNC/turbovnc/blob/main/java/com/turbovnc/vncviewer/CConn.java#L2488).

**Comment by dcommander** [comment]
Thanks for the diagnosis!  I have integrated your fix into both the main (3.0) and 2.2.x branches.  CI builds should be available shortly.
