### ISSUE TITLE
Removal of -nohttpd arg not Documented in Release Notes for 2.2.90/ 3.0 Beta1

### ISSUE THREAD

**Issue by flakrat** [TurboVNC/turbovnc#311]
Howdy,

We encountered an issue when upgrading clients from 2.2.6 to 2.2.90 where the VNC desktop failed to to launch with:

```shell
Unrecognized option: -nohttpd
use: X [:<display>] [option]
-a #                   default pointer acceleration (factor)
```

`vncserver` is being launched via the following command syntax:

```shell
vncserver -log "#{vnc_log}" -rfbauth "#{vnc_passwd}" -nohttpd -noxstartup #{vnc_args}
```

I don't see anywhere in the man page or release notes where `-nohttpd` is mentioned as being removed. 

It appears that `-novnc` is now used to explicitly start a web server, as opposed to having to use `-nohttpd` to prevent starting one???

**Comment by dcommander** [comment]
The man page would not mention that a command-line option has been removed.  It would simply cease to contain a description of that option, the implication being that you should not use any command-line options that are not therein described.  The change log entry 3.0 beta1[6] implies that all command-line options and configuration directives associated with the built-in HTTP server were removed along with that feature.  (It isn't common practice for software to retain command-line options for a non-existent feature.)  However, I will modify the change log to make that explicit.
