### ISSUE TITLE
how to pass " -listen tcp " args from TurboVNC session manager to /opt/Turbovnc/bin/vncserver when creating new session?

### ISSUE THREAD

**Issue by wanlinwang** [TurboVNC/turbovnc#315]
Hi there,

How to pass " -listen tcp " args from TurboVNC session manager to /opt/Turbovnc/bin/vncserver when creating new session? 
Thanks a lot.

**Comment by dcommander** [comment]
Add it to the `$serverArgs` variable in **~/.vnc/turbovncserver.conf** or **/etc/turbovncserver.conf**.

**Comment by dcommander** [comment]
Also, if you need to add server arguments just temporarily, you can set `TVNC_SERVERARGS` in the environment on the client rather than modifying **turbovncserver.conf** on the host.
