### ISSUE TITLE
Compiling without the web server cannot run

### ISSUE THREAD

**Issue by fhriley** [TurboVNC/turbovnc#316]
If you compile turbovnc with `-DTVNC_BUILDWEBSERVER=0`, `/opt/TurboVNC/bin/webserver` will never exist. This means `vncserver` can never run because [it does a sanity check to verify `/opt/TurboVNC/bin/webserver` exists](https://github.com/TurboVNC/turbovnc/blob/3f9e08149c60f49e2c2ee07d469493857136a4d9/unix/vncserver.in#L1057).

**Comment by dcommander** [comment]
Oops.  Should be fixed now.
