### ISSUE TITLE
Session.connect: java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by wanlinwang** [TurboVNC/turbovnc#324]
Hi, could you please help to look into this error? Thank you! Below is the description,

Error: Session.connect: java.net.SocketException: Connection reset
![image](https://user-images.githubusercontent.com/32032219/163778375-64280f32-6a47-41c0-b43c-78c75de9d16f.png)

More info:
Server: CentOS 8.4
CLient: Windows 10

**Comment by dcommander** [comment]
Which version of TurboVNC?

**Comment by wanlinwang** [comment]
Hi there,

Server side:
Host: CentOS 8.4
TurboVNC: turbovnc-2.2.90.x86_64.rpm

Client side:
Host: Windows 10
TurboVNC Client: TurboVNC-2.2.90-x64.exe

By the way, the ssh port is connectable via MobaXterm. However, the turbovnc viewer complained the preceiding error.

**Comment by dcommander** [comment]
I have never seen that error. Can you check the TurboVNC session log (under ~/.vnc on the host) and see if the session failed to start for some reason?

**Comment by dcommander** [comment]
@wanlinwang Did you resolve the issue?

**Comment by wanlinwang** [comment]
> @wanlinwang Did you resolve the issue?

Sorry, I didn't. Could I close this?

**Comment by wanlinwang** [comment]
> @wanlinwang Did you resolve the issue?

Currently I don't need this environment which suffering this issue. So I close it.
