### ISSUE TITLE
Support for OpenSSL 3 / Ubuntu 22.04

### ISSUE THREAD

**Issue by LukasRuppert** [TurboVNC/turbovnc#325]
Hi,

I wanted to ask if you could add support for OpenSSL version 3 which is the only version provided with the new Ubuntu LTS version.
You probably just need to extend your list of suffixes to try and load `libssl.so.3` and `libcrypto.so.3`.
Creating a symlink to the new version with an extension contained in your current list works on my machine.
https://github.com/TurboVNC/turbovnc/blob/f2b115f207739a1dd2bedcb5a246179e943ee1d6/unix/Xvnc/programs/Xserver/hw/vnc/rfbssl_openssl.c#L185

Thanks

**Comment by dcommander** [comment]
Yes, I will install 22.04 and make sure everything works prior to releasing TurboVNC 3.0.
