### ISSUE TITLE
v3.0 unhappy with Win10 UltraVNC

### ISSUE THREAD

**Issue by karlkleinpaste** [TurboVNC/turbovnc#326]
Upgraded to 3.0 this morning. Attempted to connect to a remote Win10 UltraVNC server over VPN using:

`vncviewer -shared=0 -passwd .vnc/passwd -menukey F5 -fullscreen=0 -toolbar=0 -securitytypes=vncauth,tlsnone -recvclipboard=0 -sendclipboard=0 -viewonly latte-wired.hwpa`

(strictly observer mode: no clipboard, view only)

First it tossed up a warning about an unknown signature, and was I sure I wanted to continue; I wasn't aware that it should be trying to do such a thing. After verifying that it was in fact connecting to the right host, I hit OK, then I got this complaint:

![latte](https://user-images.githubusercontent.com/7548920/166812758-225dccbe-8352-48bc-a05b-bc7e8c7fd898.png)

I don't know what's going on with the new 3.0, but of course there's no TVNC installed there, and I don't know why it should be looking for it under any circumstance.

I downgraded to 2.2.7 and all is back to normal.

**Comment by dcommander** [comment]
Older versions assumed Display :0 when no display was specified, but TurboVNC 3.0 assumes that you intend to use the Session Manager if no display is specified. You can either specify the display, that is, add :0 to the VNC server name, or disable the session manager by passing `-nosessmgr` on the command line.
