### ISSUE TITLE
Why vncviewer cannot use key-based authentication?

### ISSUE THREAD

**Issue by wanlinwang** [TurboVNC/turbovnc#332]
![mmexport1654398763225.jpg](https://user-images.githubusercontent.com/32032219/172033817-bc6cfe12-0069-4eaa-b2e4-d5e9b9d35283.jpg)

![mmexport1654398764845.jpg](https://user-images.githubusercontent.com/32032219/172033402-da4034f5-57de-49a0-bab5-6d33cee85e21.jpg)

**Comment by dcommander** [comment]
Try the 3.0.x stable pre-release build. This has already been fixed.
