### ISSUE TITLE
Session Manager Error: Could not use SSH private key

### ISSUE THREAD

**Issue by nathanshearer** [TurboVNC/turbovnc#342]
TurboVNC Viewer 3.0.1 on Gentoo Linux.

I cannot connect to any hosts anymore. Even ones that are not running a VNC server fail with this error before attempting to actually connect:

> Session Manager Error:
> Could not use SSH private key: /home/user/.ssh/id_rsa:
> invalid privatekey

My ssh private key is valid and has been working for years and still works. I don't use SSH authentication with VNC for any connections and there seems to be no way to get around this error.

Older version 2.2.7 seems to work fine.

**Comment by nathanshearer** [comment]
I was connecting via an IP address without using :0 or any port offsets, for example: `192.168.100.42`
My ssh key was generated a few years ago for my user account with: `ssh-keygen -t rsa -b 16384` which has worked for ancient and modern systems alike when using ssh authorized keys. It's big key (deliberately), but that key size is supported by all versions of ssh.

**Comment by dcommander** [comment]
OK, well, that definitely explains why it was trying to activate SSH. Just add “:0” explicitly or disable the session manager, as described above, to restore the behavior of the TurboVNC 2.2.x viewer. I will look into the SSH key issue. It may be that JSch doesn’t support keys with that bit depth, in which case I’ll have to patch it.

**Comment by dcommander** [comment]
Regarding the SSH private key, I generated a new key using the exact command line you posted above, but I can't reproduce any problems with it.
