### ISSUE TITLE
Enable HiDPI (Retina Display) support to macOS client

### ISSUE THREAD

**Issue by yghorbal** [TurboVNC/turbovnc#352]
Hello,

The current build of macOS client does not take into account HiDPI Retina Displays on Macs and renders poorly (blurry images and fonts)

The trick is to include 
```
<key>NSHighResolutionCapable</key>
<true/>
```
at the end of **Contents/Info.plist** file to enable HiDPI support and make the interface and fonts really sharp.

I've tested it on my client and it's life changing! (I've included a screenshot of the main diag box with and without NSHighResolutionCapable)
<img width="953" alt="Screenshot 2022-12-13 at 23 16 56" src="https://user-images.githubusercontent.com/13449208/207457025-269ca4c3-505e-4bac-85a4-8a115f84cf31.png">
<img width="965" alt="Screenshot 2022-12-13 at 23 14 58" src="https://user-images.githubusercontent.com/13449208/207457046-91e73b57-86ca-434f-b948-98d4daf2899a.png">

The [same issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=382972) was reported for Eclipse and this very workaround was suggested

It would be nice if this is natively included in the official build!

Thank you for your help!

**Comment by dcommander** [comment]
Fix pushed and will be in the pre-release builds shortly (look for today's date on the pre-release build download page.)
