### ISSUE TITLE
[Ubuntu 22.04] "Oh no" screen + black screen on VNC viewer

### ISSUE THREAD

**Issue by S1sirocks** [TurboVNC/turbovnc#355]
When starting the 3.0.2 server on Ubuntu 22.04 I get the "Oh no" screen. If I don't close that window I can see that the server is running and I can connect to it from another Ubuntu 22.04 TurboVNC viewer, resulting in a black screen.

I am running /opt/TurboVNC/bin/vncserver with default xstartup.turbovnc although I have tried multiple combinations of the file based on internet comments.

Do let me know what further info you need to probe this problem further.

Thanks!

Log-1:
``
TurboVNC Server (Xvnc) 64-bit v3.0.2 (build 20221128)
Copyright (C) 1999-2022 The VirtualGL Project and many others (see README.txt)
Visit http://www.TurboVNC.org for more information on TurboVNC

09/01/2023 19:31:53 Using security configuration file /etc/turbovncserver-security.conf
09/01/2023 19:31:53 Enabled security type 'tlsvnc'
09/01/2023 19:31:53 Enabled security type 'tlsotp'
09/01/2023 19:31:53 Enabled security type 'tlsplain'
09/01/2023 19:31:53 Enabled security type 'x509vnc'
09/01/2023 19:31:53 Enabled security type 'x509otp'
09/01/2023 19:31:53 Enabled security type 'x509plain'
09/01/2023 19:31:53 Enabled security type 'vnc'
09/01/2023 19:31:53 Enabled security type 'otp'
09/01/2023 19:31:53 Enabled security type 'unixlogin'
09/01/2023 19:31:53 Enabled security type 'plain'
09/01/2023 19:31:53 Desktop name 'TurboVNC: mediacenter:2 (maka)' (mediacenter:2)
09/01/2023 19:31:53 Protocol versions supported: 3.3, 3.7, 3.8, 3.7t, 3.8t
09/01/2023 19:31:53 Listening for VNC connections on TCP port 5902
09/01/2023 19:31:53   Interface 0.0.0.0
09/01/2023 19:31:53 Framebuffer: BGRX 8/8/8/8
09/01/2023 19:31:53 New desktop size: 1240 x 900
09/01/2023 19:31:53 New screen layout:
09/01/2023 19:31:53   0x00000040 (output 0x00000040): 1240x900+0+0
09/01/2023 19:31:53 Maximum clipboard transfer size: 1048576 bytes
09/01/2023 19:31:53 VNC extension running!
xstartup.turbovnc: Creating new session bus instance:
xstartup.turbovnc:   unix:abstract=/tmp/dbus-vxHYItL9Dn,guid=e2fbffeef3b9f1bb2f27f3e963bc5d9a
xstartup.turbovnc: Using 'gnome' window manager in
xstartup.turbovnc:   /usr/share/xsessions/gnome.desktop
xstartup.turbovnc: Executing /etc/X11/Xsession "/usr/bin/gnome-session --session=gnome"

09/01/2023 19:32:12 Got connection from client 192.168.1.12
09/01/2023 19:32:13 Normal socket connection
09/01/2023 19:32:13 Using protocol version 3.8
09/01/2023 19:32:13 Enabling TightVNC protocol extensions
09/01/2023 19:32:13 Advertising Tight auth cap 'VENCRYPT'
09/01/2023 19:32:13 Advertising Tight auth cap 'VNCAUTH_'
09/01/2023 19:32:13 Advertising Tight auth cap 'ULGNAUTH'
09/01/2023 19:32:13 Client requested VeNCrypt sub-type 258
09/01/2023 19:32:13 Successfully loaded symbols from libssl.so.3
09/01/2023 19:32:13 Successfully loaded symbols from libcrypto.so.3
09/01/2023 19:32:13 Anonymous TLS key length: 2048 bits
09/01/2023 19:32:13 Available cipher suites: TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ADH-AES256-GCM-SHA384:ADH-AES128-GCM-SHA256:ADH-AES256-SHA256:ADH-CAMELLIA256-SHA256:ADH-AES128-SHA256:ADH-CAMELLIA128-SHA256:AECDH-AES256-SHA:ADH-AES256-SHA:ADH-CAMELLIA256-SHA:AECDH-AES128-SHA:ADH-AES128-SHA:ADH-CAMELLIA128-SHA:AECDH-NULL-SHA
09/01/2023 19:32:13 Deferring TLS handshake
09/01/2023 19:32:13 Negotiated cipher suite: AECDH-AES256-SHA
09/01/2023 19:32:17 Full-control authentication enabled for 192.168.1.12
09/01/2023 19:32:17 Pixel format for client 192.168.1.12:
09/01/2023 19:32:17   32 bpp, depth 24, little endian
09/01/2023 19:32:17   true colour: max r 255 g 255 b 255, shift r 16 g 8 b 0
09/01/2023 19:32:17   no translation needed
09/01/2023 19:32:17 Enabling full-color cursor updates for client 192.168.1.12
09/01/2023 19:32:17 Enabling Desktop Size protocol extension for client 192.168.1.12
09/01/2023 19:32:17 Enabling Extended Desktop Size protocol extension for client 192.168.1.12
09/01/2023 19:32:17 rfbProcessClientNormalMessage: ignoring unknown encoding -307 (fffffecd)
09/01/2023 19:32:17 Enabling LastRect protocol extension for client 192.168.1.12
09/01/2023 19:32:17 Enabling Continuous Updates protocol extension for client 192.168.1.12
09/01/2023 19:32:17 Enabling Fence protocol extension for client 192.168.1.12
09/01/2023 19:32:17 Enabling GII protocol extension for client 192.168.1.12
09/01/2023 19:32:17 Using tight encoding for client 192.168.1.12
09/01/2023 19:32:17 Using JPEG subsampling 2, Q62 for client 192.168.1.12
09/01/2023 19:32:17 Using JPEG quality 40 for client 192.168.1.12
09/01/2023 19:32:17 Using JPEG subsampling 0 for client 192.168.1.12
09/01/2023 19:32:17 Using Tight compression level 1 for client 192.168.1.12
09/01/2023 19:32:17 Using 4 threads for Tight encoding
09/01/2023 19:32:17 Client supports GII version 1
09/01/2023 19:32:17 New screen layout:
09/01/2023 19:32:17   0x00000040 (output 0x00000040): 1240x900+0+0
09/01/2023 19:32:17 Continuous updates enabled
09/01/2023 19:32:17 Continuous updates enabled
09/01/2023 19:32:17 Continuous updates enabled
09/01/2023 19:32:22 New desktop size: 1846 x 994
09/01/2023 19:32:22 New screen layout:
09/01/2023 19:32:22   0x00000040 (output 0x00000040): 1846x994+0+0
09/01/2023 19:32:22 Continuous updates enabled
09/01/2023 19:32:22 Continuous updates enabled
09/01/2023 19:32:24 New desktop size: 1240 x 900
09/01/2023 19:32:24 New screen layout:
09/01/2023 19:32:24   0x00000040 (output 0x00000040): 1240x900+0+0
09/01/2023 19:32:24 Continuous updates enabled
09/01/2023 19:32:24 Continuous updates enabled
Terminated
Killing Xvnc process ID 8652`
``

Log-2:
``
TurboVNC Server (Xvnc) 64-bit v3.0.2 (build 20221128)
Copyright (C) 1999-2022 The VirtualGL Project and many others (see README.txt)
Visit http://www.TurboVNC.org for more information on TurboVNC

09/01/2023 19:41:52 Using security configuration file /etc/turbovncserver-security.conf
09/01/2023 19:41:52 Enabled security type 'tlsvnc'
09/01/2023 19:41:52 Enabled security type 'tlsotp'
09/01/2023 19:41:52 Enabled security type 'tlsplain'
09/01/2023 19:41:52 Enabled security type 'x509vnc'
09/01/2023 19:41:52 Enabled security type 'x509otp'
09/01/2023 19:41:52 Enabled security type 'x509plain'
09/01/2023 19:41:52 Enabled security type 'vnc'
09/01/2023 19:41:52 Enabled security type 'otp'
09/01/2023 19:41:52 Enabled security type 'unixlogin'
09/01/2023 19:41:52 Enabled security type 'plain'
09/01/2023 19:41:52 Desktop name 'TurboVNC: mediacenter:2 (maka)' (mediacenter:2)
09/01/2023 19:41:52 Protocol versions supported: 3.3, 3.7, 3.8, 3.7t, 3.8t
09/01/2023 19:41:52 Listening for VNC connections on TCP port 5902
09/01/2023 19:41:52   Interface 0.0.0.0
09/01/2023 19:41:52 Framebuffer: BGRX 8/8/8/8
09/01/2023 19:41:52 New desktop size: 1240 x 900
09/01/2023 19:41:52 New screen layout:
09/01/2023 19:41:52   0x00000040 (output 0x00000040): 1240x900+0+0
09/01/2023 19:41:52 Maximum clipboard transfer size: 1048576 bytes
09/01/2023 19:41:52 VNC extension running!

09/01/2023 19:42:20 Got connection from client 192.168.1.12
09/01/2023 19:42:20 Normal socket connection
09/01/2023 19:42:21 Using protocol version 3.8
09/01/2023 19:42:21 Enabling TightVNC protocol extensions
09/01/2023 19:42:21 Advertising Tight auth cap 'VENCRYPT'
09/01/2023 19:42:21 Advertising Tight auth cap 'VNCAUTH_'
09/01/2023 19:42:21 Advertising Tight auth cap 'ULGNAUTH'
09/01/2023 19:42:21 Client requested VeNCrypt sub-type 258
09/01/2023 19:42:21 Successfully loaded symbols from libssl.so.3
09/01/2023 19:42:21 Successfully loaded symbols from libcrypto.so.3
09/01/2023 19:42:21 Anonymous TLS key length: 2048 bits
09/01/2023 19:42:21 Available cipher suites: TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ADH-AES256-GCM-SHA384:ADH-AES128-GCM-SHA256:ADH-AES256-SHA256:ADH-CAMELLIA256-SHA256:ADH-AES128-SHA256:ADH-CAMELLIA128-SHA256:AECDH-AES256-SHA:ADH-AES256-SHA:ADH-CAMELLIA256-SHA:AECDH-AES128-SHA:ADH-AES128-SHA:ADH-CAMELLIA128-SHA:AECDH-NULL-SHA
09/01/2023 19:42:21 Deferring TLS handshake
09/01/2023 19:42:21 Negotiated cipher suite: AECDH-AES256-SHA
09/01/2023 19:42:25 Full-control authentication enabled for 192.168.1.12
09/01/2023 19:42:25 Pixel format for client 192.168.1.12:
09/01/2023 19:42:25   32 bpp, depth 24, little endian
09/01/2023 19:42:25   true colour: max r 255 g 255 b 255, shift r 16 g 8 b 0
09/01/2023 19:42:25   no translation needed
09/01/2023 19:42:25 Enabling full-color cursor updates for client 192.168.1.12
09/01/2023 19:42:25 Enabling Desktop Size protocol extension for client 192.168.1.12
09/01/2023 19:42:25 Enabling Extended Desktop Size protocol extension for client 192.168.1.12
09/01/2023 19:42:25 rfbProcessClientNormalMessage: ignoring unknown encoding -307 (fffffecd)
09/01/2023 19:42:25 Enabling LastRect protocol extension for client 192.168.1.12
09/01/2023 19:42:25 Enabling Continuous Updates protocol extension for client 192.168.1.12
09/01/2023 19:42:25 Enabling Fence protocol extension for client 192.168.1.12
09/01/2023 19:42:25 Enabling GII protocol extension for client 192.168.1.12
09/01/2023 19:42:25 Using tight encoding for client 192.168.1.12
09/01/2023 19:42:25 Using JPEG subsampling 2, Q62 for client 192.168.1.12
09/01/2023 19:42:25 Using JPEG quality 40 for client 192.168.1.12
09/01/2023 19:42:25 Using JPEG subsampling 0 for client 192.168.1.12
09/01/2023 19:42:25 Using Tight compression level 1 for client 192.168.1.12
09/01/2023 19:42:25 Using 4 threads for Tight encoding
09/01/2023 19:42:25 Client supports GII version 1
09/01/2023 19:42:26 New screen layout:
09/01/2023 19:42:26   0x00000040 (output 0x00000040): 1240x900+0+0
09/01/2023 19:42:26 Continuous updates enabled
09/01/2023 19:42:26 Continuous updates enabled
09/01/2023 19:42:26 Continuous updates enabled
09/01/2023 19:42:28 New desktop size: 1846 x 994
09/01/2023 19:42:28 New screen layout:
09/01/2023 19:42:28   0x00000040 (output 0x00000040): 1846x994+0+0
09/01/2023 19:42:28 Continuous updates enabled
09/01/2023 19:42:28 Continuous updates enabled
09/01/2023 19:42:30 New desktop size: 1240 x 900
09/01/2023 19:42:30 New screen layout:
09/01/2023 19:42:30   0x00000040 (output 0x00000040): 1240x900+0+0
09/01/2023 19:42:30 Continuous updates enabled
09/01/2023 19:42:30 Continuous updates enabled
09/01/2023 19:42:34 Client 192.168.1.12 gone
09/01/2023 19:42:34 Statistics:
09/01/2023 19:42:34   key events received 0, pointer events 86
09/01/2023 19:42:34   framebuffer updates 3, rectangles 16, bytes 240
09/01/2023 19:42:34     LastRect markers 3, bytes 36
09/01/2023 19:42:34     cursor shape updates 1, bytes 12
09/01/2023 19:42:34     Tight rectangles 12, bytes 192
09/01/2023 19:42:34   raw equivalent 16.267732 Mbytes, compression ratio 84727.770833
``

**Comment by dcommander** [comment]
Are you intending to run GNOME as a window manager?  That is the default in TurboVNC if you don't specify a window manager.

**Comment by S1sirocks** [comment]
I really don't care, just want to make it work. 
I have also tried with xfce4, running -wm xfce4 with same result. Would you suggest any check to try?
Thanks

**Comment by dcommander** [comment]
You need to pass `-wm xfce`, not `-wm xfce4`.  https://turbovnc.org/Documentation/Compatibility30

**Comment by S1sirocks** [comment]
Oh, ok thanks.
Now the server doesn't start:

10/01/2023 13:15:26 Using security configuration file /etc/turbovncserver-security.conf
10/01/2023 13:15:26 Enabled security type 'tlsvnc'
10/01/2023 13:15:26 Enabled security type 'tlsotp'
10/01/2023 13:15:26 Enabled security type 'tlsplain'
10/01/2023 13:15:26 Enabled security type 'x509vnc'
10/01/2023 13:15:26 Enabled security type 'x509otp'
10/01/2023 13:15:26 Enabled security type 'x509plain'
10/01/2023 13:15:26 Enabled security type 'vnc'
10/01/2023 13:15:26 Enabled security type 'otp'
10/01/2023 13:15:26 Enabled security type 'unixlogin'
10/01/2023 13:15:26 Enabled security type 'plain'
10/01/2023 13:15:26 Desktop name 'TurboVNC: mediacenter:2 (maka)' (mediacenter:2)
10/01/2023 13:15:26 Protocol versions supported: 3.3, 3.7, 3.8, 3.7t, 3.8t
10/01/2023 13:15:26 Listening for VNC connections on TCP port 5902
10/01/2023 13:15:26   Interface 0.0.0.0
10/01/2023 13:15:26 Framebuffer: BGRX 8/8/8/8
10/01/2023 13:15:26 New desktop size: 1240 x 900
10/01/2023 13:15:26 New screen layout:
10/01/2023 13:15:26   0x00000040 (output 0x00000040): 1240x900+0+0
10/01/2023 13:15:26 Maximum clipboard transfer size: 1048576 bytes
10/01/2023 13:15:26 VNC extension running!
xstartup.turbovnc: Creating new session bus instance:
xstartup.turbovnc:   unix:abstract=/tmp/dbus-pv4aBhBJxx,guid=47bbf5945296be99b3e3bc5063bd56df
xstartup.turbovnc: Using 'xfce' window manager in
xstartup.turbovnc:   /usr/share/xsessions/xfce.desktop
xstartup.turbovnc: Executing /etc/X11/Xsession "startxfce4"
Segmentation fault (core dumped)
Killing Xvnc process ID 7051

Could you point me where to look?
Thanks!

**Comment by dcommander** [comment]
Ouch.  Can you obtain a stack trace from the Xvnc process?

**Comment by dcommander** [comment]
NOTE: It's not clear from the server output whether Xvnc or Xfce is crashing.  The stack trace obviously wouldn't be relevant if the segfault is occurring in Xfce.

**Comment by S1sirocks** [comment]
Can you point me how to do that?

It's weird, sometimes there is no crash but the screen is still black:

10/01/2023 16:27:48 Got connection from client 192.168.2.12
10/01/2023 16:27:49 Normal socket connection
10/01/2023 16:27:49 Using protocol version 3.8
10/01/2023 16:27:49 Enabling TightVNC protocol extensions
10/01/2023 16:27:49 Advertising Tight auth cap 'VENCRYPT'
10/01/2023 16:27:49 Advertising Tight auth cap 'VNCAUTH_'
10/01/2023 16:27:49 Advertising Tight auth cap 'ULGNAUTH'
10/01/2023 16:27:49 Client requested VeNCrypt sub-type 258
10/01/2023 16:27:49 Anonymous TLS key length: 2048 bits
10/01/2023 16:27:49 Available cipher suites: TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ADH-AES256-GCM-SHA384:ADH-AES128-GCM-SHA256:ADH-AES256-SHA256:ADH-CAMELLIA256-SHA256:ADH-AES128-SHA256:ADH-CAMELLIA128-SHA256:AECDH-AES256-SHA:ADH-AES256-SHA:ADH-CAMELLIA256-SHA:AECDH-AES128-SHA:ADH-AES128-SHA:ADH-CAMELLIA128-SHA:AECDH-NULL-SHA
10/01/2023 16:27:49 Deferring TLS handshake
10/01/2023 16:27:50 Negotiated cipher suite: AECDH-AES256-SHA
10/01/2023 16:27:53 Full-control authentication enabled for 192.168.2.12
10/01/2023 16:27:53 Pixel format for client 192.168.2.12:
10/01/2023 16:27:53   32 bpp, depth 24, little endian
10/01/2023 16:27:53   true colour: max r 255 g 255 b 255, shift r 16 g 8 b 0
10/01/2023 16:27:53   no translation needed
10/01/2023 16:27:53 Enabling full-color cursor updates for client 192.168.2.12
10/01/2023 16:27:53 Enabling Desktop Size protocol extension for client 192.168.2.12
10/01/2023 16:27:53 Enabling Extended Desktop Size protocol extension for client 192.168.2.12
10/01/2023 16:27:53 rfbProcessClientNormalMessage: ignoring unknown encoding -307 (fffffecd)
10/01/2023 16:27:53 Enabling LastRect protocol extension for client 192.168.2.12
10/01/2023 16:27:53 Enabling Continuous Updates protocol extension for client 192.168.2.12
10/01/2023 16:27:53 Enabling Fence protocol extension for client 192.168.2.12
10/01/2023 16:27:53 Enabling GII protocol extension for client 192.168.2.12
10/01/2023 16:27:53 Using tight encoding for client 192.168.2.12
10/01/2023 16:27:53 Using JPEG subsampling 2, Q62 for client 192.168.2.12
10/01/2023 16:27:53 Using JPEG quality 40 for client 192.168.2.12
10/01/2023 16:27:53 Using JPEG subsampling 0 for client 192.168.2.12
10/01/2023 16:27:53 Using Tight compression level 1 for client 192.168.2.12
10/01/2023 16:27:53 Using 4 threads for Tight encoding
10/01/2023 16:27:53 Client supports GII version 1
10/01/2023 16:27:53 New screen layout:
10/01/2023 16:27:53   0x00000040 (output 0x00000040): 1846x994+0+0
10/01/2023 16:27:53 Continuous updates enabled
10/01/2023 16:27:53 Continuous updates enabled
10/01/2023 16:27:53 Continuous updates enabled
10/01/2023 16:27:56 Continuous updates enabled
10/01/2023 16:27:56 Enabling full-color cursor updates for client 192.168.2.12
10/01/2023 16:27:56 rfbProcessClientNormalMessage: ignoring unknown encoding -307 (fffffecd)
10/01/2023 16:27:56 Enabling LastRect protocol extension for client 192.168.2.12
10/01/2023 16:27:56 Using tight encoding for client 192.168.2.12
10/01/2023 16:27:56 Using Tight compression level 1 for client 192.168.2.12
10/01/2023 16:27:56 Enabling full-color cursor updates for client 192.168.2.12
10/01/2023 16:27:56 rfbProcessClientNormalMessage: ignoring unknown encoding -307 (fffffecd)
10/01/2023 16:27:56 Enabling LastRect protocol extension for client 192.168.2.12
10/01/2023 16:27:56 Using tight encoding for client 192.168.2.12
10/01/2023 16:27:56 Using JPEG subsampling 2, Q62 for client 192.168.2.12
10/01/2023 16:27:56 Using JPEG quality 40 for client 192.168.2.12
10/01/2023 16:27:56 Using JPEG subsampling 0 for client 192.168.2.12
10/01/2023 16:27:56 Using Tight compression level 1 for client 192.168.2.12
10/01/2023 16:27:56 Continuous updates enabled
10/01/2023 16:28:17 Continuous updates enabled
10/01/2023 16:28:17 Enabling full-color cursor updates for client 192.168.2.12
10/01/2023 16:28:17 rfbProcessClientNormalMessage: ignoring unknown encoding -307 (fffffecd)
10/01/2023 16:28:17 Enabling LastRect protocol extension for client 192.168.2.12
10/01/2023 16:28:17 Using tight encoding for client 192.168.2.12
10/01/2023 16:28:17 Using Tight compression level 1 for client 192.168.2.12
10/01/2023 16:28:17 Enabling full-color cursor updates for client 192.168.2.12
10/01/2023 16:28:17 rfbProcessClientNormalMessage: ignoring unknown encoding -307 (fffffecd)
10/01/2023 16:28:17 Enabling LastRect protocol extension for client 192.168.2.12
10/01/2023 16:28:17 Using tight encoding for client 192.168.2.12
10/01/2023 16:28:17 Using JPEG subsampling 2, Q62 for client 192.168.2.12
10/01/2023 16:28:17 Using JPEG quality 40 for client 192.168.2.12
10/01/2023 16:28:17 Using JPEG subsampling 0 for client 192.168.2.12
10/01/2023 16:28:17 Using Tight compression level 1 for client 192.168.2.12
10/01/2023 16:28:18 Continuous updates enabled
10/01/2023 16:28:19 Client 192.168.2.12 gone
10/01/2023 16:28:19 Statistics:
10/01/2023 16:28:19   key events received 0, pointer events 182
10/01/2023 16:28:19   framebuffer updates 7, rectangles 30, bytes 440
10/01/2023 16:28:19     LastRect markers 5, bytes 60
10/01/2023 16:28:19     cursor shape updates 5, bytes 60
10/01/2023 16:28:19     Tight rectangles 20, bytes 320
10/01/2023 16:28:19   raw equivalent 36.698540 Mbytes, compression ratio 114682.937500

10/01/2023 16:28:41 Got connection from client 192.168.2.12
10/01/2023 16:28:41 Normal socket connection
10/01/2023 16:28:41 Using protocol version 3.8
10/01/2023 16:28:41 Enabling TightVNC protocol extensions
10/01/2023 16:28:41 Advertising Tight auth cap 'VENCRYPT'
10/01/2023 16:28:41 Advertising Tight auth cap 'VNCAUTH_'
10/01/2023 16:28:41 Advertising Tight auth cap 'ULGNAUTH'
10/01/2023 16:28:41 Client requested VeNCrypt sub-type 258
10/01/2023 16:28:42 Anonymous TLS key length: 2048 bits
10/01/2023 16:28:42 Available cipher suites: TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ADH-AES256-GCM-SHA384:ADH-AES128-GCM-SHA256:ADH-AES256-SHA256:ADH-CAMELLIA256-SHA256:ADH-AES128-SHA256:ADH-CAMELLIA128-SHA256:AECDH-AES256-SHA:ADH-AES256-SHA:ADH-CAMELLIA256-SHA:AECDH-AES128-SHA:ADH-AES128-SHA:ADH-CAMELLIA128-SHA:AECDH-NULL-SHA
10/01/2023 16:28:42 Deferring TLS handshake
10/01/2023 16:28:42 Negotiated cipher suite: AECDH-AES256-SHA
10/01/2023 16:28:45 Full-control authentication enabled for 192.168.2.12
10/01/2023 16:28:45 Pixel format for client 192.168.2.12:
10/01/2023 16:28:45   32 bpp, depth 24, little endian
10/01/2023 16:28:45   true colour: max r 255 g 255 b 255, shift r 16 g 8 b 0
10/01/2023 16:28:45   no translation needed
10/01/2023 16:28:45 Enabling full-color cursor updates for client 192.168.2.12
10/01/2023 16:28:45 Enabling Desktop Size protocol extension for client 192.168.2.12
10/01/2023 16:28:45 Enabling Extended Desktop Size protocol extension for client 192.168.2.12
10/01/2023 16:28:45 rfbProcessClientNormalMessage: ignoring unknown encoding -307 (fffffecd)
10/01/2023 16:28:45 Enabling LastRect protocol extension for client 192.168.2.12
10/01/2023 16:28:45 Enabling Continuous Updates protocol extension for client 192.168.2.12
10/01/2023 16:28:45 Enabling Fence protocol extension for client 192.168.2.12
10/01/2023 16:28:45 Enabling GII protocol extension for client 192.168.2.12
10/01/2023 16:28:45 Using tight encoding for client 192.168.2.12
10/01/2023 16:28:45 Using JPEG subsampling 2, Q62 for client 192.168.2.12
10/01/2023 16:28:45 Using JPEG quality 40 for client 192.168.2.12
10/01/2023 16:28:45 Using JPEG subsampling 0 for client 192.168.2.12
10/01/2023 16:28:45 Using Tight compression level 1 for client 192.168.2.12
10/01/2023 16:28:45 Using 4 threads for Tight encoding
10/01/2023 16:28:45 Client supports GII version 1
10/01/2023 16:28:45 Continuous updates enabled
10/01/2023 16:29:07 Client 192.168.2.12 gone
10/01/2023 16:29:07 Statistics:
10/01/2023 16:29:07   key events received 0, pointer events 119
10/01/2023 16:29:07   framebuffer updates 1, rectangles 6, bytes 88
10/01/2023 16:29:07     LastRect markers 1, bytes 12
10/01/2023 16:29:07     cursor shape updates 1, bytes 12
10/01/2023 16:29:07     Tight rectangles 4, bytes 64
10/01/2023 16:29:07   raw equivalent 7.339708 Mbytes, compression ratio 114682.937500

10/01/2023 16:29:12 Got connection from client 192.168.2.12
10/01/2023 16:29:12 Normal socket connection
10/01/2023 16:29:12 Using protocol version 3.8
10/01/2023 16:29:12 Enabling TightVNC protocol extensions
10/01/2023 16:29:12 Advertising Tight auth cap 'VENCRYPT'
10/01/2023 16:29:12 Advertising Tight auth cap 'VNCAUTH_'
10/01/2023 16:29:12 Advertising Tight auth cap 'ULGNAUTH'
10/01/2023 16:29:12 Client requested VeNCrypt sub-type 258
10/01/2023 16:29:13 Anonymous TLS key length: 2048 bits
10/01/2023 16:29:13 Available cipher suites: TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ADH-AES256-GCM-SHA384:ADH-AES128-GCM-SHA256:ADH-AES256-SHA256:ADH-CAMELLIA256-SHA256:ADH-AES128-SHA256:ADH-CAMELLIA128-SHA256:AECDH-AES256-SHA:ADH-AES256-SHA:ADH-CAMELLIA256-SHA:AECDH-AES128-SHA:ADH-AES128-SHA:ADH-CAMELLIA128-SHA:AECDH-NULL-SHA
10/01/2023 16:29:13 Deferring TLS handshake
10/01/2023 16:29:13 Negotiated cipher suite: AECDH-AES256-SHA
10/01/2023 16:29:16 Full-control authentication enabled for 192.168.2.12
10/01/2023 16:29:16 Pixel format for client 192.168.2.12:
10/01/2023 16:29:16   32 bpp, depth 24, little endian
10/01/2023 16:29:16   true colour: max r 255 g 255 b 255, shift r 16 g 8 b 0
10/01/2023 16:29:16   no translation needed
10/01/2023 16:29:17 Enabling full-color cursor updates for client 192.168.2.12
10/01/2023 16:29:17 Enabling Desktop Size protocol extension for client 192.168.2.12
10/01/2023 16:29:17 Enabling Extended Desktop Size protocol extension for client 192.168.2.12
10/01/2023 16:29:17 rfbProcessClientNormalMessage: ignoring unknown encoding -307 (fffffecd)
10/01/2023 16:29:17 Enabling LastRect protocol extension for client 192.168.2.12
10/01/2023 16:29:17 Enabling Continuous Updates protocol extension for client 192.168.2.12
10/01/2023 16:29:17 Enabling Fence protocol extension for client 192.168.2.12
10/01/2023 16:29:17 Enabling GII protocol extension for client 192.168.2.12
10/01/2023 16:29:17 Using tight encoding for client 192.168.2.12
10/01/2023 16:29:17 Using JPEG subsampling 2, Q62 for client 192.168.2.12
10/01/2023 16:29:17 Using JPEG quality 40 for client 192.168.2.12
10/01/2023 16:29:17 Using JPEG subsampling 0 for client 192.168.2.12
10/01/2023 16:29:17 Using Tight compression level 1 for client 192.168.2.12
10/01/2023 16:29:17 Using 4 threads for Tight encoding
10/01/2023 16:29:17 Client supports GII version 1
10/01/2023 16:29:17 Continuous updates enabled
