### ISSUE TITLE
Where to download the new server. All I download is View

### ISSUE THREAD

**Issue by huddhudd** [TurboVNC/turbovnc#363]
Where to download the new server. All I download is View

**Comment by dcommander** [comment]
Please be more specific. What do you mean by the "new server"? And what platform are you trying to download a server for?

**Comment by huddhudd** [comment]
![image](https://user-images.githubusercontent.com/8034908/222879447-d1b24860-9a3a-4ba7-8de3-cc60d83ea464.png)
only Viewer

**Comment by dcommander** [comment]
We do not have a Windows server. You can use our viewer with the UltraVNC Server.
