### ISSUE TITLE
Use Arithmetic or Progressive Huffman Encoding to Improve JPEG Compression on Low-Bandwidth Networks

### ISSUE THREAD

**Issue by dcommander** [TurboVNC/turbovnc#37]
JPEGs using arithmetic entropy coding are part of the official spec but are not widely used.  Using arithmetic coding decreases compression/decompression performance significantly (2-3x), but modern hardware has become fast enough that it should still be possible to maintain 25-30 fps on a 2-megapixel image stream without encountering a CPU bottleneck.  Furthermore, arithmetic coding decreases the size of the JPEG images by 15-20%, which would correspond to a similar decrease in the network footprint of the image stream for applications that produce a high number of unique colors.  That could increase the frame rate significantly on low-bandwidth networks, or it could allow users to increase the quality of the JPEG images without compromising frame rate.  The arithmetic codec in libjpeg-turbo isn't very highly optimized, so there is probably a lot of potential for accelerating it by using similar techniques to the ones we used on the Huffman codec.

The TurboVNC decoder doesn't really care what type of JPEG image it receives, as long as it's decompressible by libjpeg-turbo, so we could implement this feature in several different ways:
1. Arithmetic coding could be enabled in the TurboVNC Server by requesting one of the currently unused Tight compression levels (Levels 3 and 8, for instance.)
2. Arithmetic coding could be enabled by using the existing (and not-widely-advertised) Compression Level 9, which is meant to be the most extreme level of compression.  This makes a certain amount of sense, becuase CL 9 imparts a similar sort of trade-off (10-20% increase in compression ratio, 2x decrease in performance) for non-JPEG subrectangles.  CL 9 is currently not useful for 3D applications, but adding arithmetic coding support to it would change that.
3. Arithmetic coding could be enabled using an as-yet-to-be-defined RFB pseudo-encoding.

Option 1 is the least disruptive, since it would preserve the existing behavior of all of the other compression levels.  Option 3 is the most flexible, since it could be enabled/disabled independently of the other options.  Option 2 probably makes the most sense from a usability point of view, and if CL 9 could be altered such that it is useful for 3D applications, then we could expose that option in the GUI (currently CL 9 can only be selected from the TurboVNC Viewer command line.)

**Comment by hildred** [comment]
I don't care for option three (jpeg is jpeg), and I disagree about it being more flexible (options are options and can be added as needed or useful).  As to which compression level we use, the presented interface is that the larger the number the more processor is traded for bandwidth efficiency, I believe the best policy is to allow shuffling compression levels as needed to best fit that assumption, and that no guarantee of any specific meaning be assigned to any given value.

**Comment by dcommander** [comment]
That makes sense.  The only reason why I suggested possibly using a separate RFB pseudo-encoding is that, traditionally, the compression level in TightVNC-compatible solutions is independent of the JPEG encoding settings.  That's because you can specify different compression levels even if JPEG isn't enabled.  However, there is no reason why TurboVNC has to adhere to that standard.  Our approach has traditionally been to expose only the encoding combinations that have been proven to provide useful trade-offs.  For instance, in TigerVNC and TightVNC, any compression levels above 5 are essentially useless.  They don't increase the compression ratio by more than a couple of percent on average relative to CL 5, and they increase CPU usage by as much as 4-5x.  So TurboVNC's "extreme" compression mode (CL 9) is currently calibrated to emulate the compression ratio of TightVNC's CL 5.  We added that mode at the behest of the libvncserver developers, who were concerned that replacing the TightVNC encoder with the TurboVNC encoder would reduce the overall "tightness" of the solution.  They wanted a mode that would provide equivalent compression for 2D applications without using any more CPU time, regardless of whether the library was compiled with libjpeg or libjpeg-turbo.  CL 9 in TurboVNC actually comes within 1% on average of the compression ratio of TightVNC CL 5 for 2D applications, while providing 10% better performance.  For 3D applications, it is about 60% tighter and 2x as fast as TightVNC CL 5.  However, when you look at it in terms of incremental improvements, it works like this:

CL 1 to CL 2:  ~19% better compression and ~13% more CPU usage for 2D app workloads, ~13% better compression and ~20% more CPU usage for 3D app workloads (good trade-off)

CL 2 to CL 9:  ~18% better compression and ~2x thee CPU usage for 2D app workloads,  ~7% better compression and ~2.25x the CPU usage for 3D app workloads (not such a good trade-off)

That's what I mean when I say that CL 9 currently has little or no usefulness for 3D applications, and the trade-off for 2D applications is less than favorable as well.  However, if we can get 20% better compression with JPEGs, that will change the fundamental assumptions about that compression mode, and it may be possible to re-design it such that it has a better trade-off.  Or we can simply move the existing CL 9 to CL 8 and make arithmetic coding the new CL 9.  I would need to do some low-level experiments with the TurboVNC Benchmark Tools to determine the best approach.

**Comment by hildred** [comment]
Agreed.

**Comment by dcommander** [comment]
Another possibility here would be to integrate a set of SSE2 SIMD extensions for progressive Huffman encoding.  Those extensions have been submitted to libjpeg-turbo, but they are in need of funding for integration and testing labor:
https://github.com/libjpeg-turbo/libjpeg-turbo/pull/46

The amount of compression from prog. Huffman wouldn't be as high as arithmetic coding, but the performance would be much better.  Accelerating the arithmetic codec in libjpeg-turbo would be a relatively large undertaking, and it would have to be accelerated on both the client and server side in order to achieve sufficient performance.  To put some numbers on this:

Across the set of test images I typically use for libjpeg-turbo testing, which includes three 3D application screen captures (http://www.libjpeg-turbo.org/About/Performance), arithmetic coding compresses about 15% better than baseline on average, with an 5x drop in compression performance and a 6x drop in decompression performance (also on average.)  With the SIMD-accelerated progressive Huffman codec, we'd be looking at about a 10% improvement in compression (on average) with a 4x drop in compression performance and a 3x drop in decompression performance.  That would still put the compressor in the range of about 15-30 Megapixels/sec and the decompressor in the range of 30-40 Mpixels/sec, which is enough to achieve at least usable frame rates on a 2-megapixel screen.

**Comment by dcommander** [comment]
Unfortunately, this just didn't bear out the way I had hoped.  Even with the 2X improvement in progressive encoding performance in libjpeg-turbo, adding progressive Huffman encoding to the existing Compression Level 9 reduced the encoding performance by about 25% for only a 4-5% overall gain in compression ratio for 3D applications.  Not worth it.
