### ISSUE TITLE
clipboard UTF-8 support issue

### ISSUE THREAD

**Issue by levinit** [TurboVNC/turbovnc#375]
hi, I found the 3.0.9 release note mentions that the clipboard now supports UTF-8.

So I upgrade the server&viewer to 3.0.9, then launch a new session and connect it, but the text after pasting still garbled.

1. I open vscode and create a new file with UTF-8 encoding on Windows(client), input 2 Chinese words: 你好 , then copy them

2. paste on Linux (server), it shows ???+

#113
Where am I not configured correctly？ thx！

**Comment by dcommander** [comment]
This issue seems to be specific to Windows clients, as I cannot reproduce it on macOS.  I will investigate.

**Comment by dcommander** [comment]
Should be fixed now.

**Comment by levinit** [comment]
> The issue seems to be that Java on Un*x and macOS uses UTF-8 text encoding by default, whereas Java/Windows uses a different text encoding (windows-1252) by default.  You can temporarily work around the issue by setting `JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8` in the environment.  I am looking into a more permanent fix.

add env var, it works

**Comment by dcommander** [comment]
> add env var, it works

OK. Did you try the actual fix? The new pre-release build should work without the environment variable.
