### ISSUE TITLE
Toggle remote cursor rendering breaks updates on keyboard input

### ISSUE THREAD

**Issue by norman-geist** [TurboVNC/turbovnc#38]
After toggling the remote cursor rendering option in an active connection between to linux boxes, it seems to break something with the udpinputport as entered text is not seen anymore. It seems keyboard input do nor more trigger an update of the vnc screen, whereas the enetered text gets visible when moving the editor window inside vnc.

**Comment by dcommander** [comment]
Will investigate.

**Comment by norman-geist** [comment]
Some more detailes:

I'm using KDE4, and XDMCP to get an login screen. Within the login screen the problem doesn't occur. I can switch remote cursor rendering on/off. But, after login, when turning off the remote cursor rendering, only one more keyboard hit is shown in e.g an console terminal. Afterwards no keyboard hit triggeres an screen update anymore. But it can be seen that all keyboard hits were sent to the vnc, as they appear suddenly when moving the console terminal window around using the mouse.

**Comment by dcommander** [comment]
Please supply the following details:

- Which version of Linux is running on the server?

- Which version of Linux is running on the client?

- Which version of the TurboVNC Server are you using?

- Which version of the TurboVNC Viewer are you using?

**Comment by norman-geist** [comment]
*        Open Suse 13.1 on server with custom Kernel 3.11.10

*        Open Suse 13.1 on Client default Kernel 3.12.53-40-desktop / also from Windows Clients e.g. Windows 10

*        Tried Versions: 1.2.90, 2.0.2, 2.0.91

*        Tried Versions: 1.2.90, 2.0.2, 2.0.91

 

Von: DRC [mailto:notifications@github.com] 
Gesendet: Donnerstag, 14. April 2016 21:27
An: TurboVNC/turbovnc <turbovnc@noreply.github.com>
Cc: norman-geist <norman.geist@uni-greifswald.de>
Betreff: Re: [TurboVNC/turbovnc] Toggle remote cursor rendering breaks updates on keyboard input (#38)

 

Please supply the following details:

*     Which version of Linux is running on the server?

*     Which version of Linux is running on the client?

*     Which version of the TurboVNC Server are you using?

*     Which version of the TurboVNC Viewer are you using?

**Comment by dcommander** [comment]
There seem to be some general problems with server-side cursor rendering, stemming from the upgrade of our X server code base to X.org 7.7 (which happened in TurboVNC 2.0.)  I'm investigating.

**Comment by dcommander** [comment]
This issue is tied very closely to #38, so it's proving tricky to solve both of them simultaneously without breaking something else.  I'll keep you posted.  I've had an extraordinarily busy summer and thus haven't been able to spend more than 10 or 15 hours looking at this, and it's probably going to take 10 or 15 hours more to resolve it.  It's required a lot of digging through the code history and adding debug statements and such.  This absolutely will be fixed in TurboVNC 2.1.  I'm delaying that release for this and a couple of other critical bugs.

**Comment by dcommander** [comment]
Please try again with the current code in Git master.  I was never able to reproduce this specific problem, but I'm hoping that the other problems that were fixed with server-side cursor rendering fixed this one as well.  If not, then I'm going to need more details about how to reproduce this.

**Comment by dcommander** [comment]
Please re-test with the release candidate and let me know if this problem still exists:

http://www.turbovnc.org/DeveloperInfo/PreReleases

**Comment by norman-geist** [comment]
I’m not able to reproduce the problem anymore, maybe fixed by os update of a 3rd party library.

 

Von: DRC [mailto:notifications@github.com] 
Gesendet: Montag, 4. April 2016 17:48
An: TurboVNC/turbovnc <turbovnc@noreply.github.com>
Cc: norman-geist <norman.geist@uni-greifswald.de>
Betreff: Re: [TurboVNC/turbovnc] Toggle remote cursor rendering breaks updates on keyboard input (#38)

 

Will investigate.

**Comment by dcommander** [comment]
OK, cool.  Closing as fixed.
