### ISSUE TITLE
Separately turbovnc viewer

### ISSUE THREAD

**Issue by paolosezart** [TurboVNC/turbovnc#381]
How can I separately download and install turbovnc viewer on windows? I already use tightvnc server. But I'm thinking of switching to turbovnc. To do this, I would like to test how it behaves and what functionality is available (file transfer, clipboard, etc.) in turbovnc viewer with servers from other developers. I want to find a universal vnc client and server for remote computer management (windows, debian), android tv and raspberry pi (debian).

**Comment by dcommander** [comment]
What do you mean separately? The only TurboVNC component for Windows is the TurboVNC Viewer, so you just need to download the TurboVNC Windows installer and install it. Not sure why you had to file a GitHub issue rather than just trying that.
