### ISSUE TITLE
After disable  "Render cursor locally" VNC Serssion cursor flicker

### ISSUE THREAD

**Issue by SimontChan** [TurboVNC/turbovnc#382]
Thank you for your contribution. Currently, I have encountered an issue while using the service.
I don't choose "Render cursor locally"（Due to the nature of my work, I have no choice but to do so.）, I am bothered by the flickering of the mouse cursor when I move the mouse pointer.
VNC Server：TurboVNC Server v3.0.3（Centos 7.9 GNOME）
VNC Client：TurboVNC Viewer v3.0.3（Windows 10 22H2）

You can watch the video file, thanks.
https://github.com/TurboVNC/turbovnc/assets/145539600/056d455b-5e5b-4d2f-bd03-156e97805032

![image](https://github.com/TurboVNC/turbovnc/assets/145539600/6b5d14b1-ca1d-4c1e-82b0-02d3aac105ba)
![image](https://github.com/TurboVNC/turbovnc/assets/145539600/d471162a-31fe-4bbb-a18f-c45fa0e9dfc4)

**Comment by dcommander** [comment]
Unfortunately, I cannot reproduce the issue when using the same configuration, TurboVNC versions, and operating systems.

**Comment by SimontChan** [comment]
@dcommander 
Thank you for your feedback.
 I have noticed that issues can occur when using monitors with different refresh rates. My laptop display has a resolution of 1920x1080p and a refresh rate of 60Hz, while my HDMI monitor has the same resolution but a refresh rate of 120Hz. The laptop display is set as the primary display in Windows, which tends to cause problems in this scenario.
It is strange that my colleague's laptop and HDMI monitor, both with a resolution of 1920x1080p and a refresh rate of 60Hz, do not encounter any issues.
Here is my system env：
![image](https://github.com/TurboVNC/turbovnc/assets/145539600/fcbc7419-391b-407e-9ddf-7f5b9701c086)
![image](https://github.com/TurboVNC/turbovnc/assets/145539600/f763f78d-1ff3-4885-a09d-c981eb7cdf0a)
![image](https://github.com/TurboVNC/turbovnc/assets/145539600/f0822b86-2080-4418-9d29-f9f11eded70e)

**Comment by dcommander** [comment]
This is a shot in the dark, but try setting `JAVA_TOOL_OPTIONS=-Dturbovnc.swingdb=1` in the system environment.

**Comment by SimontChan** [comment]
@dcommander 
Thank you for your response. I attempted to add JAVA_TOOL_OPTIONS=-Dturbovnc.swingdb=1 to the Windows system environment variables and restarted TurboVNC Client, but the issue still persists.
![image](https://github.com/TurboVNC/turbovnc/assets/145539600/d9d31698-720c-42d5-bae2-61e49440e9b8)

**Comment by SimontChan** [comment]
@dcommander Yes, I have no choice.

**Comment by dcommander** [comment]
By "clarify", I mean explain *why* you have no choice.
