### ISSUE TITLE
Repo problem?

### ISSUE THREAD

**Issue by sjpb** [TurboVNC/turbovnc#387]
There seems to be a problem with the repos at the moment. Trying to dnf install anything on a RockyLinux 8 system with the Turbovnc repofile installed fails with:

```
Failed to download metadata for repo 'TurboVNC': Yum repo downloading error: Downloading error(s): repodata/985592b30463108e0ddec7a671e3bec67f692894779564b4979405b44a882f56-primary.xml.gz - Cannot download, all mirrors were already tried without success
```
or
```
Failed to download metadata for repo 'TurboVNC': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

or any one of similar errors

**Comment by sjpb** [comment]
Are the repos rate limited now? I'm getting `Failed to download metadata for repo 'TurboVNC': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried` on 1 of 6 nodes when trying to deploy to a cluster.

**Comment by dcommander** [comment]
No, it's probably just a mirroring issue triggered when I rebuilt the YUM repository.  Since I am in the process of moving the YUM repository to another host, it doesn't make sense for me to try to debug what's wrong with SourceForge.  (Such issues are a big reason why I am moving the repository.)

**Comment by sjpb** [comment]
Thank you. Any ideas on timescale for when repos are *likely* to have been transitioned please 🙏 (accepting things don't always work out as planned!)? Days, weeks?

**Comment by dcommander** [comment]
Hopefully by the end of this week.  Others who are experiencing this problem reported that it eventually went away after they did `yum clean all` or `dnf clean all`.

**Comment by dcommander** [comment]
I think the existing YUM repository should be working again.  If not, you can beta test the new YUM repository:

https://raw.githubusercontent.com/TurboVNC/repo/main/TurboVNC.repo

**Comment by sjpb** [comment]
Using new repofile/repos now, thanks for all the communications 🙏
