### ISSUE TITLE
QUEMU Key Event feature now causes login difficulties with local vs remote keymaps

### ISSUE THREAD

**Issue by ihayhurst** [TurboVNC/turbovnc#390]
The new QUEMU Key event  feature causes login difficulty
Could I request that the ability to toggle this feature please from the viewer? 

I have Turbovnc 3.1 on both server an viewer

"TurboVNC 3.1 by implementing the QEMU Extended Key Event extension to the RFB protocol...
...Moving the key mapping from client side to server side"  now prevents me logging into my desktops with UK keyboards configured when I have a US keyboard where screensaver passwords contain chars that differ (typically `@"` on uk / us)

Work around is to log in via ssh terminal, as root disable the screenlock with `loginctl unlock-sessions`
then once connected with Turbovnc  override the the server side keyboard with `setxkbmap us` in a terminal

or to use a version prior to 3.1 on either client or server, however that isn't sustainable moving forward
Many thanks.

**Comment by ihayhurst** [comment]
basically you can't type a password in to a remote 'screensaver'  screen lock is a better name for a virtual screen yes it's Gnome on somewhat ageing Centos7 desktops (you can type a password in but previously it would use a keymap from the remote client so all was well. With the new behaviour you get whatever the remote machine maps your keys to it's configured keyboard until you can get in and override it

**Comment by dcommander** [comment]
If you absolutely need to disable the QEMU Extended Key Event extension, you can do so by passing `-noserverkeymap` on the command line when starting the TurboVNC Viewer, e.g. `/opt/TurboVNC/bin/vncviewer -noserverkeymap` or `"c:\Program Files\TurboVNC\vncviewer.bat" -noserverkeymap`.  However, on my CentOS 7 system, the lock screen has a gadget in the upper right that allows you to change the keyboard layout, so I can't actually reproduce the issue you are experiencing.
