### ISSUE TITLE
 Run TurboVNC client and server via port forwarding

### ISSUE THREAD

**Issue by nEghbal** [TurboVNC/turbovnc#412]
Hello,

Is it possible to run the client and server over a tunnel with port forwarding?

Thanks,
Nooshin

**Comment by dcommander** [comment]
Yes.  The TurboVNC Session Manager, in fact, enables SSH tunneling automatically.  You can also use the `-tunnel` or `-via` options in the TurboVNC Viewer, either with the viewer's built-in SSH client or an external SSH client (by specifying `-extssh`.)  Refer to the [TurboVNC User's Guide](https://rawcdn.githack.com/TurboVNC/turbovnc/main/doc/index.html#hd006006) and the TurboVNC Viewer help screen (`/opt/TurboVNC/bin/vncviewer -?` or `"c:\Program Files\TurboVNC\vncviewer.bat -?`.)  The User's Guide describes what the viewer is actually doing when you pass `-via` or `-tunnel` to it.
