### ISSUE TITLE
Ramdon notification sound while running the application.

### ISSUE THREAD

**Issue by LucasMontero** [TurboVNC/turbovnc#424]
When using the application, a [notification sound](https://youtu.be/0mGkCw3SMZM?si=7MCOmmBvPQiWG6zz&t=6)  is triggered randomly and unexpectedly. Despite attempting to troubleshoot the issue by running the application through a shell, no output or error messages are generated when the notification sound occurs.

Environment Details:

    Platforms affected: Windows 11
    Application version: 3.1.1

**Comment by dcommander** [comment]
No idea.  Is it possible that the beep is coming from the server?  If so, then you should be able to silence it by unchecking "Beep when requested by server" in the TurboVNC Viewer Options dialog.  Apart from that, the TurboVNC Viewer does not generate sounds.
