### ISSUE TITLE
"Authentication is required to access the PC/SC daemon" dialog when launching GNOME 3 using TurboVNC (w/ -3dwm)

### ISSUE THREAD

**Issue by dcommander** [TurboVNC/turbovnc#52]
When launching GNOME 3 (including Classic) in TurboVNC on Fedora 24, a dialog pops up ("Authentication is required to access the PC/SC daemon"), and it cannot be dismissed unless your user account has sudo privileges.  This seems to be a problem endemic to all X proxies running on recent Linux distros that use GNOME 3 (yet another reason to use MATE instead, at least with TurboVNC.)

This is very similar to #47, and the workaround is similar as well.  Create a new file under /etc/polkit.1/rules.d (I call mine "03-allow-pcscd.rules"), then give it the following contents:

```
polkit.addRule(function(action, subject) {
    if (action.id == "org.debian.pcsc-lite.access_pcsc" &&
        subject.isInGroup("{group}")) {
            return polkit.Result.YES;
    }
});
```

where {group} is a group that you designate (I personally use the vglusers group, but it can be any group containing the users to whom you wish to grant access to the PC/SC daemon.)

**Comment by dcommander** [comment]
Referring to https://github.com/TurboVNC/turbovnc/issues/47#issuecomment-412324029, the same procedure can be used to work around this issue as well. Simply add `org.debian.pcsc-lite.access_pcsc` to the end of the `Action=` line.

**Comment by dcommander** [comment]
This should now be fixed in dev/3.0 evolving.  The RPM and DEB packages now include
**/etc/polkit-1/localauthority/50-local.d/45-turbovnc-gnome3.pkla**
with the following contents:

```
[Eliminate GNOME 3 dialogs in TurboVNC]
Identity=unix-user:*
Action=org.freedesktop.color-manager.create-device;org.freedesktop.color-manager.create-profile;org.freedesktop.color-manager.delete-device;org.freedesktop.color-manager.delete-profile;org.freedesktop.color-manager.modify-device;org.freedesktop.color-manager.modify-profile;org.debian.pcsc-lite.access_pcsc;org.freedesktop.packagekit.system-sources-refresh
ResultAny=no
ResultInactive=no
ResultActive=yes
```

That fixes this issue on all of the platforms I tested, but please let me know if I missed something.

**Comment by jave** [comment]
I get this bug when I upgrade from 2.2.6 to 2.2.80, oddly enough.

I havent tried the workarounds mentioned above yet.

**Comment by dcommander** [comment]
@jave That's very odd, since 2.2.5+ stable and 3.0 evolving should both automatically work around the issue.  The automatic workaround is deployed via a custom PKLA file, which is installed by our official release or pre-release RPM packages, so you will not get the automatic workaround if you install TurboVNC in some other way.
