### ISSUE TITLE
UltraVNC Repeater in TurboVNC

### ISSUE THREAD

**Issue by maxlinus** [TurboVNC/turbovnc#54]
hi, plz tell me how to use repeater (ultravnc) in turboVNC

    Features/fixes introduced in 2.0 beta1:
    [12]
    vncconnect can now be used to connect a TurboVNC Server session to an
    instance of the UltraVNC Repeater in Mode II.

**Comment by dcommander** [comment]
Wiki page added
http://www.turbovnc.org/Documentation/UltraVNCRepeater

**Comment by maxlinus** [comment]
Thank you.
still I found a startup options:
`/opt/TurboVNC/bin/vncviewer -via 128.128.128.128:5901 ID:654323`
and
`c:\Program Files\TurboVNC\vncviewer-java.bat -via 128.128.128.128:5901 ID:654323`

**Comment by dcommander** [comment]
Yes, those are correct options for Mode II, if the repeater is listening on port 5901 (which it would by default unless you edited uvncrepeater.ini-- personally, I prefer 5900) and if you created the reverse connection from the server using ID 654323.
