### ISSUE TITLE
Java: Window resizing issues under Unity

### ISSUE THREAD

**Issue by dcommander** [TurboVNC/turbovnc#63]
Because of inconsistencies in Java's reporting of window "insets" (Java-speak for the size of the window decorations-- borders, titlebar, etc.) under certain Linux window managers, it is necessary for the Java TurboVNC Viewer under Linux to create a small window (JFrame) at startup and call getInsets() to ask for the size of its insets.  The viewer then makes the assumption that these insets will be the same as the insets for the main viewer window.  The viewer needs to know these numbers ahead of time, because unlike some other GUI toolkits, resizing windows in Swing requires specifying the whole window size, including the decorations.  Thus, it is necessary to know how big the decorations are so the proper window size can be chosen.  This is particularly important when automatic desktop resizing is enabled.  If the viewer cannot properly calculate the maximum remote desktop size that can be displayed without scrollbars in a non-full-screen window, then it can cause infinite remote desktop size ping-ponging with the server or unnecessary scrollbars to be displayed.

In the past, it was discovered that getInsets() on Linux would sometimes return values that varied by 1 pixel in subsequent calls, which caused the aforementioned ping-ponging (refer to a2a3939e958c38f70974d26404d7df0152cf7ab2).  That, plus another issue specific to OS X, prompted me to pre-compute the insets as the viewer is starting up, but apparently even that was insufficient.  Under GNOME 3, it was discovered that getInsets() doesn't return correct values until componentResized() is called, which prompted c26cb8bdd6950c0112bb001f2da0c8da4861eaf7.  Under Unity, a similar issue exists whereby getInsets() always returns {0,0,0,0}, and there doesn't seem to be a way to work around it:  https://bugs.openjdk.java.net/browse/JDK-8153295.  This doesn't seem to cause any major usability issues, but in my testing, the viewer window would sometimes maximize unexpectedly, or sometimes the remote desktop chosen for a particular window size would be too small, thus causing white areas to appear around the remote desktop image.

**Comment by dcommander** [comment]
I spent some time poring through the OpenJDK code, and it seems that what's happening is that the JWM is waiting until the first ReparentNotify event on the window before setting the insets (refer to `sun.awt.X11.XDecoratedPeer.handleReparentNotifyEvent()`, https://github.com/openjdk-mirror/jdk/blob/jdk8u/jdk8u/master/src/solaris/classes/sun/awt/X11/XDecoratedPeer.java#L306-L380.)  Within the body of that function, `sun.awt.X11.XDecoratedPeer.getWMSetInsets()` is called with a null argument (https://github.com/openjdk-mirror/jdk/blob/jdk8u/jdk8u/master/src/solaris/classes/sun/awt/X11/XDecoratedPeer.java#L347), which causes it to call `XWM.getInsetsFromExtents()`, which in turn obtains the insets for the current window by probing the `_NET_FRAME_EXTENTS` Atom (https://github.com/openjdk-mirror/jdk/blob/jdk8u/jdk8u/master/src/solaris/classes/sun/awt/X11/XWM.java#L1419).  So it seems that there is some sort of a bug in Unity or perhaps compiz that prevents that Atom from being set to the proper value in a timely manner, and that causes a race condition.  Sometimes the Atom is set quickly enough that Java can obtain correct inset values, but most of the time it isn't.  This seems to not just be specific to Java:

https://answers.launchpad.net/unity/+question/255025

I don't think anything can be done about this within TurboVNC, unfortunately.  Even more unfortunately, I was able to reproduce the aforementioned ping-pong resize loop with the TurboVNC Viewer in Unity, because of this issue.  :(  The only workaround at the moment is to disable automatic desktop resizing or to just live with the quirkiness.  This has supposedly been fixed in OpenJDK 9 b130, but that fix hasn't made it into Ubuntu yet as of this writing.

**Comment by tidux** [comment]
This issue has reappeared under GNOME 3.24.3-1 jre8-openjdk 8.u144-1, on Arch Linux.

**Comment by dcommander** [comment]
According to the OpenJDK bug reports I linked to above, it has been resolved, but they decided not to back-port the fix to Java 8.  Any way you could test the early-access build of Java 9?
http://jdk.java.net/9/

I'm slammed right now working on other bug fixes for 2.1.2 and next-gen features for 2.2, both of which I hope to release this Fall.

If Java 9 fixes it, then I'll consider the matter resolved.  If it's truly the same bug as under Unity, then there isn't anything I can do about it in TurboVNC.  If it's a different bug, then maybe there is something I can do.  Also be sure to update to the latest stable 2.1.x pre-release build:
http://www.turbovnc.org/DeveloperInfo/PreReleases

I just pushed quite a few bug fixes, some of which might affect this.

**Comment by tidux** [comment]
This bug is resolved under the current prerelease builds of Java 9.

**Comment by dcommander** [comment]
Awesome!  Thank you for testing.  I'll double check it with Unity as well.

**Comment by dcommander** [comment]
Confirmed that JRE 9 produces the correct global insets with Unity as well.  There's still a little weirdness when using CTRL-ALT-Z to set the window to its default size/position (in some cases, the WM will offset it slightly, for reasons I can't explain), but at least the sizing is reported consistently and accurately to the application, so the ping-pong issue shouldn't occur.  Closing as fixed-external.
