### ISSUE TITLE
turbovnc 2.0.95 blank screen on KDE Plasma 5.6 (Linux Mint 18 KDE)

### ISSUE THREAD

**Issue by altdel** [TurboVNC/turbovnc#65]
Symptons: xstartup.turbovnc failed to launch plasma desktop; only a blank screen is seen.
I have the following installed:
1) turbovnc_2.0.95_amd64 preview release
2) virtualgl_2.5_amd64
3) libjpeg-turbo-official_1.5.0_amd64

Host is running Linux Mint 18 KDE version (Plasma 5.6); client is TurboVNC Viewer 2.0.95 on Windows 7.
Command: vncserver -3dwm -geometry 1920x1200 :7
Log file:
TurboVNC Server (Xvnc) 64-bit v2.0.95 (build 20160909)
Copyright (C) 1999-2016 The VirtualGL Project and many others (see README.txt)
Visit http://www.TurboVNC.org for more information on TurboVNC

14/09/2016 14:20:43 Using auth configuration file /etc/turbovncserver-security.conf
14/09/2016 14:20:43 Enabled authentication method 'tlsvnc'
14/09/2016 14:20:43 Enabled authentication method 'tlsotp'
14/09/2016 14:20:43 Enabled authentication method 'tlsplain'
14/09/2016 14:20:43 Enabled authentication method 'x509vnc'
14/09/2016 14:20:43 Enabled authentication method 'x509otp'
14/09/2016 14:20:43 Enabled authentication method 'x509plain'
14/09/2016 14:20:43 Enabled authentication method 'vnc'
14/09/2016 14:20:43 Enabled authentication method 'otp'
14/09/2016 14:20:43 Enabled authentication method 'unixlogin'
14/09/2016 14:20:43 Enabled authentication method 'plain'
14/09/2016 14:20:43 Desktop name 'TurboVNC: fangc6-dl:7 (fangc6)' (fangc6-dl:7)
14/09/2016 14:20:43 Protocol versions supported: 3.3, 3.7, 3.8, 3.7t, 3.8t
14/09/2016 14:20:43 Listening for VNC connections on TCP port 5907
14/09/2016 14:20:43   Interface 0.0.0.0
14/09/2016 14:20:43 Listening for HTTP connections on TCP port 5807
14/09/2016 14:20:43   URL http://fangc6-dl:5807
14/09/2016 14:20:43   Interface 0.0.0.0
14/09/2016 14:20:43 Framebuffer: BGRX 8/8/8/8
14/09/2016 14:20:43 Maximum clipboard transfer size: 1048576 bytes
14/09/2016 14:20:43 VNC extension running!

**Comment by dcommander** [comment]
Sorry for my lack of response on SourceForge.  I was getting around to it, but today's been a busy day.  I prefer to discuss it on GitHub anyhow.  I've tested Plasma 5.7 under Fedora 24 with no issues, but that was under Parallels Desktop, so it wasn't using a real GPU.  Another user had problems with Plasma 5 that were related to using an older version of VirtualGL (Plasma 5 uses Qt 5, which requires the XCB interposer in VirtualGL, but that interposer wasn't built or enabled by default until VirtualGL 2.5.)

**Comment by dcommander** [comment]
One thing to sanity check-- are you using our VirtualGL packages?  If not, please try them.  Certain distributions screw up the packaging of VirtualGL, which causes is to not load symbols correctly (this was known to be a problem under Arch, for instance.)

**Comment by dcommander** [comment]
If that doesn't bear fruit, then I'll have to try to bring up the KDE version of Linux Mint.  I have the MATE version installed currently.

**Comment by altdel** [comment]
Thanks for your response. I have VirtualGL 2.5 installed.
Here's the log after client tried to connect (actual IP address replaced w/A.B.C.D):
14/09/2016 14:39:20 Got connection from client A.B.C.D
14/09/2016 14:39:20 Using protocol version 3.8
14/09/2016 14:39:23 Full-control authentication enabled for A.B.C.D
14/09/2016 14:39:23 Using ZRLE encoding for client A.B.C.D
14/09/2016 14:39:23 rfbProcessClientNormalMessage: ignoring unknown encoding 22 (16)
14/09/2016 14:39:23 rfbProcessClientNormalMessage: ignoring unknown encoding 21 (15)
14/09/2016 14:39:23 rfbProcessClientNormalMessage: ignoring unknown encoding 15 (f)
14/09/2016 14:39:23 rfbProcessClientNormalMessage: ignoring unknown encoding -311 (fffffec9)
14/09/2016 14:39:23 Enabling full-color cursor updates for client A.B.C.D
14/09/2016 14:39:23 Enabling Desktop Size protocol extension for client A.B.C.D
14/09/2016 14:39:23 Pixel format for client A.B.C.D:
14/09/2016 14:39:23   32 bpp, depth 24, little endian
14/09/2016 14:39:23   true colour: max r 255 g 255 b 255, shift r 16 g 8 b 0
14/09/2016 14:39:23   no translation needed

**Comment by dcommander** [comment]
Do you have the official VirtualGL packages installed?  The ones from our SourceForge project?  Or is VirtualGL provided by your Linux distribution?

**Comment by altdel** [comment]
It's from your SourceForge project.
-rw-rw-r-- 1 fangc6 fangc6    1702432 Sep  8 08:58 virtualgl_2.5_amd64.deb

**Comment by altdel** [comment]
fangc6@fangc6-dl (517)/opt/VirtualGL/bin> ll
total 1612
drwxr-xr-x 2 root root   4096 Sep 12 13:20 ./
drwxr-xr-x 4 root root   4096 Sep 12 13:20 ../
-rwxr-xr-x 1 root root   9945 Feb 15  2016 cpustat*
-rwxr-xr-x 1 root root 115622 Feb 15  2016 glreadtest*
-rwxr-xr-x 1 root root  35912 Feb 15  2016 glxinfo*
-rwxr-xr-x 1 root root  40194 Feb 15  2016 glxspheres64*
-rwxr-xr-x 1 root root 114782 Feb 15  2016 nettest*
-rwxr-xr-x 1 root root 108352 Feb 15  2016 tcbench*
-rwxr-xr-x 1 root root 693214 Feb 15  2016 vglclient*
-rwxr-xr-x 1 root root 448521 Feb 15  2016 vglconfig*
-rwxr-xr-x 1 root root   5265 Feb 15  2016 vglconnect*
-rwxr-xr-x 1 root root    546 Feb 15  2016 vglgenkey*
-rwxr-xr-x 1 root root   1489 Feb 15  2016 vgllogin*
-rwxr-xr-x 1 root root   9845 Feb 15  2016 vglrun*
-rwxr-xr-x 1 root root  25869 Feb 15  2016 vglserver_config*

**Comment by dcommander** [comment]
OK.  For future reference, you don't need to install libjpeg-turbo-official when installing the "official" VirtualGL or TurboVNC packages, because our official packages are statically linked with libjpeg-turbo.  That was part of my confusion.  I'll try to bring up the KDE version of Mint and see if I can reproduce this.

**Comment by dcommander** [comment]
Also, can you tell me which GPU and driver you are using?

**Comment by altdel** [comment]
Nvidia Quadro 600 GPU and Nvidia 361.42 driver

**Comment by dcommander** [comment]
I don't have a new enough install of Mint to be able to install Plasma 5.6, but I installed it under Ubuntu 16.04, which I assume should be about the same.  I edited ~/.vnc/xstartup.turbovnc, inserting the following at the top:

```
vglrun +wm startkde
exit 0
```

Seems to work fine, so I don't think this is a Plasma issue or a TurboVNC issue.  It's probably an issue with how Plasma is launched by Mint.  It doesn't surprise me that TurboVNC's method of invoking the window manager (running /etc/X11/xinit/xinitrc) doesn't work in this case, because that machinery under Ubuntu-based distros is designed to work with gnome-session, and KDE uses a different mechanism.  I am not entirely sure how the KDE version of Mint handles things.  I would need to install it and poke around, which is more than I have time for right now.  Can you confirm that the above workaround fixes the problem on your end?

**Comment by altdel** [comment]
Tried that, but same as before. Here are the error messages in .vnc/myhost:5807.log
[VGL] ERROR: Could not open display :0.
No protocol specified
[VGL] ERROR: Could not open display :0.
No protocol specified
[VGL] ERROR: Could not open display :0.
No protocol specified
[VGL] ERROR: Could not open display :0.
No protocol specified
[VGL] ERROR: Could not open display :0.
startkde: Starting up...
startkde: Could not start D-Bus. Can you call qdbus?
No protocol specified
[VGL] ERROR: Could not open display :0.

**Comment by altdel** [comment]
$ which qdbus
/usr/bin/qdbus
$ ll /usr/bin/qdbus
lrwxrwxrwx 1 root root 9 Sep 12 10:32 /usr/bin/qdbus -> qtchooser*

**Comment by dcommander** [comment]
Ah, OK.  That means that VirtualGL isn't configured properly.  Have you run vglserver_config and restarted the display manager?  If so, and it's still failing in that manner, then perhaps this is a VirtualGL problem.

**Comment by dcommander** [comment]
I did some further testing by temporarily converting my install of Ubuntu 16.04 into Kubuntu:

```
sudo apt-get install kubuntu-desktop
sudo dpkg --purge ubuntu-desktop ubuntu-session
sudo update-alternatives --set x-session-manager /usr/bin/startkde
```

I also installed Linux Mint 18 KDE.  Ignore my previous comments about modifying xstartup.turbovnc.  That should not be necessary with a KDE-only distribution.  On such distros, /usr/share/gnome-session/sessions/ubuntu.session will not exist, so xstartup.turbovnc will not try to configure the upstart environment for Unity.  It will simply invoke /etc/X11/xinit/xinitrc, and because startkde is configured as the default X session manager, things should "just work" (as long as 3D WM support is enabled and VirtualGL is working properly.)  So I think this should start working for you once the VirtualGL issues are resolved.

**Comment by altdel** [comment]
Still not working after issueing "sudo vglserver_config" and rebooting the box.

There is some error messages in the output of vglserver_config. How do I fix it?
--------------------------------------------------------------------------
... Creating vglusers group ...
groupadd: group 'vglusers' already exists
Could not add vglusers group (probably because it already exists.)
... Granting read permission to /etc/opt/VirtualGL/ for vglusers group ...
... Creating /etc/modprobe.d/virtualgl.conf to set requested permissions for
    /dev/nvidia* ...
... Attempting to remove nvidia module from memory so device permissions
    will be reloaded ...
rmmod: ERROR: Module nvidia is in use by: nvidia_modeset nvidia_uvm
... Granting write permission to /dev/nvidia-modeset /dev/nvidia-uvm /dev/nvidia0 /dev/nvidiactl for vglusers group ...
... Granting write permission to /dev/dri/card0 for vglusers group ...
... Adding vglgenkey to /usr/share/sddm/scripts/Xsetup script ...


Done. You must restart the display manager for the changes to take effect.

IMPORTANT NOTE: Your system uses modprobe.d to set device permissions. You
must execute rmmod nvidia with the display manager stopped in order for the
new device permission settings to become effective.

**Comment by dcommander** [comment]
Those are all normal.  OK, try this:

```
/opt/TurboVNC/bin/vncserver -kill :1
/opt/TurboVNC/bin/vncserver -noxstartup
DISPLAY=:1 vglrun /opt/VirtualGL/bin/glxspheres64
```

That should help pinpoint whether VirtualGL is working and, if not, why not.  I was able to make VGL 2.5 work successfully on my install of Linux Mint KDE.

**Comment by altdel** [comment]
DISPLAY=:1 vglrun /opt/VirtualGL/bin/glxspheres64
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
No protocol specified
[VGL] ERROR: Could not open display :0.

**Comment by altdel** [comment]
Ha... got it working!
I had to stop sddm (sudo service sddm stop)
run vglserver_config
add myself and root to group vglusers (sudo adduser root vglusers)
start sddm again (sudo service sddm start)
Then everything works.
Well, almost... The new desktop size is 3200x1800, although I had specified "-geometry 1920x1200".
But, I had this problem with Kubuntu 14.04 as well. There is a kscreen setting that needs to be corrected. Should be easy to fix.

Thanks a lot for your help!

**Comment by dcommander** [comment]
I was just about to walk you through exactly that same procedure if things weren't working yet.  Glad you got it sorted.

`rm ~/.local/share/kscreen/* ~/.kde/share/apps/kscreen/*`

should get rid of any persistent screen resolution settings stored by KDE Plasma 4 or 5.
