### ISSUE TITLE
How do you install and RUN the server portion on a windows machine?

### ISSUE THREAD

**Issue by vally78** [TurboVNC/turbovnc#7]
Basically i need to connect to an IPV6 only windows 8 machine from a windows 8 machine.  I can get the viewer software installed on the viewer pc, but cant figure out how to run the server portion on the remote pc.

**Comment by dcommander** [comment]
The TurboVNC Server itself supports only Unix/Linux servers.  For Windows servers, I recommend using the UltraVNC Server with the TurboVNC Viewer.

**Comment by dcommander** [comment]
http://www.turbovnc.com/files/ultravnc.zip

contains an experimental build of UltraVNC with the TurboVNC encoder, so it should perform similarly to the TurboVNC Server.  In my experience, it is necessary to set the CPU usage limit to 90% on the server (in the UltraVNC Server settings) and use the mirror driver to achieve maximum performance.  When properly configured, I can get about 30% more performance out of this build of UltraVNC than the "stock" build, and ultimately I would like to submit my enhancements to that project.

**Comment by dcommander** [comment]
TurboVNC enhancements have been submitted and accepted by the UltraVNC developers and are now available in the 1.2.0.8 pre-release:

http://www.uvnc.com/downloads/ultravnc.html

**Comment by dcommander** [comment]
The TurboVNC encoder is now available in UltraVNC 1.2.0.9.  Refer to 
http://www.turbovnc.org/Documentation/UltraVNC
for instructions on how to get the maximum performance out of it.
