### ISSUE TITLE
Disable password for vnc

### ISSUE THREAD

**Issue by fixitben** [TurboVNC/turbovnc#74]
Hi 

Is there an easy way to not require a password for vnc sessions? We have a group of users and it would be much easier to not have the password. I did this with tiger vnc by commenting out sections in the vncserver file. I was wondering if you could tell me the sections to comment out or if there is a switch/option for this?

**Comment by dcommander** [comment]
Sure.  Just edit the TurboVNC Security Configuration File (/etc/turbovncserver-security.conf) and only enable security methods that don't require a VNC password.  For instance, if you want to use Unix login credentials and enforce encryption (to avoid sending those credentials over the open network), you could do:

```
permitted-security-types = TLSPlain, X509Plain, TLSOtp, X509Otp, OTP   
```

This would require that users authenticate using their Unix login credentials with a VeNCrypt-enabled viewer, or that they generate a one-time password for the session (the use of an OTP would allow non-VeNCrypt-enabled viewers to connect safely-- for collaboration purposes, for instance.)

**Comment by dcommander** [comment]
I should also point out that the Security Configuration File is used to specify the defaults for all sessions.  By setting the "permitted-security-types" variable, you are specifying which security types are "allowed" by TurboVNC sessions on that machine.  However, you can also choose to enable only a subset of the allowed security types by specifying the `-SecurityTypes` argument on the vncserver command line.  The default is to allow all security types, so you could achieve the same effect as above for a single session by starting it with:

```
/opt/TurboVNC/bin/vncserver -securitytypes TLSPlain,X509Plain,TLSOtp,X509Otp,OTP
```

You could also start a single session with no authentication at all by doing

```
/opt/TurboVNC/bin/vncserver -securitytypes TLSNone,X509None,None
```

The vncserver script is smart enough to parse the Security Configuration file, as well as the `-SecurityTypes` argument, and figure out whether it needs to invoke vncpasswd to generate a new VNC password.  It should not ever invoke vncpasswd unless one of the *Vnc security types is allowed and enabled.

**Comment by fixitben** [comment]
I guess I wasn't clear. I don't want a password at all. No Security. I tried the None Option but get an error. 

Fatal server error:
ERROR: no authentication methods enabled!

I want to be able to type in the session number using turbovnc viewer and it just open the session. Obviously it will have to be a session that has been generated using the vncserver command.

**Comment by dcommander** [comment]
The *None security types are allowed by default, so there is no need to edit the Security Configuration File in that case, but you have to explicitly specify them on the vncserver command line in order to enable them:

```
/opt/TurboVNC/bin/vncserver -securitytypes tlsnone,x509none,none
```

This is to prevent someone from accidentally starting a session without authentication.

**Comment by dcommander** [comment]
NOTE:  You can also automate that for a particular user by putting

```
$securityTypes = tlsnone,x509none,none
```

in ~/.vnc/turbovncserver.conf

**Comment by fixitben** [comment]
Ok. This works great. Thank you. I already have a shell script they use to start the vncserver I can just add the  -securitytypes tlsnone,x509none,none to that script. Thanks for your help.
