### ISSUE TITLE
Sane installation / building process for turbovnc on Ubuntu 14.04

### ISSUE THREAD

**Issue by aashidham** [TurboVNC/turbovnc#75]
I want to install turboVNC on my Ubuntu 14.04 LTS x86_64 instance with GLX support (which I think will mean installing virtualGL as well). [The instance is hosted on AWS EC2, which means it has NViDia drivers, I think?]

However, it is really frustrating getting this to work.

Maybe I'm an idiot. Regardless, I'm willing to *pay* somebody if they can provide a Docker image on Docker hub with turboVNC installed on Ubuntu 14.04 that supports GLX / OpenGL along with a Dockerfile that describes each step of the installation / building process. If you're going through the installation process, please describe where every jar / deb / rpm file comes from.

PLEASE. I'm begging you. Somebody do this. I will send Bitcoin to a wallet of your choice if you can do this in 24 hours.

**Comment by dcommander** [comment]
A Docker image would be difficult, because Docker wouldn't support the necessary drivers and X infrastructure to make VirtualGL work properly.  Can you e-mail me offline?  http://www.virtualgl.org/About/Contact  I'm happy to SSH into your EC2 instance and diagnose what's wrong.

**Comment by aashidham** [comment]
sent a note to you. lmk if you didnt get it,
