### ISSUE TITLE
TurboVNC does not release the alt key on the server after losing focus via alt-tab on the client.

### ISSUE THREAD

**Issue by xenium1024** [TurboVNC/turbovnc#88]
I am running TurboVNC Viewer 64-bit v2.1.1 (20170202) with UltraVNC Server v1.2.1.2. Both client and server are running Windows 7 64-bit Ultimate SP1. I have grabkeyboard set to 2.

When running TurboVNC in full-screen mode, if I use alt-tab to change focus to a different window on the client, and then physically go to the server console and use the keyboard connected directly to the server, I find that the server thinks that the alt key is still being held down.

Sending the alt-keydown to the server as soon as the key is pressed is the right thing to do of course, so TurboVNC should probably send an alt-keyup to the server if it detects that the client no longer has focus?

In my use-case, I have a dedicated computer connected to my television to play and stream video and music from. I use TurboVNC to control the computer, but also have a wireless keyboard connected to it, and tend to jump between the two a lot. I may use VNC on my laptop to start a video playing for example, and then alt-tab TurboVNC to the background. When the video is over, I may grab the wireless keyboard to start another video, and that's where I experience problems, because the UltraVNC server still thinks the alt key is being held down, even though I'm using the wireless keyboard.

Thanks! Please let me know if there is anything I can do to help.

**Comment by dcommander** [comment]
The viewer should send key up events for all modifier keys when it loses focus.  I'll investigate.

**Comment by xenium1024** [comment]
Another data point: I've noticed that the viewer does release the key when it's closed. In other words, I can have the viewer in full screen in the foreground, press alt-tab to put it in the background -- at this point the alt key will be "stuck" on the server. If I then close the viewer via any method (context menu, task manager, etc.), the alt key is then released on the server.

I am able to reproduce this bug consistently, so I'll try to do some further troubleshooting to see if it occurs with other other VNC servers and to see if I can reproduce it on any other client boxes, so far I have only had time to test on this one box.

**Comment by xenium1024** [comment]
I finally had a chance to do some more testing today. I was able to duplicate this on multiple clients and servers. I tested against UltraVNC Server 1.2.1.2, UltraVNC Server 1.2.1.5, and TightVNC server 2.8.8. I tested connections to each of these servers from TurboVNC running on three different clients, in both full-screen and windowed mode. In all cases, alt-tabbing away from the TurboVNC client caused the alt key to get "stuck" on the server. All clients and servers were running Windows 7 Ultra 64.

Please let me know if there's anything else I can do to help out with this.

**Comment by dcommander** [comment]
Thanks for the testing.  I will try to look at this issue this week.  Things are extraordinarily busy right now.

**Comment by dcommander** [comment]
Can't reproduce, unfortunately.  Tried with both viewers.  Verified that both viewers release modifier keys when the viewer window loses focus.  Please provide more details to help me reproduce this.

**Comment by dcommander** [comment]
Please provide more details.  Are you using the native or the Java viewer?

**Comment by dcommander** [comment]
Please provide more details if you want me to fix this.  Otherwise it will be closed due to lack of user response.

**Comment by jave** [comment]
This sometimes happens to me as well, but it's not imho a big problem.

In my case I use Emacs a lot, and thus the alt key. In my case I dont think I alt-tab away a lot, rather the cursor leaves the turbovnc window. 

I can usually resolve the situation by toggling alt in the vnc window.

The same thing happens in other remote clients, such as x2go-client.

**Comment by dcommander** [comment]
Was finally able to reproduce this issue in the Windows native viewer (you didn't specify which viewer you were using, so I assume this is the same issue you were seeing.)  2.1.x pre-release build now contains the fix.

**Comment by xenium1024** [comment]
Thank you! I apologize for not responding to your previous questions. Honestly, my life has been a bit of a train wreck lately, starting a new job and such, I just haven't had time to get back to this yet. It was still in my inbox and still on my "todo" list. :-) I am indeed using the Windows native viewer (I mentioned in my original report that I was running Windows 7 ultimate 64 bit, and the 64-bit v2.1.1 (20170202) viewer and thought that was enough info, sorry, I should have mentioned I wasn't using the Java viewer.) I'll give the pre-release version a try. Is their a windows build of that available for download? I only see the source in the github repo, and I'm not set up to build on Windows, and I don't see it on Sourceforge. 

Thanks again, this was driving me crazy!

**Comment by dcommander** [comment]
https://turbovnc.org/DeveloperInfo/PreReleases

**Comment by xenium1024** [comment]
Thanks for the link. Just confirming that it's fixed for me with 2.1.2. Thanks dcommander, you rock!
