### ISSUE TITLE
Connection seems to fail due to wifi internet connection: wifi versus ethernet

### ISSUE THREAD

**Issue by saschaturbovnc** [TurboVNC/turbovnc#89]
Hello, 

Does anyone have an idea why I can use Turbovnc viewer when using ethernet, but not when I am on wifi?

Thanks in advance. 

Bw, 

Sascha

**Comment by dcommander** [comment]
No idea, unless switching to the wi-fi connection somehow enabled a firewall setting that wasn't present on your Ethernet connection.

**Comment by dcommander** [comment]
Closing as WFM.  If you have any further info, I am happy to evaluate it.
