### ISSUE TITLE
Turbovnc client closes after connection error or wrong credentials

### ISSUE THREAD

**Issue by ddavidebor** [TurboVNC/turbovnc#92]
TurboVNC quits after authentication errors and unable-to-connect errors. It would probably be more intuitive to reopen the first window to allow the user to fix the wrong hostname/credentials

**Comment by dcommander** [comment]
There's a good security reason why the viewer doesn't immediately return to the password dialog if you enter a bad password-- it's to make it more difficult for someone to design a bot that can rapidly execute a brute-force attack against the server's authentication mechanism.

I'll look into the possibility of returning to the connection dialog upon error, but I will also say that TurboVNC's behavior in this regard is similar to that of other remote display software.

**Comment by ddavidebor** [comment]
In that case it should be limited at the server, not at the client

**Comment by dcommander** [comment]
I think it already is limited at the server, but I'll check on that as well.  Please be patient, as I have about 10,000 things I'm juggling right now.  I don't know why everyone hits me up for work in August when I'm usually sitting idle throughout January and February, but such is the case, so I'm swamped at the moment.

**Comment by dcommander** [comment]
Unfortunately had to push this to 2.3.  I have been ridiculously slammed with trying to put out beta releases for three products, and I only have 24 hours left to get TurboVNC 2.2 beta out the door.  Some things just have to fall off the plate.

**Comment by dcommander** [comment]
Sincere apologies for the years-long delay in implementing this. It is now available in the dev branch and will be released in 3.1 beta1 later this year.
