### ISSUE TITLE
vncviewer 2.1.1 on macOS stops reading key input if key repeat is enabled

### ISSUE THREAD

**Issue by craigruff** [TurboVNC/turbovnc#94]
vncviewer stops accepting input if keyboard repeat is turned on and key repeat kicks in.  Screen updates and mouse cursor continue to work normally. Restarting vncviewer restores keyboard input. Oracle Java 8.144 is installed.

**Comment by craigruff** [comment]
macOS 10.12.5

**Comment by dcommander** [comment]
This is unfortunately a known issue:
https://sourceforge.net/p/turbovnc/mailman/message/34500418/

There is an easy workaround:
```
defaults write -g ApplePressAndHoldEnabled -bool false
```
which takes effect immediately and can be reversed immediately as well, should you need to re-enable the Press and Hold feature for another application.

I unfortunately don't know of a way around this in Java.  The key events are simply never reaching my code when Press and Hold is enabled.  Probably working around it would require a JNI hack, which I don't have the cycles for right now.

**Comment by craigruff** [comment]
Thanks, never heard of that before, but I use it on iOS.

**Comment by dcommander** [comment]
Yeah, that's where the feature originated.  Really hoping the Java developers eventually expose some way of programmatically disabling it.

**Comment by dcommander** [comment]
Also discovered that you can do
```
defaults write com.turbovnc.vncviewer.VncViewer ApplePressAndHoldEnabled -bool false
```
to disable Press and Hold just for the TurboVNC Viewer.  This should work when launching the viewer from our official packages, and it doesn't interfere with the global setting.

**Comment by craigruff** [comment]
> Also discovered that you can do
> 
> defaults write com.turbovnc.vncviewer.VncViewer ApplePressAndHoldEnabled -bool false
> to disable Press and Hold just for the TurboVNC Viewer. 
> 
I figured something like that was possible because Terminal certainly behaves like I expected. Thanks.

**Comment by craigruff** [comment]
> On Aug 5, 2017, at 1:22 PM, DRC <notifications@github.com> wrote:
> Also discovered that you can do
> 
> defaults write com.turbovnc.vncviewer.VncViewer ApplePressAndHoldEnabled -bool false
> to disable Press and Hold just for the TurboVNC Viewer. This should work when launching the viewer from our official packages, and it doesn't interfere with the global setting.
> 
Spoke too soon.  It doesn't seem to work for me, either launching it from the command line or by double clicking the icon.  I have to have the global setting as false to get the key repeat to function. :-(  But that doesn't really matter on my laptop.

**Comment by dcommander** [comment]
Weird.  That command works great for me on Yosemite and Sierra.  I tried launching the viewer from the icon in the Applications folder, from the icon in the dock, from the /opt/TurboVNC/bin/vncviewer script, and even from a local copy of the .app in my build directory.  The ApplePressAndHoldEnabled setting was turned off in all cases.

**Comment by dcommander** [comment]
Also found a way to work around the issue programmatically in Java (commit pushed and CI build should be available shortly.)  Although that doesn't enable key repeat, it at least allows the viewer to work properly under Sierra if ApplePressAndHoldEnabled is true.
