### ISSUE TITLE
Investigate SIMD-accelerated Zlib implementations

### ISSUE THREAD

**Issue by dcommander** [TurboVNC/turbovnc#95]
Perform low-level benchmarking with the TurboVNC Benchmark Tools and the following SIMD-enhanced Zlib implementations:

CloudFare:
https://github.com/cloudflare/zlib

Intel:
https://github.com/jtkukunas/zlib

zlib-ng:
https://github.com/Dead2/zlib-ng

Investigate the possibility of merging one of them into the TurboVNC Server (the client would be trickier, since it would require JNI.)

**Comment by dcommander** [comment]
The improvement in encoding performance was significant for the Tight+JPEG encoding methods and dramatic for the Lossless Tight+Zlib encoding method.  The improvement in decoding performance was only slight and probably not worth pursuing (which is kind of a relief, because pursuing it from Java would've been a PITA.)  All results are for 64-bit code at the moment, but I will double-check them against 32-bit code later.  In all cases, the results were obtained from a Dell Precision T3500 with quad-core 2.8 GHz Xeon W3530, 4 GB memory, CentOS 6.9, GCC 4.4.7 with maximum (`-O3`) optimization.  The baseline was the build of zlib 1.2.3 included in CentOS 6.9.  All results are expressed as a speedup relative to the baseline, for the combined encoding/decoding time of the [20 canonical RFB datasets](https://turbovnc.org/pmwiki/uploads/About/turbototiger.pdf).

**Tight + Perceptually Lossless JPEG (CL 1 = zlib level 1, JPEG 4:4:4 Q=95)**
- _[CloudFlare:](https://github.com/cloudflare/zlib/tree/836eb111a5c5df7db3f2469a867a6f7c1b2e7bdb)_
   - Encode: +16.0% (+25.6% 2D, +14.6% 3D)
   - Decode: +1.0% (+4.2% 2D, +0.7% 3D)
- _[Intel:](https://github.com/jtkukunas/zlib/tree/4b9e3f0c56ce0a354bcb11f048f870f2d0fc544e)_
   - Encode: +14.6% (+23.4% 2D, +13.2% 3D)
   - Decode: +1.3% (+4.1% 2D, +1.0% 3D)
- _[zlib-ng:](https://github.com/Dead2/zlib-ng/tree/60dedcc1ff6032ae404a05472b16b0586cacbee1)_
   - Encode: +5.3% (+55.1% 2D, +0.1% 3D)
   - Decode: +6.0% (+45.9% 2D, +3.0% 3D)
   - Note: Despite building with `--zlib-compat`, the compression ratio varied wildly (-46% to +62% for 2D, -12% to +8% for 3D) relative to the baseline.  While all of the 2D datasets were dramatically faster than the baseline, some of the 3D datasets were significantly slower (-12% for Catia, -19% for TeamCenter Vis, -29% for UniGraphics NX, -16% for GLXSpheres.)

**Tight + Medium-Quality JPEG (CL 6 = zlib level 1 w/ interframe comparison, JPEG 4:2:2 Q=80)**
- _[CloudFlare:](https://github.com/cloudflare/zlib/tree/836eb111a5c5df7db3f2469a867a6f7c1b2e7bdb)_
   - Encode: +11.4% (20.4% 2D, 10.2% 3D)
   - Decode: +1.3% (4.0% 2D, 1.0% 3D)
- _[Intel:](https://github.com/jtkukunas/zlib/tree/4b9e3f0c56ce0a354bcb11f048f870f2d0fc544e)_
   - Encode: +10.2% (+18.2% 2D, +9.0% 3D)
   - Decode: +1.1% (+3.6% 2D, +0.8% 3D)
- _[zlib-ng:](https://github.com/Dead2/zlib-ng/tree/60dedcc1ff6032ae404a05472b16b0586cacbee1)_
   - Encode: +18.9% (+46.6% 2D, +15.6% 3D)
   - Decode: +2.6% (+11.7% 2D, +1.8% 3D)
   - Note:  Despite building with `--zlib-compat`, the compression ratio varied wildly (-51% to -1% for 2D, -20% to 0% for 3D) relative to the baseline.  The UG NX dataset experienced a 15% slow-down.  All of the rest of the datasets were faster than the baseline.

**Tight + Low-Quality JPEG (CL 7 = zlib level 2 & 3 w/ interframe comparison, JPEG 4:2:0 Q=30)**
- _[CloudFlare:](https://github.com/cloudflare/zlib/tree/836eb111a5c5df7db3f2469a867a6f7c1b2e7bdb)_
   - Encode: +24.8% (+27.7% 2D, +24.4% 3D)
   - Decode: +1.0% (+3.6% 2D, +0.7% 3D)
- _[Intel:](https://github.com/jtkukunas/zlib/tree/4b9e3f0c56ce0a354bcb11f048f870f2d0fc544e)_
   - Encode: +23.4% (+24.8% 2D, +23.2% 3D)
   - Decode: +0.0% (+2.5% 2D, -0.2% 3D)
- _[zlib-ng:](https://github.com/Dead2/zlib-ng/tree/60dedcc1ff6032ae404a05472b16b0586cacbee1)_
   - Encode: +24.9% (+26.6% 2D, +24.6% 3D)
   - Decode: +3.2% (+5.5% 2D, +2.9% 3D)
   - Note:  Despite building with `--zlib-compat`, the compression ratio varied somewhat (-9% to 0% for 2D, -4% to 0% for 3D) relative to the baseline.  No slow-downs were observed, however.

**Lossless Tight (CL 0 = zlib level 0, no JPEG)**
In this case, the baseline was bypassing zlib altogether by using TurboVNC's rfbTightNoZlib extension.  Since this extension is unofficial, the purpose of these tests was to see if the extension could be obviated by using a SIMD-accelerated zlib implementation.
- _[CloudFlare:](https://github.com/cloudflare/zlib/tree/836eb111a5c5df7db3f2469a867a6f7c1b2e7bdb)_
   - Encode: -37.3% (-21.6% 2D, -39.5% 3D)
   - Decode: -43.8% (-40.6% 2D, -44.0% 3D)
- _[Intel:](https://github.com/jtkukunas/zlib/tree/4b9e3f0c56ce0a354bcb11f048f870f2d0fc544e)_
   - Encode: -35.3% (-20.4% 2D, -37.4% 3D)
   - Decode: -42.3% (-39.8% 2D, -42.5% 3D)
- _[zlib-ng:](https://github.com/Dead2/zlib-ng/tree/60dedcc1ff6032ae404a05472b16b0586cacbee1)_
   - Encode: -11.4% (-8.0% 2D, -12.0% 3D)
   - Decode: -41.5% (-38.8% 2D, -41.7% 3D)

zlib-ng came close, but not close enough.  I think we're going to need to pursue making rfbTightNoZlib an official extension.

**Lossless Tight + Zlib (CL 1 = zlib level 1 w/ interframe comparison, no JPEG)**
- _[CloudFlare:](https://github.com/cloudflare/zlib/tree/836eb111a5c5df7db3f2469a867a6f7c1b2e7bdb)_
   - Encode: +47.2% (+34.8% 2D, +48.2% 3D)
   - Decode: +9.4% (+9.8% 2D, +9.4% 3D)
- _[Intel:](https://github.com/jtkukunas/zlib/tree/4b9e3f0c56ce0a354bcb11f048f870f2d0fc544e)_
   - Encode: +32.5% (+27.9% 2D, +32.8% 3D)
   - Decode: +8.8% (+9.1% 2D, +8.8% 3D)
- _[zlib-ng:](https://github.com/Dead2/zlib-ng/tree/60dedcc1ff6032ae404a05472b16b0586cacbee1)_
   - "Error in tight encoder" ([disqualified!](https://makeagif.com/gif/zoolander-disqualified-david-bowie-7KV2wR))

At the moment, integrating the CloudFlare zlib encoder with the TurboVNC Server seems like a clear win across the board.

**Comment by dcommander** [comment]
The Intel zlib implementation has been integrated into the dev branch.  I ultimately backed away from CloudFlare, despite its superior performance, because it doesn't perform run-time CPU feature detection.  It assumes the existence of SSE 4.2, which is not available on all x86-64 CPUs, and of SSE2, which is not available on all x86 CPUs.  CloudFlare does have nascent support for NEON instructions, so it might be beneficial in the long term to merge that into TurboVNC, but at the moment, 99.9% of TurboVNC users are going to be on Intel-compatible CPUs, so the Intel solution makes our common case fast without requiring additional development effort on my part.

**Comment by ms178** [comment]
Just for your information: Chromium maintains a fork named c-zlib which includes some significant Intel SSE and ARM NEON otimizations. It might be worth a look? Maybe they'll integrate the more recent changes of Intel's branch as well in the future. 

Slides from Open Source Summit: https://events.linuxfoundation.org/wp-content/uploads/2017/11/Optimizing-Zlib-on-ARM-The-Power-of-NEON-Adenilson-Cavalcanti-ARM.pdf

Source: https://cs.chromium.org/chromium/src/third_party/zlib/

**Comment by dcommander** [comment]
Thanks for the tip.  ARM is going to overhaul the NEON accelerations in libjpeg-turbo over the next few months and then provide me some new hardware with which to test those optimizations.  I can use that hardware to test their faster implementation of libjpeg-turbo along with c-zlib.  I would definitely like to switch to a SIMD zlib implementation that is maintained in a more formal manner.

**Comment by dcommander** [comment]
At the moment, I don't have the cycles to revisit this prior to TurboVNC 3.0.  I think that #144 will do a better job of "making the common case fast" for TurboVNC 3.0 and beyond, since it would allow the Java viewer to take advantage of the Intel zlib library.  Arm support isn't a priority for TurboVNC (yet.)
